---
permalink: protect-scsql/concept_requirements_for_restoring_a_database.html 
sidebar: sidebar 
keywords: Requirements 
summary: Antes de restaurar um banco de dados SQL Server a partir de um backup do SnapCenter Plug-in para Microsoft SQL Server, você deve garantir que vários requisitos sejam atendidos. 
---
= Requisitos para restaurar um banco de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de restaurar um banco de dados SQL Server a partir de um backup do SnapCenter Plug-in para Microsoft SQL Server, você deve garantir que vários requisitos sejam atendidos.

* A instância de destino do SQL Server deve estar online e em execução antes que você possa restaurar um banco de dados.
+
Isso se aplica tanto às operações de restauração do banco de dados do usuário quanto às operações de restauração do banco de dados do sistema.

* As operações do SnapCenter agendadas para serem executadas nos dados do SQL Server que você está restaurando devem ser desabilitadas, incluindo quaisquer trabalhos agendados em servidores de gerenciamento remoto ou de verificação remota.
* Se os bancos de dados do sistema não estiverem funcionais, você deverá primeiro reconstruí-los usando um utilitário do SQL Server.
* Se você estiver instalando o plug-in, certifique-se de conceder permissões para outras funções para restaurar os backups do Grupo de Disponibilidade (AG).
+
A restauração do AG falha quando uma das seguintes condições é atendida:

+
** Se o plug-in for instalado pelo usuário do RBAC e um administrador tentar restaurar um backup do AG
** Se o plug-in for instalado por um administrador e um usuário RBAC tentar restaurar um backup do AG


* Se você estiver restaurando backups de diretório de log personalizados para um host alternativo, o SnapCenter Server e o host do plug-in deverão ter a mesma versão do SnapCenter instalada.
* Você deve ter instalado o hotfix da Microsoft, KB2887595.  O site de suporte da Microsoft contém mais informações sobre o KB2887595.
+
https://support.microsoft.com/kb/2887595["Artigo de Suporte da Microsoft 2887595: Pacote cumulativo de atualizações do Windows RT 8.1, Windows 8.1 e Windows Server 2012 R2: novembro de 2013"]

* Você deve ter feito backup dos grupos de recursos ou do banco de dados.
* Se você estiver replicando Snapshots para um espelho ou cofre, o administrador do SnapCenter deverá ter atribuído a você as máquinas virtuais de armazenamento (SVMs) para os volumes de origem e de destino.
+
Para obter informações sobre como os administradores atribuem recursos aos usuários, consulte as informações de instalação do SnapCenter .

* Todos os trabalhos de backup e clonagem devem ser interrompidos antes de restaurar o banco de dados.
* A operação de restauração pode atingir o tempo limite se o tamanho do banco de dados estiver em terabytes (TB).
+
Você deve aumentar o valor do parâmetro RESTTimeout do SnapCenter Server para 20000000 ms executando o seguinte comando: Set-SmConfigSettings -Agent -configSettings @{"RESTTimeout" = "20000000"}.  De acordo com o tamanho do banco de dados, o valor do tempo limite pode ser alterado e o valor máximo que você pode definir é 86400000 ms.



Se você quiser restaurar enquanto os bancos de dados estiverem online, a opção de restauração online deverá ser habilitada na página Restaurar.
