---
permalink: protect-scsql/concept_how_long_to_retain_transaction_log_backups_on_the_source_storage_system.html 
sidebar: sidebar 
keywords: retain transaction log backups 
summary: O plug-in SnapCenter para Microsoft SQL Server precisa de backups de log de transações para executar operações de restauração atualizadas, que restauram seu banco de dados para um intervalo entre dois backups completos. 
---
= Por quanto tempo manter backups de log de transações no sistema de armazenamento de origem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O plug-in SnapCenter para Microsoft SQL Server precisa de backups de log de transações para executar operações de restauração atualizadas, que restauram seu banco de dados para um intervalo entre dois backups completos.

Por exemplo, se o Plug-in para SQL Server fizesse um backup completo às 8h e outro backup completo às 17h, ele poderia usar o backup de log de transações mais recente para restaurar o banco de dados a qualquer momento entre 8h e 17h. Se os logs de transações não estiverem disponíveis, o Plug-in para SQL Server poderá executar apenas operações de restauração pontuais, que restauram um banco de dados ao momento em que o Plug-in para SQL Server concluiu um backup completo.

Normalmente, você precisa de operações de restauração atualizadas por apenas um ou dois dias.  Por padrão, o SnapCenter retém no mínimo dois dias.
