---
permalink: protect-scsql/reference_sources_and_destinations_for_a_restore_operation.html 
sidebar: sidebar 
keywords: restore operation 
summary: Você pode restaurar um banco de dados do SQL Server a partir de uma cópia de backup no armazenamento primário ou secundário.  Você também pode restaurar o banco de dados para destinos diferentes além do seu local original, permitindo que você escolha o destino que atende às suas necessidades. 
---
= Origens e destinos para uma operação de restauração
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode restaurar um banco de dados do SQL Server a partir de uma cópia de backup no armazenamento primário ou secundário.  Você também pode restaurar o banco de dados para destinos diferentes além do seu local original, permitindo que você escolha o destino que atende às suas necessidades.



== Fontes para uma operação de restauração

Você pode restaurar bancos de dados do armazenamento primário ou secundário.



== Destinos para uma operação de restauração

Você pode restaurar bancos de dados para vários destinos:

|===
| Destino | Descrição 


 a| 
A localização original
 a| 
Por padrão, o SnapCenter restaura o banco de dados no mesmo local na mesma instância do SQL Server.



 a| 
Um local diferente
 a| 
Você pode restaurar o banco de dados para um local diferente em qualquer instância do SQL Server no mesmo host.



 a| 
Localização original ou diferente usando nomes de banco de dados diferentes
 a| 
Você pode restaurar o banco de dados com um nome diferente para qualquer instância do SQL Server no mesmo host onde o backup foi criado.

|===

NOTE: Não há suporte para restauração em host alternativo entre servidores ESX para bancos de dados SQL em VMDKs (datastores NFS e VMFS).
