---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter .  Você deve criar credenciais para instalar plug-ins do SnapCenter e credenciais adicionais para executar operações de proteção de dados em bancos de dados ou sistemas de arquivos do Windows. 
---
= Configurar credenciais para o pacote de plug-ins do SnapCenter para Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter .  Você deve criar credenciais para instalar plug-ins do SnapCenter e credenciais adicionais para executar operações de proteção de dados em bancos de dados ou sistemas de arquivos do Windows.

.Antes de começar
* Você deve configurar as credenciais do Windows antes de instalar plug-ins.
* Você deve configurar as credenciais com privilégios de administrador, incluindo direitos de administrador no host remoto.
* Autenticação SQL em hosts Windows
+
Você deve configurar credenciais SQL após instalar plug-ins.

+
Se você estiver implantando o SnapCenter Plug-in para Microsoft SQL Server, deverá configurar as credenciais do SQL após instalar os plug-ins.  Configure uma credencial para um usuário com permissões de administrador de sistema do SQL Server.

+
O método de autenticação SQL autentica em uma instância do SQL Server.  Isso significa que uma instância do SQL Server deve ser descoberta no SnapCenter.  Portanto, antes de adicionar uma credencial SQL, você deve adicionar um host, instalar pacotes de plug-in e atualizar os recursos.  Você precisa da autenticação do SQL Server para executar operações como agendamento ou descoberta de recursos.



.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Credencial*.
. Clique em *Novo*.
. Na página Credencial, especifique as informações necessárias para configurar as credenciais:
+
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Digite um nome para a credencial.



 a| 
Nome de usuário/Senha
 a| 
Digite o nome de usuário e a senha que serão usados para autenticação.

** Administrador de domínio
+
Especifique o administrador de domínio do sistema no qual você está instalando o plug-in SnapCenter . Os formatos válidos para o campo Nome de usuário são:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Administrador local (somente para grupos de trabalho)
+
Para sistemas que pertencem a um grupo de trabalho, especifique o administrador local integrado no sistema em que você está instalando o plug-in SnapCenter . Você pode especificar uma conta de usuário local que pertença ao grupo de administradores locais se a conta de usuário tiver privilégios elevados ou se o recurso de Controle de Acesso do Usuário estiver desabilitado no sistema host.  O formato válido para o campo Nome de usuário é: `UserName`

+
Não use aspas duplas (") ou acento grave (`) nas senhas.  Você não deve usar os símbolos de menor que (<) e exclamação (!) juntos em senhas.  Por exemplo, menor que <! 10, menor que 10 <!, acento grave `12.





 a| 
Modo de autenticação
 a| 
Selecione o modo de autenticação que você deseja usar.  Se você selecionar o modo de autenticação SQL, também deverá especificar a instância do servidor SQL e o host onde a instância SQL está localizada.

|===
. Clique em *OK*.


Depois de concluir a configuração das credenciais, talvez você queira atribuir a manutenção de credenciais a um usuário ou grupo de usuários na página Usuário e Acesso.
