---
permalink: protect-scsql/task_install_the_snapcenter_plug_in_for_sql_server_silently.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: Você deve instalar o SnapCenter Plug-in para Microsoft SQL Server a partir da interface do usuário do SnapCenter .  Entretanto, se por algum motivo você não puder, você pode executar o programa de instalação do Plug-in para SQL Server de forma autônoma no modo silencioso a partir da linha de comando do Windows. 
---
= Instale o plug-in SnapCenter para Microsoft SQL Server silenciosamente a partir da linha de comando
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve instalar o SnapCenter Plug-in para Microsoft SQL Server a partir da interface do usuário do SnapCenter .  Entretanto, se por algum motivo você não puder, você pode executar o programa de instalação do Plug-in para SQL Server de forma autônoma no modo silencioso a partir da linha de comando do Windows.

.Antes de começar
* Você deve excluir a versão anterior do SnapCenter Plug-in para Microsoft SQL Server antes de instalar.
+
Para obter mais informações, consulte  https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Install_a_SnapCenter_Plug-In_manually_and_directly_from_thePlug-In_Host["Como instalar um plug-in SnapCenter manualmente e diretamente do host do plug-in"^] .



.Passos
. Valide se a pasta C:\temp existe no host do plug-in e se o usuário conectado tem acesso total a ela.
. Baixe o plug-in para o software SQL Server em C:\ProgramData\ NetApp\ SnapCenter\Package Repository.
+
Este caminho pode ser acessado a partir do host onde o SnapCenter Server está instalado.

. Copie o arquivo de instalação para o host no qual você deseja instalar o plug-in.
. Em um prompt de comando do Windows no host local, navegue até o diretório onde você salvou os arquivos de instalação do plug-in.
. Instale o plug-in para o software SQL Server:
+
`"snapcenter_windows_host_plugin.exe"/silent /debuglog"Debug_Log_Path" /log"Log_Path" BI_SNAPCENTER_PORT=Num SUITE_INSTALLDIR="Install_Directory_Path" BI_SERVICEACCOUNT=domain\\administrator BI_SERVICEPWD=password ISFeatureInstall=SCW,SCSQL`

+
Substitua os valores do espaço reservado pelos seus dados

+
** Debug_Log_Path é o nome e o local do arquivo de log do instalador do pacote.
** Log_Path é o local dos logs de instalação dos componentes do plug-in (SCW, SCSQL e SMCore).
** Num é a porta na qual o SnapCenter se comunica com o SMCore
** Install_Directory_Path é o diretório de instalação do pacote de plug-in do host.
** domain\administrator é o plug-in SnapCenter para a conta de serviço web do Microsoft Windows.
** password é a senha para a conta de serviço web do SnapCenter Plug-in para Microsoft Windows. + 
`"snapcenter_windows_host_plugin.exe"/silent /debuglog"C:\HPPW_SCSQL_Install.log" /log"C:\" BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR="C:\Program Files\NetApp\SnapCenter" BI_SERVICEACCOUNT=domain\administrator BI_SERVICEPWD=password ISFeatureInstall=SCW,SCSQL`


+

NOTE: Todos os parâmetros passados durante a instalação do Plug-in para SQL Server diferenciam maiúsculas de minúsculas.

. Monitore o agendador de tarefas do Windows, o arquivo de log de instalação principal C:\Installdebug.log e os arquivos de instalação adicionais em C:\Temp.
. Monitore o diretório %temp% para verificar se os instaladores msiexe.exe estão instalando o software sem erros.
+

NOTE: A instalação do Plug-in para SQL Server registra o plug-in no host e não no SnapCenter Server.  Você pode registrar o plug-in no SnapCenter Server adicionando o host usando a GUI do SnapCenter ou o cmdlet do PowerShell.  Depois que o host é adicionado, o plug-in é descoberto automaticamente.


