---
permalink: protect-scsql/task_clean_up_the_secondary_backup_count_using_powershell_cmdlets_for_sql.html 
sidebar: sidebar 
keywords: backups 
summary: Você pode usar o cmdlet Remove-SmBackup para limpar a contagem de backups para backups secundários que não têm instantâneos.  Talvez você queira usar este cmdlet quando o total de Snapshots exibidos na topologia Gerenciar Cópias não corresponder à configuração de retenção de Snapshot do armazenamento secundário. 
---
= Limpe a contagem de backups secundários usando cmdlets do PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o cmdlet Remove-SmBackup para limpar a contagem de backups para backups secundários que não têm Snapshot.  Talvez você queira usar este cmdlet quando o total de Snapshots exibidos na topologia Gerenciar Cópias não corresponder à configuração de retenção de Snapshot do armazenamento secundário.

Você deve ter preparado o ambiente do PowerShell para executar os cmdlets do PowerShell.

As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _Get-Help command_name_. Alternativamente, você também pode consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência do cmdlet do software SnapCenter"^] .

.Passos
. Inicie uma sessão de conexão com o SnapCenter Server para um usuário especificado usando o cmdlet Open-SmConnection.
+
[listing]
----
Open-SmConnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Limpe a contagem de backups secundários usando o parâmetro -CleanupSecondaryBackups.
+
Este exemplo limpa a contagem de backups para backups secundários sem instantâneos:

+
[listing]
----
Remove-SmBackup -CleanupSecondaryBackups
Remove-SmBackup
Are you sure want to remove the backup(s).
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
----

