---
permalink: protect-scsql/task_create_backup_policies_for_sql_server_databases.html 
sidebar: sidebar 
keywords: backup policy 
summary: Você pode criar uma política de backup para o recurso ou grupo de recursos antes de usar o SnapCenter para fazer backup de recursos do SQL Server ou pode criar uma política de backup no momento em que cria um grupo de recursos ou faz backup de um único recurso. 
---
= Crie políticas de backup para bancos de dados SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar uma política de backup para o recurso ou grupo de recursos antes de usar o SnapCenter para fazer backup de recursos do SQL Server ou pode criar uma política de backup no momento em que cria um grupo de recursos ou faz backup de um único recurso.

.Antes de começar
* Você deve ter definido sua estratégia de proteção de dados.
* Você deve estar preparado para a proteção de dados concluindo tarefas como instalar o SnapCenter, adicionar hosts, identificar recursos e criar conexões de sistema de armazenamento.
* Você deve ter configurado o diretório de log do host para backup de log.
* Você deve ter atualizado (descoberto) os recursos do SQL Server.
* Se você estiver replicando Snapshots para um espelho ou cofre, o administrador do SnapCenter deverá ter atribuído as máquinas virtuais de armazenamento (SVMs) para os volumes de origem e de destino a você.
+
Para obter informações sobre como os administradores atribuem recursos aos usuários, consulte as informações de instalação do SnapCenter .

* Se você quiser executar os scripts do PowerShell em prescripts e postscripts, defina o valor do parâmetro usePowershellProcessforScripts como true no arquivo web.config.
+
O valor padrão é falso.

* Revise os pré-requisitos e limitações específicos da sincronização ativa do SnapMirror . Para obter informações, consulte https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Limites de objetos para sincronização ativa do SnapMirror"] .


.Sobre esta tarefa
* Uma política de backup é um conjunto de regras que rege como você gerencia e mantém backups e com que frequência o recurso ou grupo de recursos é feito backup.  Além disso, você pode especificar configurações de replicação e script.  Especificar opções em uma política economiza tempo quando você deseja reutilizar a política para outro grupo de recursos.
+
O SCRIPTS_PATH é definido usando a chave PredefinedWindowsScriptsDirectory localizada no arquivo SMCoreServiceHost.exe.Config do host do plug-in.

+
Se necessário, você pode alterar esse caminho e reiniciar o serviço SMcore.  É recomendável que você use o caminho padrão por segurança.

+
O valor da chave pode ser exibido no swagger por meio da API: API /4.7/configsettings

+
Você pode usar a API GET para exibir o valor da chave.  A API SET não é suportada.

* SnapLock
+
** Se a opção 'Manter as cópias de backup por um número específico de dias' for selecionada, o período de retenção do SnapLock deverá ser menor ou igual aos dias de retenção mencionados.
+
Especificar um período de bloqueio de Snapshot impede a exclusão dos Snapshots até que o período de retenção expire. Isso pode levar à retenção de um número maior de Snapshots do que a contagem especificada na política.

+
Para o ONTAP 9.12.1 e versões anteriores, os clones criados a partir dos SnapLock Vault Snapshots como parte da restauração herdarão o tempo de expiração do SnapLock Vault. O administrador de armazenamento deve limpar manualmente os clones após o tempo de expiração do SnapLock .







== Etapa 1: Criar nome da política

. No painel de navegação esquerdo, selecione *Configurações*.
. Na página Configurações, selecione *Políticas*.
. Selecione *Novo*.
. Na página *Nome*, insira o nome e os detalhes da política.




== Etapa 2: Configurar opções de política

. Na página Tipo de política, execute as seguintes etapas:
+
.. Selecione seu tipo de armazenamento.
.. Selecione o escopo da sua política.
+
[role="tabbed-block"]
====
.Backup completo e backup de log
--
Faça backup dos arquivos de banco de dados e dos logs de transações e trunque os logs de transações.

... Selecione *Backup completo e Backup de log*.
... Insira o número máximo de bancos de dados que devem ser copiados para cada Snapshot.
+

NOTE: Você deve aumentar esse valor se quiser executar várias operações de backup simultaneamente.



--
.Backup completo
--
Faça backup dos arquivos do banco de dados.

... Selecione *Backup completo*.
... Insira o número máximo de bancos de dados que devem ser copiados para cada Snapshot.  O valor padrão é 100
+

NOTE: Você deve aumentar esse valor se quiser executar várias operações de backup simultaneamente.



--
.Backup de log
--
... Faça backup dos logs de transações.
... Selecione *Backup de log*.


--
.Backup somente cópia
--
... Se você estiver fazendo backup de seus recursos usando outro aplicativo de backup, selecione *Copiar somente backup*.


Manter os logs de transações intactos permite que qualquer aplicativo de backup restaure os bancos de dados.  Normalmente, você não deve usar a opção somente cópia em nenhuma outra circunstância.


NOTE: O Microsoft SQL não oferece suporte à opção *Somente cópia de backup* juntamente com as opções *Backup completo e Backup de log* para armazenamento secundário.

--
====






== Etapa 3: Configurar as configurações do Grupo de Disponibilidade

. Na seção Configurações do grupo de disponibilidade, execute as seguintes ações:
+
.. Faça backup somente na réplica de backup preferencial.
+
Selecione esta opção para fazer backup somente na réplica de backup preferida.  A réplica de backup preferencial é decidida pelas preferências de backup configuradas para o AG no SQL Server.

.. Selecione réplicas para backup.
+
Escolha a réplica do AG primário ou a réplica do AG secundário para o backup.

.. Selecione a prioridade de backup (prioridade mínima e máxima de backup)
+
Especifique um número mínimo de prioridade de backup e um número máximo de prioridade de backup que decidam a réplica do AG para backup.  Por exemplo, você pode ter uma prioridade mínima de 10 e uma prioridade máxima de 50.  Nesse caso, todas as réplicas do AG com prioridade maior que 10 e menor que 50 são consideradas para backup.

+
Por padrão, a prioridade mínima é 1 e a máxima é 100.



+

NOTE: Em configurações de cluster, os backups são retidos em cada nó do cluster de acordo com as configurações de retenção definidas na política.  Se o nó proprietário do AG for alterado, os backups serão feitos de acordo com as configurações de retenção e os backups do nó proprietário anterior serão mantidos.  A retenção para AG é aplicável somente no nível do nó.





== Etapa 4: Configurar as configurações de instantâneo e replicação

. Na página Snapshot e Replicação, execute as seguintes etapas:
+
.. Especifique o tipo de programação selecionando *Sob demanda*, *Por hora*, *Diário*, *Semanal* ou *Mensal*.
+
Você só pode selecionar um tipo de agendamento para uma política.

+

NOTE: Você pode especificar o agendamento (data de início, data de término e frequência) para a operação de backup ao criar um grupo de recursos.  Isso permite que você crie grupos de recursos que compartilham a mesma política e frequência de backup, mas permite que você atribua agendamentos de backup diferentes a cada política.

+

NOTE: Se você agendou para 2h00, a programação não será acionada durante o horário de verão (DST).







== Etapa 5: Configurar as configurações de retenção mais recentes

. Na seção Configurações de retenção atualizadas, dependendo do tipo de backup selecionado na página de tipo de backup, execute uma ou mais das seguintes ações:


[role="tabbed-block"]
====
.Número específico de cópias
--
Mantenha apenas um número específico de Snapshots.

. Selecione a opção *Manter backups de log aplicáveis aos últimos <número> dias* e especifique o número de dias a serem retidos.  Se você estiver próximo desse limite, talvez seja melhor excluir cópias mais antigas.


--
.Número específico de dias
--
Mantenha as cópias de segurança por um número específico de dias.

. Selecione a opção *Manter backups de log aplicáveis aos últimos <número> dias de backups completos* e especifique o número de dias para manter as cópias de backup de log.


--
====


== Etapa 6: Configurar as definições do Snapshot

. Para as configurações de retenção de backup completo, execute as seguintes ações:
+
.. Especifique o número total de instantâneos a serem mantidos
+
... Para especificar o número de instantâneos a serem mantidos, selecione *Cópias a serem mantidas*.
... Se o número de instantâneos exceder o número especificado, os instantâneos serão excluídos, com as cópias mais antigas sendo excluídas primeiro.
+

IMPORTANT: Por padrão, o valor da contagem de retenção é definido como 2.  Se você definir a contagem de retenção como 1, a operação de retenção poderá falhar porque o primeiro instantâneo será o instantâneo de referência para o relacionamento SnapVault até que um instantâneo mais recente seja replicado para o destino.

+

NOTE: O valor máximo de retenção é 1018. Os backups falharão se a retenção for definida como um valor maior do que o suportado pela versão subjacente do NetApp ONTAP .







. Período de tempo para manter instantâneos
+
.. Se você quiser especificar o número de dias pelos quais deseja manter os instantâneos antes de excluí-los, selecione *Manter cópias por*.


. Selecione *Período de bloqueio de cópia de instantâneo* e especifique a duração em dias, meses ou anos.
+
O período de retenção do Snaplock deve ser inferior a 100 anos.

. Selecione um rótulo de política.
+

NOTE: Você pode atribuir rótulos SnapMirror a snapshots primários para replicação remota, permitindo que os snapshots primários descarreguem a operação de replicação de snapshots do SnapCenter para sistemas secundários ONTAP . Isso pode ser feito sem habilitar a opção SnapMirror ou SnapVault na página de política.





== Etapa 7: Configurar opções de replicação secundária

. Na seção Selecionar opções de replicação secundária, selecione uma ou ambas as seguintes opções de replicação secundária:


[role="tabbed-block"]
====
.Atualizar SnapMirror
--
Atualize o SnapMirror após criar uma cópia local do Snapshot.

. Selecione esta opção para criar cópias espelhadas de conjuntos de backup em outro volume (SnapMirror).
+
Esta opção deve ser habilitada para sincronização ativa do SnapMirror .

+
Durante a replicação secundária, o tempo de expiração do SnapLock carrega o tempo de expiração do SnapLock primário.  Clicar no botão *Atualizar* na página Topologia atualiza o tempo de expiração do SnapLock secundário e primário que são recuperados do ONTAP.

+
Ver link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["Exibir backups e clones do SQL Server na página Topologia"] .



--
.Atualizar SnapVault
--
Atualize o SnapVault após criar uma cópia do Snapshot.

. Selecione esta opção para executar a replicação de backup de disco para disco.
+
Durante a replicação secundária, o tempo de expiração do SnapLock carrega o tempo de expiração do SnapLock primário.  Clicar no botão *Atualizar* na página Topologia atualiza o tempo de expiração do SnapLock secundário e primário que são recuperados do ONTAP.

+
Quando o SnapLock é configurado somente no secundário do ONTAP conhecido como SnapLock Vault, clicar no botão *Atualizar* na página Topologia atualiza o período de bloqueio no secundário recuperado do ONTAP.

+
Para mais informações sobre o SnapLock Vault, consulte https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["Enviar cópias do Snapshot para o WORM em um destino de cofre"]

+
Ver link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["Exibir backups e clones do SQL Server na página Topologia"] .



--
.Contagem de novas tentativas de erro
--
. Insira o número de tentativas de replicação que devem ocorrer antes que o processo seja interrompido.


--
====


== Etapa 8: Configurar as definições do script

. Na página Script, insira o caminho e os argumentos do prescript ou postscript que devem ser executados antes ou depois da operação de backup, respectivamente.
+
Por exemplo, você pode executar um script para atualizar traps SNMP, automatizar alertas e enviar logs.

+

NOTE: O caminho de prescrições ou pós-escritos não deve incluir unidades ou compartilhamentos.  O caminho deve ser relativo ao SCRIPTS_PATH.

+

NOTE: Você deve configurar a política de retenção do SnapMirror no ONTAP para que o armazenamento secundário não atinja o limite máximo de Snapshots.





== Etapa 9: Configurar as configurações de verificação

Na página Verificação, execute as seguintes etapas:

. Na seção Executar verificação para os seguintes agendamentos de backup, selecione a frequência do agendamento.
. Na seção Opções de verificação de consistência do banco de dados, execute as seguintes ações:
+
.. Limitar a estrutura de integridade à estrutura física do banco de dados (PHYSICAL_ONLY)
+
... Selecione *Limitar a estrutura de integridade à estrutura física do banco de dados (PHYSICAL_ONLY)* para limitar a verificação de integridade à estrutura física do banco de dados e detectar páginas quebradas, falhas de soma de verificação e falhas comuns de hardware que afetam o banco de dados.


.. Suprimir todas as mensagens de informação (SEM INFOMSGS)
+
... Selecione *Suprimir todas as mensagens informativas (NO_INFOMSGS)* para suprimir todas as mensagens informativas.  Selecionado por padrão.


.. Exibir todas as mensagens de erro relatadas por objeto (ALL_ERRORMSGS)
+
... Selecione *Exibir todas as mensagens de erro relatadas por objeto (ALL_ERRORMSGS)* para exibir todos os erros relatados por objeto.


.. Não verificar índices não agrupados (NOINDEX)
+
... Selecione *Não verificar índices não agrupados (NOINDEX)* se não quiser verificar índices não agrupados.  O banco de dados SQL Server usa o Microsoft SQL Server Database Consistency Checker (DBCC) para verificar a integridade lógica e física dos objetos no banco de dados.


.. Limite as verificações e obtenha os bloqueios em vez de usar um Snapshot de banco de dados interno (TABLOCK)
+
... Selecione *Limitar as verificações e obter os bloqueios em vez de usar uma cópia de instantâneo do banco de dados interno (TABLOCK)* para limitar as verificações e obter os bloqueios em vez de usar um instantâneo do banco de dados interno.




. Na seção *Backup de log*, selecione *Verificar backup de log após a conclusão* para verificar o backup de log após a conclusão.
. Na seção *Configurações do script de verificação*, insira o caminho e os argumentos do prescript ou postscript que devem ser executados antes ou depois da operação de verificação, respectivamente.
+

NOTE: O caminho de prescrições ou pós-escritos não deve incluir unidades ou compartilhamentos.  O caminho deve ser relativo ao SCRIPTS_PATH.





== Etapa 10: Resumo da revisão

. Revise o resumo e selecione *Concluir*.

