---
permalink: protect-sco/alternate-ways-install-plug-in-linux-aix.html 
sidebar: sidebar 
keywords: alternate methods, install, plug-ins package, linux, aix, remote hosts, cmdlets, cluster host, silent mode, console mode 
summary: Você pode usar outras maneiras alternativas para instalar o Pacote de plug-ins do SnapCenter para Linux ou o Pacote de plug-ins do SnapCenter para AIX. 
---
= Formas alternativas de instalar o pacote de plug-ins para Linux ou AIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você também pode instalar o Pacote de Plug-ins para Linux ou AIX manualmente usando os cmdlets ou CLIs.

Antes de instalar o plug-in manualmente, você deve validar a assinatura do pacote binário usando a chave *snapcenter_public_key.pub* e *snapcenter_linux_host_plugin.bin.sig* localizadas em _C:\ProgramData\ NetApp\ SnapCenter\Package Repository_.


NOTE: Certifique-se de que o *OpenSSL 1.0.2g* esteja instalado no host onde você deseja instalar o plug-in.

Valide a assinatura do pacote binário executando o comando:

* Para host Linux: `openssl dgst -sha256 -verify snapcenter_public_key.pub -signature snapcenter_linux_host_plugin.bin.sig snapcenter_linux_host_plugin.bin`
* Para host AIX: `openssl dgst -sha256 -verify snapcenter_public_key.pub -signature snapcenter_aix_host_plugin.bsx.sig snapcenter_aix_host_plugin.bsx`




== Instalar em vários hosts remotos usando cmdlets

Você deve usar o cmdlet _Install-SmHostPackage_ do PowerShell para instalar o Pacote de plug-ins do SnapCenter para Linux ou o Pacote de plug-ins do SnapCenter para AIX em vários hosts.

*O que você vai precisar*

Você deve estar conectado ao SnapCenter como um usuário de domínio com direitos de administrador local em cada host no qual deseja instalar o pacote de plug-in.

*Passos*

. Inicie o PowerShell.
. No host do SnapCenter Server, estabeleça uma sessão usando o cmdlet _Open-SmConnection_ e insira suas credenciais.
. Instale o pacote de plug-ins SnapCenter para Linux ou o pacote de plug-ins SnapCenter para AIX usando o cmdlet _Install-SmHostPackage_ e os parâmetros necessários.
+
Você pode usar a opção _-skipprecheck_ quando já tiver instalado os plug-ins manualmente e não quiser validar se o host atende aos requisitos para instalar o plug-in.

+

NOTE: O script de pré-verificação não valida o status do firewall da porta do plug-in se ele estiver especificado nas regras de rejeição do firewall.

. Insira suas credenciais para instalação remota.


As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _Get-Help command_name_. Alternativamente, você também pode consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência do cmdlet do software SnapCenter"^] .



== Instalar no host do cluster

Você deve instalar o SnapCenter Plug-ins Package para Linux ou o SnapCenter Plug-ins Package para AIX em ambos os nós do host do cluster.

Cada um dos nós do host do cluster tem dois IPs.  Um dos IPs será o IP público dos respectivos nós e o segundo IP será o IP do cluster compartilhado entre os dois nós.

*Passos*

. Instale o SnapCenter Plug-ins Package para Linux ou o SnapCenter Plug-ins Package para AIX em ambos os nós do host do cluster.
. Valide se os valores corretos para os parâmetros SNAPCENTER_SERVER_HOST, SPL_PORT, SNAPCENTER_SERVER_PORT e SPL_ENABLED_PLUGINS estão especificados no arquivo spl.properties localizado em _/var/opt/snapcenter/spl/etc/_.
+
Se SPL_ENABLED_PLUGINS não estiver especificado em spl.properties, você poderá adicioná-lo e atribuir o valor SCO,SCU.

. No host do SnapCenter Server, estabeleça uma sessão usando o cmdlet _Open-SmConnection_ e insira suas credenciais.
. Em cada um dos nós, defina os IPs preferenciais do nó usando o comando _Set-PreferredHostIPsInStorageExportPolicy_ sccli e os parâmetros necessários.
. No host do SnapCenter Server, adicione uma entrada para o IP do cluster e o nome DNS correspondente em _C:\Windows\System32\drivers\etc\hosts_.
. Adicione o nó ao SnapCenter Server usando o cmdlet _Add-SmHost_ especificando o IP do cluster para o nome do host.


Descubra o banco de dados Oracle no nó 1 (supondo que o IP do cluster esteja hospedado no nó 1) e crie um backup do banco de dados.  Se ocorrer um failover, você poderá usar o backup criado no nó 1 para restaurar o banco de dados no nó 2.  Você também pode usar o backup criado no nó 1 para criar um clone no nó 2.


NOTE: Haverá volumes, diretórios e arquivos de bloqueio obsoletos se o failover ocorrer enquanto qualquer outra operação do SnapCenter estiver em execução.



== Instalar pacote de plug-ins para Linux no modo silencioso

Você pode instalar o pacote de plug-ins SnapCenter para Linux no modo silencioso usando a interface de linha de comando (CLI).

*O que você vai precisar*

* Você deve revisar os pré-requisitos para instalar o pacote de plug-ins.
* Você deve garantir que a variável de ambiente DISPLAY não esteja definida.
+
Se a variável de ambiente DISPLAY estiver definida, você deverá executar unset DISPLAY e tentar instalar manualmente o plug-in.



*Sobre esta tarefa*

Você precisa fornecer as informações de instalação necessárias ao instalar no modo console, enquanto na instalação no modo silencioso você não precisa fornecer nenhuma informação de instalação.

*Passos*

. Baixe o pacote de plug-ins do SnapCenter para Linux no local de instalação do SnapCenter Server.
+
O caminho de instalação padrão é _C:\ProgramData\ NetApp\ SnapCenter\PackageRepository_.  Este caminho pode ser acessado a partir do host onde o SnapCenter Server está instalado.

. No prompt de comando, navegue até o diretório onde você baixou o arquivo de instalação.
. Correr
+
`./SnapCenter_linux_host_plugin.bin-i silent-DPORT=8145-DSERVER_IP=SnapCenter_Server_FQDN-DSERVER_HTTPS_PORT=SnapCenter_Server_Port-DUSER_INSTALL_DIR==/opt/custom_path`

. Edite o arquivo spl.properties localizado em _/var/opt/snapcenter/spl/etc/_ para adicionar SPL_ENABLED_PLUGINS=SCO,SCU e reinicie o serviço SnapCenter Plug-in Loader .



IMPORTANT: A instalação do pacote de plug-ins registra os plug-ins no host e não no SnapCenter Server.  Você deve registrar os plug-ins no SnapCenter Server adicionando o host usando a GUI do SnapCenter ou o cmdlet do PowerShell.  Ao adicionar o host, selecione “Nenhum” como credencial.  Depois que o host é adicionado, os plug-ins instalados são descobertos automaticamente.



== Instalar pacote de plug-ins para AIX no modo silencioso

Você pode instalar o pacote de plug-ins SnapCenter para AIX no modo silencioso usando a interface de linha de comando (CLI).

*O que você vai precisar*

* Você deve revisar os pré-requisitos para instalar o pacote de plug-ins.
* Você deve garantir que a variável de ambiente DISPLAY não esteja definida.
+
Se a variável de ambiente DISPLAY estiver definida, você deverá executar unset DISPLAY e tentar instalar manualmente o plug-in.



*Passos*

. Baixe o pacote de plug-ins do SnapCenter para AIX do local de instalação do SnapCenter Server.
+
O caminho de instalação padrão é _C:\ProgramData\ NetApp\ SnapCenter\PackageRepository_.  Este caminho pode ser acessado a partir do host onde o SnapCenter Server está instalado.

. No prompt de comando, navegue até o diretório onde você baixou o arquivo de instalação.
. Correr
+
`./snapcenter_aix_host_plugin.bsx-i silent-DPORT=8145-DSERVER_IP=SnapCenter_Server_FQDN-DSERVER_HTTPS_PORT=SnapCenter_Server_Port-DUSER_INSTALL_DIR==/opt/custom_path-DINSTALL_LOG_NAME=SnapCenter_AIX_Host_Plug-in_Install_MANUAL.log-DCHOSEN_FEATURE_LIST=CUSTOMDSPL_USER=install_user`

. Edite o arquivo spl.properties localizado em _/var/opt/snapcenter/spl/etc/_ para adicionar SPL_ENABLED_PLUGINS=SCO,SCU e reinicie o serviço SnapCenter Plug-in Loader .



IMPORTANT: A instalação do pacote de plug-ins registra os plug-ins no host e não no SnapCenter Server.  Você deve registrar os plug-ins no SnapCenter Server adicionando o host usando a GUI do SnapCenter ou o cmdlet do PowerShell.  Ao adicionar o host, selecione “Nenhum” como credencial.  Depois que o host é adicionado, os plug-ins instalados são descobertos automaticamente.
