---
permalink: protect-sco/catalog-backups.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: Como o SnapCenter descobre bancos de dados Oracle. 
---
= Como catalogar backups com o Oracle Recovery Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode catalogar os backups de bancos de dados Oracle usando o Oracle Recovery Manager (RMAN) para armazenar as informações de backup no repositório Oracle RMAN.

Os backups catalogados podem ser usados posteriormente para restauração em nível de bloco ou operações de recuperação pontual de tablespace.  Quando você não precisar desses backups catalogados, poderá remover as informações do catálogo.

O banco de dados deve estar em estado montado ou superior para catalogação.  Você pode executar catalogação em backups de dados, backups de log de arquivo e backups completos.  Se a catalogação estiver habilitada para um backup de um grupo de recursos que tenha vários bancos de dados, a catalogação será executada para cada banco de dados.  Para bancos de dados Oracle RAC, a catalogação será realizada no nó preferencial onde o banco de dados estiver pelo menos no estado montado.

Se você quiser catalogar backups de um banco de dados RAC, certifique-se de que nenhuma outra tarefa esteja em execução para esse banco de dados.  Se outra tarefa estiver em execução, a operação de catalogação falhará em vez de ser enfileirada.



== Banco de dados de catálogo externo

Por padrão, o arquivo de controle do banco de dados de destino é usado para catalogação.  Se desejar adicionar um banco de dados de catálogo externo, você poderá configurá-lo especificando a credencial e o nome do Transparent Network Substrate (TNS) do catálogo externo usando o assistente de configurações de banco de dados na interface gráfica do usuário (GUI) do SnapCenter .  Você também pode configurar o banco de dados de catálogo externo a partir da CLI executando o comando Configure-SmOracleDatabase com as opções -OracleRmanCatalogCredentialName e -OracleRmanCatalogTnsName.



== Comando RMAN

Se você habilitou a opção de catalogação ao criar uma política de backup do Oracle na GUI do SnapCenter , os backups serão catalogados usando o Oracle RMAN como parte da operação de backup.  Você também pode executar a catalogação adiada de backups executando o `Catalog-SmBackupWithOracleRMAN` comando.

Após catalogar os backups, você pode executar o `Get-SmBackupDetails` comando para obter as informações de backup catalogadas, como a tag para arquivos de dados catalogados, o caminho do catálogo do arquivo de controle e os locais de log do arquivo catalogado.



== Formato de nomenclatura

Se o nome do grupo de discos ASM for maior ou igual a 16 caracteres, a partir do SnapCenter 3.0, o formato de nomenclatura usado para o backup será SC_HASHCODEofDISKGROUP_DBSID_BACKUPID.  No entanto, se o nome do grupo de discos tiver menos de 16 caracteres, o formato de nomenclatura usado para o backup será DISKGROUPNAME_DBSID_BACKUPID, que é o mesmo formato usado no SnapCenter 2.0.

O HASHCODEofDISKGROUP é um número gerado automaticamente (2 a 10 dígitos) exclusivo para cada grupo de discos ASM.



== Operações de verificação cruzada

Você pode executar verificações cruzadas para atualizar informações desatualizadas do repositório RMAN sobre backups cujos registros de repositório não correspondem ao seu status físico.  Por exemplo, se um usuário remover logs arquivados do disco com um comando do sistema operacional, o arquivo de controle ainda indicará que os logs estão no disco, quando na verdade não estão.

A operação de verificação cruzada permite que você atualize o arquivo de controle com as informações.  Você pode habilitar a verificação cruzada executando o comando Set-SmConfigSettings e atribuindo o valor TRUE ao parâmetro ENABLE_CROSSCHECK.  O valor padrão é definido como FALSO.

`sccli Set-SmConfigSettings-ConfigSettingsTypePlugin-PluginCodeSCO-ConfigSettings "KEY=ENABLE_CROSSCHECK, VALUE=TRUE"`



== Remover informações do catálogo

Você pode remover as informações do catálogo executando o comando Uncatalog-SmBackupWithOracleRMAN.  Não é possível remover as informações do catálogo usando a GUI do SnapCenter .  No entanto, as informações de um backup catalogado são removidas durante a exclusão do backup ou durante a exclusão do grupo de retenção e recursos associado a esse backup catalogado.


NOTE: Quando você força a exclusão do host SnapCenter , as informações dos backups catalogados associados a esse host não são removidas.  Você deve remover informações de todos os backups catalogados para esse host antes de forçar a exclusão do host.

Se a catalogação e a descatalogação falharem porque o tempo de operação excedeu o valor de tempo limite especificado para o parâmetro ORACLE_PLUGIN_RMAN_CATALOG_TIMEOUT, você deverá modificar o valor do parâmetro executando o seguinte comando:

`/opt/Netapp/snapcenter/spl/bin/sccli Set-SmConfigSettings-ConfigSettingsType Plugin -PluginCode SCO-ConfigSettings "KEY=ORACLE_PLUGIN_RMAN_CATALOG_TIMEOUT,VALUE=user_defined_value"`

Após modificar o valor do parâmetro, reinicie o serviço SnapCenter Plug-in Loader (SPL) executando o seguinte comando:

`/opt/NetApp/snapcenter/spl/bin/spl restart`

As informações sobre os parâmetros que podem ser usados com o comando e suas descrições podem ser obtidas executando Get-Help command_name. Alternativamente, você pode consultar o https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["Guia de referência de comandos do software SnapCenter"^] .
