---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-backup.html 
sidebar: sidebar 
keywords: environment variable, predefined, prescript, postscript, backup, policy 
summary: O SnapCenter permite que você use as variáveis ​​de ambiente predefinidas ao executar o prescript e o postscript ao criar políticas de backup. 
---
= Variáveis de ambiente predefinidas para prescript e postscript específicos de backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter permite que você use as variáveis ​​de ambiente predefinidas ao executar o prescript e o postscript ao criar políticas de backup.  Essa funcionalidade é suportada por todas as configurações do Oracle, exceto VMDK.

O SnapCenter predefine os valores dos parâmetros que serão diretamente acessíveis no ambiente onde os scripts de shell são executados.  Você não precisa especificar manualmente os valores desses parâmetros ao executar os scripts.



== Variáveis de ambiente predefinidas com suporte para criação de política de backup

* *SC_JOB_ID* especifica o ID do trabalho da operação.
+
Exemplo: 256

* *SC_ORACLE_SID* especifica o identificador do sistema do banco de dados.
+
Se a operação envolver vários bancos de dados, o parâmetro conterá nomes de bancos de dados separados por barra vertical.

+
Este parâmetro será preenchido para volumes de aplicativos.

+
Exemplo: NFSB32|NFSB31

* *SC_HOST* especifica o nome do host do banco de dados.
+
Para RAC, o nome do host será o nome do host no qual o backup será executado.

+
Este parâmetro será preenchido para volumes de aplicativos.

+
Exemplo: scsmohost2.gdl.englabe.netapp.com

* *SC_OS_USER* especifica o proprietário do sistema operacional do banco de dados.
+
Os dados serão formatados como <db1>@<osuser1>|<db2>@<osuser2>.

+
Exemplo: NFSB31@oracle|NFSB32@oracle

* *SC_OS_GROUP* especifica o grupo de sistema operacional do banco de dados.
+
Os dados serão formatados como <db1>@<osgroup1>|<db2>@<osgroup2>.

+
Exemplo: NFSB31@install|NFSB32@oinstall

* *SC_BACKUP_TYPE*" especifica o tipo de backup (completo on-line, dados on-line, log on-line, desligamento off-line, montagem off-line)
+
Exemplos:

+
** Para backup completo: ONLINEFULL
** backup somente de dados: ONLINEDATA
** Para backup somente de log: ONLINELOG


* *SC_BACKUP_NAME* especifica o nome do backup.
+
Este parâmetro será preenchido para volumes de aplicativos.

+
Exemplo: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1|AV@RG2_scspr2417819002_07-20-2021_12.16.48.9267

* *SC_BACKUP_ID* especifica o ID do backup.
+
Este parâmetro será preenchido para volumes de aplicativos.

+
Exemplo: DADOS@203|LOG@205|AV@207

* *SC_ORACLE_HOME* especifica o caminho do diretório inicial do Oracle.
+
Exemplo: NFSB32@/ora01/app/oracle/product/18.1.0/db_1|NFSB31@/ora01/app/oracle/product/18.1.0/db_1

* *SC_BACKUP_RETENTION* especifica o período de retenção definido na política.
+
Exemplos:

+
** Para backup completo: De hora em hora|DADOS@DIAS:3|LOG@CONTAGEM:4
** Para backup de dados somente sob demanda: Ondemand|DATA@COUNT:2
** Para backup somente de log sob demanda: Ondemand|LOG@COUNT:2


* *SC_RESOURCE_GROUP_NAME* especifica o nome do grupo de recursos.
+
Exemplo: RG1

* *SC_BACKUP_POLICY_NAME* especifica o nome da política de backup.
+
Exemplo: backup_policy

* *SC_AV_NAME* especifica os nomes dos volumes do aplicativo.
+
Exemplo: AV1|AV2

* *SC_PRIMARY_DATA_VOLUME_FULL_PATH* especifica o mapeamento de armazenamento do SVM para o volume do diretório de arquivos de dados.  Será o nome do volume pai para luns e qtrees.
+
Os dados serão formatados como <db1>@<SVM1:volume1>|<db2>@<SVM2:volume2>.

+
Exemplos:

+
** Para 2 bancos de dados no mesmo grupo de recursos: NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA|NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA
** Para um único banco de dados com arquivos de dados distribuídos em vários volumes: buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA,herculus:/vol/scspr2417819002_NFS


* *SC_PRIMARY_ARCHIVELOGS_VOLUME_FULL_PATH* especifica o mapeamento de armazenamento do SVM para o volume do diretório de arquivos de logs.  Será o nome do volume pai para luns e qtrees.
+
Exemplos:

+
** Para instância de banco de dados única: buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO
** Para múltiplas instâncias de banco de dados: NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO|NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO


* *SC_PRIMARY_FULL_SNAPSHOT_NAME_FOR_TAG* especifica a lista de Snapshots contendo o nome do sistema de armazenamento e o nome do volume.
+
Exemplos:

+
** Para instância de banco de dados única: buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** Para várias instâncias de banco de dados: NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1 |NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1


* *SC_PRIMARY_SNAPSHOT_NAMES* especifica os nomes dos Snapshots primários criados durante o backup.
+
Exemplos:

+
** Para instância de banco de dados única: RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** Para várias instâncias de banco de dados: NFSB32@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1|NFSB31@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** Para instantâneos de grupo de consistência que envolvem 2 volumes: cg3_R80404CBEF5V1_04-05-2021_03.08.03.4945_0_bfc279cc-28ad-465c-9d60-5487ac17b25d_2021_4_5_3_8_58_350


* *SC_PRIMARY_MOUNT_POINTS* especifica os detalhes do ponto de montagem que fazem parte do backup.
+
Os detalhes incluem o diretório no qual os volumes são montados e não o pai imediato do arquivo sob backup.  Para uma configuração ASM, é o nome do grupo de discos.

+
Os dados serão formatados como <db1>@<mountpoint1,mountpoint2>|<db2>@<mountpoint1,mountpoint2>.

+
Exemplos:

+
** Para instância de banco de dados única: /mnt/nfsdb3_data,/mnt/nfsdb3_log,/mnt/nfsdb3_data1
** Para várias instâncias de banco de dados: NFSB31@/mnt/nfsdb31_data,/mnt/nfsdb31_log,/mnt/nfsdb31_data1|NFSB32@/mnt/nfsdb32_data,/mnt/nfsdb32_log,/mnt/nfsdb32_data1
** Para ASM: +DATA2DG,+LOG2DG


* *SC_PRIMARY_SNAPSHOTS_AND_MOUNT_POINTS* especifica os nomes dos snapshots criados durante o backup de cada um dos pontos de montagem.
+
Exemplos:

+
** Para instância de banco de dados única: RG2_scspr2417819002_07-21-2021_02.28.26.3973_0:/mnt/nfsb32_data,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1:/mnt/nfsb31_log
** Para múltiplas instâncias de banco de dados: NFSB32@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0:/mnt/nfsb32_data,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1:/mnt/nfsb31_log|NFSB31@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0:/mnt/nfsb31_data,RG2_scspr2417819002_07-21-2021_02.28.26.3973_1:/mnt/nfsb32_log


* *SC_ARCHIVELOGS_LOCATIONS* especifica o local do diretório de logs de arquivamento.
+
Os nomes dos diretórios serão os pais imediatos dos arquivos de log de arquivamento.  Se os logs de arquivamento forem colocados em mais de um local, todos os locais serão capturados.  Isso também inclui os cenários FRA.  Se softlinks forem usados para o diretório, o mesmo será preenchido.

+
Exemplos:

+
** Para banco de dados único no NFS: /mnt/nfsdb2_log
** Para vários bancos de dados no NFS e para os logs de arquivamento do banco de dados NFSB31 que são colocados em dois locais diferentes: NFSB31@/mnt/nfsdb31_log1,/mnt/nfsdb31_log2|NFSB32@/mnt/nfsdb32_log
** Para ASM: +LOG2DG/ASMDB2/ARCHIVELOG/2021_07_15


* *SC_REDO_LOGS_LOCATIONS* especifica o local do diretório de logs de refazer.
+
Os nomes dos diretórios serão o pai imediato dos arquivos de log de refazer.  Se softlinks forem usados para o diretório, o mesmo será preenchido.

+
Exemplos:

+
** Para banco de dados único no NFS: /mnt/nfsdb2_data/newdb1
** Para vários bancos de dados no NFS: NFSB31@/mnt/nfsdb31_data/newdb31|NFSB32@/mnt/nfsdb32_data/newdb32
** Para ASM: +LOG2DG/ASMDB2/ONLINELOG


* *SC_CONTROL_FILES_LOCATIONS* especifica o local do diretório dos arquivos de controle.
+
Os nomes dos diretórios serão os pais imediatos dos arquivos de controle.  Se softlinks forem usados para o diretório, o mesmo será preenchido.

+
Exemplos:

+
** Para banco de dados único no NFS: /mnt/nfsdb2_data/fra/newdb1,/mnt/nfsdb2_data/newdb1
** Para vários bancos de dados no NFS: NFSB31@/mnt/nfsdb31_data/fra/newdb31,/mnt/nfsdb31_data/newdb31|NFSB32@/mnt/nfsdb32_data/fra/newdb32,/mnt/nfsdb32_data/newdb32
** Para ASM: +LOG2DG/ASMDB2/CONTROLFILE


* *SC_DATA_FILES_LOCATIONS*" especifica o local do diretório dos arquivos de dados.
+
Os nomes dos diretórios serão os pais imediatos dos arquivos de dados.  Se softlinks forem usados para o diretório, o mesmo será preenchido.

+
Exemplos:

+
** Para banco de dados único no NFS: /mnt/nfsdb3_data1,/mnt/nfsdb3_data/NEWDB3/datafile
** Para vários bancos de dados no NFS: NFSB31@/mnt/nfsdb31_data1,/mnt/nfsdb31_data/NEWDB31/datafile|NFSB32@/mnt/nfsdb32_data1,/mnt/nfsdb32_data/NEWDB32/datafile
** Para ASM: +DATA2DG/ASMDB2/DATAFILE,+DATA2DG/ASMDB2/TEMPFILE


* *SC_SNAPSHOT_LABEL* especifica o nome dos rótulos secundários.
+
Exemplos: por hora, diariamente, semanalmente, mensalmente ou rótulo personalizado.





== Delimitadores suportados

* *:* é usado para separar o nome do SVM e o nome do volume
+
Exemplo: buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1

* *@* é usado para separar dados do nome do banco de dados e para separar o valor da sua chave.
+
Exemplos:

+
** NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1 |NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** NFSB31@oracle|NFSB32@oracle


* *|* é usado para separar os dados entre dois bancos de dados diferentes e para separar os dados entre duas entidades diferentes para os parâmetros SC_BACKUP_ID, SC_BACKUP_RETENTION e SC_BACKUP_NAME.
+
Exemplos:

+
** DADOS@203|LOG@205
** Por hora|DADOS@DIAS:3|LOG@CONTAGEM:4
** DADOS@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1


* */* é usado para separar o nome do volume do seu Snapshot para os parâmetros SC_PRIMARY_SNAPSHOT_NAMES e SC_PRIMARY_FULL_SNAPSHOT_NAME_FOR_TAG.
+
Exemplo: NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1

* *,* é usado para separar conjuntos de variáveis para o mesmo banco de dados.
+
Exemplo: NFSB32@buck:/vol/scspr2417819002_NFS_CDB_NFSB32_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB32_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1 |NFSB31@buck:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA/RG2_scspr2417819002_07-21-2021_02.28.26.3973_0,buck:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO/RG2_scspr2417819002_07-21-2021_02.28.26.3973_1


