---
permalink: protect-sco/supported_backup_configs.html 
sidebar: sidebar 
keywords: backup type, preferred nodes, catalog backups, schedules, backup name format, retention, verification 
summary: O SnapCenter suporta backup de diferentes configurações de banco de dados Oracle. 
---
= Configurações de banco de dados Oracle suportadas para backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter suporta backup de diferentes configurações de banco de dados Oracle.

* Oracle autônomo
* Clusters de aplicativos reais Oracle (RAC)
* Oracle Standalone Legacy
* Banco de Dados de Contêineres Autônomos Oracle (CDB)
* Oracle Data Guard em espera
+
Você só pode criar backups de montagem offline de bancos de dados standby do Data Guard.  Backup com desligamento offline, backup somente de log de arquivo e backup completo não são suportados.

* Oracle Active Data Guard em espera
+
Você só pode criar backups on-line de bancos de dados em espera do Active Data Guard.  O backup somente do log de arquivo e o backup completo não são suportados.

+
Antes de criar um backup do banco de dados Data Guard standby ou Active Data Guard standby, o processo de recuperação gerenciada (MRP) é interrompido e, depois que o backup é criado, o MRP é iniciado.

* Gerenciamento Automático de Armazenamento (ASM)
+
** ASM autônomo e ASM RAC em disco de máquina virtual (VMDK)
+
Entre todos os métodos de restauração suportados para bancos de dados Oracle, você pode executar somente a restauração de conexão e cópia de bancos de dados ASM RAC no VMDK.

** ASM autônomo e ASM RAC no mapeamento de dispositivos Raw (RDM) + Você pode executar operações de backup, restauração e clonagem em bancos de dados Oracle no ASM, com ou sem ASMLib.
** Driver de filtro Oracle ASM (ASMFD)
+
As operações de migração e clonagem de PDB não são suportadas.

** Oracle Flex ASM




Para obter as informações mais recentes sobre as versões Oracle suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["Ferramenta de Matriz de Interoperabilidade da NetApp"^] .
