---
permalink: protect-sco/task_restore_and_recover_oracle_databases_using_unix_commands.html 
sidebar: sidebar 
keywords: restore, recover, CLI 
summary: O fluxo de trabalho de restauração e recuperação inclui planejamento, execução de operações de restauração e recuperação e monitoramento das operações. 
---
= Restaurar e recuperar bancos de dados Oracle usando comandos UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O fluxo de trabalho de restauração e recuperação inclui planejamento, execução de operações de restauração e recuperação e monitoramento das operações.

*Sobre esta tarefa*

* Você deve executar os seguintes comandos para estabelecer a conexão com o SnapCenter Server, listar os backups, recuperar suas informações e restaurar o backup.
+
As informações sobre os parâmetros que podem ser usados com o comando e suas descrições podem ser obtidas executando Get-Help _command_name_. Alternativamente, você também pode consultar o https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["Guia de referência de comandos do software SnapCenter"^] .

* Para a operação de restauração de sincronização ativa do SnapMirror , você deve selecionar o backup do local principal.


*Passos*

. Iniciar uma sessão de conexão com o SnapCenter Server para um usuário especificado: _Open-SmConnection_
. Recupere as informações sobre os backups que você deseja restaurar: _Get-SmBackup_
. Recupere as informações detalhadas sobre o backup especificado: _Get-SmBackupDetails_
+
Este comando recupera informações detalhadas sobre o backup de um recurso especificado com um ID de backup fornecido.  As informações incluem nome do banco de dados, versão, SCN inicial e final, tablespaces, bancos de dados plugáveis e seus tablespaces.

. Restaurar dados do backup: _Restore-SmBackup_

