---
permalink: protect-sco/task_refresh_a_clone.html 
sidebar: sidebar 
keywords: refresh clone, clone 
summary: Você pode atualizar o clone executando o comando “Refresh-SmClone”.  Este comando cria um backup do banco de dados, exclui o clone existente e cria um clone com o mesmo nome. 
---
= Atualizar um clone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar o clone executando o comando _Refresh-SmClone_.  Este comando cria um backup do banco de dados, exclui o clone existente e cria um clone com o mesmo nome.


NOTE: Não é possível atualizar um clone do PDB.

*O que você vai precisar*

* Crie um backup completo on-line ou uma política de backup de dados off-line sem backups agendados habilitados.
* Configure a notificação por e-mail na política somente para falhas de backup.
* Defina a contagem de retenção para os backups sob demanda adequadamente para garantir que não haja backups indesejados.
* Certifique-se de que somente um backup completo on-line ou uma política de backup de dados off-line esteja associada ao grupo de recursos identificado para a operação de atualização de clone.
* Crie um grupo de recursos com apenas um banco de dados.
* Se uma tarefa cron for criada para o comando clone refresh, certifique-se de que os agendamentos do SnapCenter e os agendamentos do cron não estejam sobrepostos para o grupo de recursos do banco de dados.
+
Para uma tarefa cron criada para o comando clone refresh, certifique-se de executar o Open-SmConnection a cada 24 horas.

* Certifique-se de que o SID do clone seja exclusivo para um host.
+
Se várias operações de atualização de clone usarem o mesmo arquivo de especificação de clone ou usarem o arquivo de especificação de clone com o mesmo SID de clone, o clone existente com o SID no host será excluído e então o clone será criado.

* Certifique-se de que a política de backup esteja habilitada com proteção secundária e que o arquivo de especificação do clone seja criado com "`-IncludeSecondaryDetails`" para criar os clones usando backups secundários.
+
** Se o arquivo de especificação do clone primário for especificado, mas a política tiver a opção de atualização secundária selecionada, o backup será criado e a atualização será transferida para o secundário.  No entanto, o clone será criado a partir do backup principal.
** Se o arquivo de especificação do clone primário for especificado e a política não tiver a opção de atualização secundária selecionada, o backup será criado no primário e o clone será criado a partir do primário.




*Passos*

. Iniciar uma sessão de conexão com o SnapCenter Server para um usuário especificado: _Open-SmConnection_
. Crie uma especificação de clone do banco de dados Oracle a partir de um backup especificado: _New-SmOracleCloneSpecification_
+

NOTE: Se a política de proteção de dados secundária for unified mirror-vault, especifique somente -IncludeSecondaryDetails.  Você não precisa especificar -SecondaryStorageType.

+
Este comando cria automaticamente um arquivo de especificação de clone do banco de dados Oracle para o banco de dados de origem especificado e seu backup.  Você também deve fornecer um SID de banco de dados clone para que o arquivo de especificação criado tenha os valores gerados automaticamente para o banco de dados clone que você criará.

+

NOTE: O arquivo de especificação do clone é criado em _/var/opt/snapcenter/sco/clone_specs_.

. Execute _Refresh-SmClone_.
+
Se a operação falhar com as mensagens de erro "PL-SCO-20032: a operação canExecute falhou com o erro: PL-SCO-30031: o arquivo de log de refazer +SC_2959770772_clmdb/clmdb/redolog/redo01_01.log existe", especifique um valor mais alto para _-WaitToTriggerClone_.

+
Para obter informações detalhadas sobre os comandos UNIX, consulte o https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["Guia de referência de comandos do software SnapCenter"^] .


