---
permalink: protect-sce/reference_granular_recovery_of_mails_and_mailbox.html 
sidebar: sidebar 
keywords: SMBR, Single Mailbox recovery, Exchange database 
summary: 'O software Single Mailbox Recovery (SMBR) permite que você restaure e recupere e-mails ou caixas de correio em vez do banco de dados completo do Exchange.' 
---
= Recuperação granular de e-mails e caixas de correio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O software Single Mailbox Recovery (SMBR) permite que você restaure e recupere e-mails ou caixas de correio em vez do banco de dados completo do Exchange.

Restaurar um banco de dados completo apenas para recuperar um único e-mail consumirá muito tempo e recursos.  O SMBR ajuda a recuperar rapidamente os e-mails criando uma cópia clone do Snapshot e, em seguida, usando APIs da Microsoft para montar a caixa de correio no SMBR.  Para obter informações sobre como usar o SMBR, consulte https://docs.netapp.com/p/snap/smbr/8.3/Administrative-Server-Administration-Guide.pdf["Guia de Administração do SMBR"^] .

Para obter informações adicionais sobre SMBR, consulte o seguinte:

* https://kb.netapp.com/Legacy/SMBR/How_to_manually_restore_a_single_item_with_SMBR["Como restaurar manualmente um único item com SMBR (também aplicável para restaurações do Ontrack Power Control)"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Single_Mailbox_Recovery_(SMBR)/How_to_restore_from_secondary_storage_in_SMBR_with_SnapCenter["Como restaurar do armazenamento secundário no SMBR com o SnapCenter"^]
* https://www.youtube.com/watch?v=wMSo049rREY&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg&index=3["Recuperando e-mails do Microsoft Exchange do SnapVault usando SMBR"^]

