---
permalink: protect-sce/task_reseed_a_replica_using_powershell_cmdlets_for_exchange_database.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: Você pode usar cmdlets do PowerShell para restaurar uma réplica não íntegra usando a cópia mais recente no mesmo host ou a cópia mais recente de um host alternativo. 
---
= Repropagar uma réplica usando cmdlets do PowerShell para banco de dados do Exchange
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar cmdlets do PowerShell para restaurar uma réplica não íntegra usando a cópia mais recente no mesmo host ou a cópia mais recente de um host alternativo.

As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _Get-Help command_name_. Alternativamente, você também pode consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência do cmdlet do software SnapCenter"^] .

.Passos
. Inicie uma sessão de conexão com o SnapCenter Server para um usuário especificado usando o `Open-SmConnection` cmdlet.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Resemelhe o banco de dados usando o `reseed-SmDagReplicaCopy` cmdlet.
+
Este exemplo repete a cópia com falha do banco de dados chamado execdb no host "mva-rx200.netapp.com" usando o backup mais recente naquele host.

+
[listing]
----
reseed-SmDagReplicaCopy -ReplicaHost "mva-rx200.netapp.com" -Database execdb
----
+
Este exemplo ressemeia a cópia com falha do banco de dados chamado execdb usando o backup mais recente do banco de dados (produção/cópia) em um host alternativo "mva-rx201.netapp.com".

+
[listing]
----
reseed-SmDagReplicaCopy -ReplicaHost "mva-rx200.netapp.com" -Database  execdb -BackupHost "mva-rx201.netapp.com"
----

