---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter .  Você deve criar credenciais para instalar o pacote de plug-in e credenciais adicionais para executar operações de proteção de dados em bancos de dados. 
---
= Configurar credenciais para o plug-in SnapCenter para Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter .  Você deve criar credenciais para instalar o pacote de plug-in e credenciais adicionais para executar operações de proteção de dados em bancos de dados.

.Sobre esta tarefa
Você deve configurar credenciais para instalar plug-ins em hosts Windows.  Embora você possa criar credenciais para o Windows após implantar hosts e instalar plug-ins, a prática recomendada é criar credenciais depois de adicionar SVMs, antes de implantar hosts e instalar plug-ins.

Configure as credenciais com privilégios de administrador, incluindo direitos de administrador no host remoto.

Se você configurar credenciais para grupos de recursos individuais e o nome de usuário não tiver privilégios de administrador completos, será necessário atribuir pelo menos os privilégios de grupo de recursos e backup ao nome de usuário.

.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Credencial*.
. Clique em *Novo*.
+
A janela Credencial é exibida.

. Na página Credencial, faça o seguinte:
+
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Digite um nome para a credencial.



 a| 
Nome de usuário
 a| 
Digite o nome de usuário usado para autenticação.

** Administrador de domínio ou qualquer membro do grupo de administradores
+
Especifique o administrador do domínio ou qualquer membro do grupo de administradores no sistema em que você está instalando o plug-in SnapCenter . Os formatos válidos para o campo Nome de usuário são:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Administrador local (somente para grupos de trabalho)
+
Para sistemas que pertencem a um grupo de trabalho, especifique o administrador local integrado no sistema em que você está instalando o plug-in SnapCenter . Você pode especificar uma conta de usuário local que pertença ao grupo de administradores locais se a conta de usuário tiver privilégios elevados ou se o recurso de Controle de Acesso do Usuário estiver desabilitado no sistema host.  O formato válido para o campo Nome de usuário é: `UserName`





 a| 
Senha
 a| 
Digite a senha usada para autenticação.



 a| 
Autenticação
 a| 
Selecione Windows como o modo de autenticação.

|===
. Clique em *OK*.

