---
permalink: protect-sce/task_configure_snapmanager_7_x_for_exchange_and_snapcenter_plug_in_for_exchange_to_coexist.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: Para permitir que o SnapCenter Plug-in para Microsoft Exchange Server coexista com o SnapManager para Microsoft Exchange Server, você precisa instalar o SnapCenter Plug-in para Microsoft Exchange Server no mesmo Exchange Server em que o SnapManager para Microsoft Exchange Server está instalado, desabilitar os agendamentos do SnapManager para Exchange e configurar novos agendamentos e backups usando o SnapCenter Plug-in para Microsoft Exchange Server. 
---
= Configurar o SnapManager 7.x para que o Exchange e o SnapCenter coexistam
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para permitir que o SnapCenter Plug-in para Microsoft Exchange Server coexista com o SnapManager para Microsoft Exchange Server, você precisa instalar o SnapCenter Plug-in para Microsoft Exchange Server no mesmo Exchange Server em que o SnapManager para Microsoft Exchange Server está instalado, desabilitar os agendamentos do SnapManager para Exchange e configurar novos agendamentos e backups usando o SnapCenter Plug-in para Microsoft Exchange Server.

.Antes de começar
* O SnapManager para Microsoft Exchange Server e o SnapDrive para Windows já estão instalados, e os backups do SnapManager para Microsoft Exchange Server existem no sistema e no diretório SnapInfo.
* Você deve ter excluído ou recuperado os backups feitos pelo SnapManager para Microsoft Exchange Server dos quais não precisa mais.
* Você deve ter suspendido ou excluído todos os agendamentos criados pelo SnapManager para Microsoft Exchange Server do agendador do Windows.
* O SnapCenter Plug-in para Microsoft Exchange Server e o SnapManager para Microsoft Exchange Server podem coexistir no mesmo Exchange Server, mas você não pode atualizar instalações existentes do SnapManager para Microsoft Exchange Server para o SnapCenter.
+
O SnapCenter não oferece uma opção para atualização.

* O SnapCenter não oferece suporte à restauração de bancos de dados do Exchange a partir do SnapManager para backup do Microsoft Exchange Server.
+
Se você não desinstalar o SnapManager para Microsoft Exchange Server após a instalação do SnapCenter Plug-in para Microsoft Exchange Server e depois quiser restaurar um backup do SnapManager para Microsoft Exchange Server, será necessário executar etapas adicionais.



.Passos
. Usando o PowerShell em todos os nós DAG, determine se o SnapDrive para Windows VSS Hardware Provider está registrado: _vssadmin list providers_
+
[listing]
----
C:\Program Files\NetApp\SnapDrive>vssadmin list providers
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Provider name: 'Data ONTAP VSS Hardware Provider'
   Provider type: Hardware
   Provider Id: {ddd3d232-a96f-4ac5-8f7b-250fd91fd102}
   Version: 7. 1. 4. 6845
----
. No diretório SnapDrive , cancele o registro do VSS Hardware Provider do SnapDrive para Windows: _navssprv.exe -r service –u_
. Verifique se o VSS Hardware Provider foi removido: _vssadmin list providers_
. Adicione o host do Exchange ao SnapCenter e instale o SnapCenter Plug-in para Microsoft Windows e o SnapCenter Plug-in para Microsoft Exchange Server.
. No diretório do plug-in SnapCenter para Microsoft Windows em todos os nós DAG, verifique se o provedor de hardware VSS está registrado: _vssadmin list providers_
+
[listing]
----
[PS] C:\Windows\system32>vssadmin list providers
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Provider name: 'Data ONTAP VSS Hardware Provider'
   Provider type: Hardware
   Provider Id: {31fca584-72be-45b6-9419-53a3277301d1}
   Version: 7. 0. 0. 5561
----
. Interrompa os agendamentos de backup do SnapManager para Microsoft Exchange Server.
. Usando a GUI do SnapCenter , crie backups sob demanda, configure backups agendados e defina configurações de retenção.
. Desinstale o SnapManager para Microsoft Exchange Server.
+
Se você não desinstalar o SnapManager para Microsoft Exchange Server agora e quiser restaurar um backup do SnapManager para Microsoft Exchange Server mais tarde:

+
.. Cancelar o registro do SnapCenter Plug-in para Microsoft Exchange Server de todos os nós DAG: _navssprv.exe -r service -u_
+
[listing]
----
C:\Program Files\NetApp\SnapCenter\SnapCenter Plug-in for Microsoft Windows>navssprv.exe -r service -u
----
.. No diretório _C:\Program Files\ NetApp\ SnapDrive\_, registre o SnapDrive para Windows em todos os nós DAG: _navssprv.exe -r service -a hostname\\username -p password_



