---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: Você pode criar uma política de backup para os recursos do Exchange ou para os grupos de recursos antes de usar o SnapCenter para fazer backup dos recursos do Microsoft Exchange Server ou pode criar uma política de backup no momento em que cria um grupo de recursos ou faz backup de um único recurso. 
---
= Criar políticas de backup para bancos de dados do Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar uma política de backup para os recursos do Exchange ou para os grupos de recursos antes de usar o SnapCenter para fazer backup dos recursos do Microsoft Exchange Server ou pode criar uma política de backup no momento em que cria um grupo de recursos ou faz backup de um único recurso.

.Antes de começar
* Você deve ter definido sua estratégia de proteção de dados.
+
Para obter detalhes, consulte as informações sobre como definir uma estratégia de proteção de dados para bancos de dados do Exchange.

* Você deve estar preparado para a proteção de dados concluindo tarefas como instalar o SnapCenter, adicionar hosts, identificar recursos e criar conexões de sistema de armazenamento.
* Você deve ter atualizado (descoberto) os recursos do Exchange Server.
* Se você estiver replicando Snapshots para um espelho ou cofre, o administrador do SnapCenter deverá ter atribuído as máquinas virtuais de armazenamento (SVMs) para os volumes de origem e de destino a você.
* Se você quiser executar os scripts do PowerShell em prescrições e postscripts, você deve definir o valor do `usePowershellProcessforScripts` parâmetro para verdadeiro no `web.config` arquivo.
+
O valor padrão é falso.

* Revise os pré-requisitos e limitações específicos da sincronização ativa do SnapMirror . Para obter informações, consulte https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Limites de objetos para sincronização ativa do SnapMirror"] .


.Sobre esta tarefa
* Uma política de backup é um conjunto de regras que rege como você gerencia e mantém backups e com que frequência o recurso ou grupo de recursos é feito backup.  Além disso, você pode especificar configurações de script.  Especificar opções em uma política economiza tempo quando você deseja reutilizar a política para outro grupo de recursos.
* A retenção de backup completo é específica para uma determinada política.  Um banco de dados ou recurso que usa a política A com uma retenção de backup completo de 4 retém 4 backups completos e não tem efeito na política B para o mesmo banco de dados ou recurso, que pode ter uma retenção de 3 para reter 3 backups completos.
* A retenção de backup de log é eficaz em todas as políticas e se aplica a todos os backups de log de um banco de dados ou recurso.  Portanto, quando um backup completo é executado usando a política B, a configuração de retenção de log afeta os backups de log criados pela política A no mesmo banco de dados ou recurso.  Da mesma forma, a configuração de retenção de log para a política A afeta os backups de log criados pela política B no mesmo banco de dados.
* O SCRIPTS_PATH é definido usando a chave PredefinedWindowsScriptsDirectory localizada no arquivo SMCoreServiceHost.exe.Config do host do plug-in.
+
Se necessário, você pode alterar esse caminho e reiniciar o serviço SMcore.  É recomendável que você use o caminho padrão por segurança.

+
O valor da chave pode ser exibido no swagger por meio da API: API /4.7/configsettings

+
Você pode usar a API GET para exibir o valor da chave.  A API SET não é suportada.

+
|===


| *Melhores práticas:* É melhor configurar a política de retenção secundária com base no número geral de backups completos e de log que você deseja manter.  Ao configurar políticas de retenção secundárias, lembre-se de que, quando os bancos de dados e logs estão em volumes diferentes, cada backup pode ter três Snapshots e, quando os bancos de dados e logs estão no mesmo volume, cada backup pode ter dois Snapshots. 
|===
* SnapLock
+
** Se a opção 'Manter as cópias de backup por um número específico de dias' for selecionada, o período de retenção do SnapLock deverá ser menor ou igual aos dias de retenção mencionados.
+
Especificar um período de bloqueio de Snapshot impede a exclusão dos Snapshots até que o período de retenção expire. Isso pode levar à retenção de um número maior de Snapshots do que a contagem especificada na política.

+
Para versões do ONTAP 9.12.1 e anteriores, os clones criados a partir dos SnapLock Vault Snapshots herdarão o tempo de expiração do SnapLock Vault. O administrador de armazenamento deve limpar manualmente os clones após o tempo de expiração do SnapLock .





.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Políticas*.
. Clique em *Novo*.
. Na página Nome, insira o nome e os detalhes da política.
. Na página Tipo de backup e replicação, execute as seguintes etapas:
+
.. Escolha o tipo de backup:
+
|===
| Se você quiser... | Faça isso... 


 a| 
Faça backup dos arquivos do banco de dados e dos logs de transações necessários
 a| 
Selecione *Backup completo e Backup de log*.

Os bancos de dados são copiados com truncamento de log, e todos os logs são copiados, incluindo os logs truncados.


NOTE: Este é o tipo de backup recomendado.



 a| 
Faça backup dos arquivos do banco de dados e dos logs de transações não confirmados
 a| 
Selecione *Backup completo*.

Os bancos de dados são copiados com truncamento de log, e logs truncados não são copiados.



 a| 
Faça backup de todos os logs de transações
 a| 
Selecione *Backup de log*.

Todos os logs de transações no sistema de arquivos ativo são copiados e não há truncamento de log.

Um diretório _scebackupinfo_ é criado no mesmo disco que o log ativo.  Este diretório contém o ponteiro para as alterações incrementais do banco de dados do Exchange e não é equivalente aos arquivos de log completos.



 a| 
Faça backup de todos os arquivos de banco de dados e logs de transações sem truncar os arquivos de log de transações
 a| 
Selecione *Copiar backup*.

Todos os bancos de dados e todos os logs são copiados e não há truncamento de logs.  Normalmente, você usa esse tipo de backup para repropagar uma réplica ou para testar ou diagnosticar um problema.

|===
+

NOTE: Você deve definir o espaço necessário para backups de log com base na retenção de backup completa e não com base na retenção atualizada (UTM).

+

NOTE: Crie políticas de cofre separadas para logs e bancos de dados ao lidar com volumes do Exchange (LUNs) e defina a retenção (keep) da política de log como o dobro do número para cada rótulo da política de banco de dados, usando os mesmos rótulos.  Para mais informações, veja, https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_for_Exchange_Backups_only_keep_half_the_Snapshots_on_the_Vault_destination_log_volume["Os backups do SnapCenter for Exchange mantêm apenas metade dos instantâneos no volume de log de destino do Vault"^]

.. Na seção Configurações do Grupo de Disponibilidade do Banco de Dados, selecione uma ação:
+
|===
| Para este campo... | Faça isso... 


 a| 
Fazer backup de cópias ativas
 a| 
Selecione esta opção para fazer backup somente das cópias ativas do banco de dados selecionado.

Para grupos de disponibilidade de banco de dados (DAGs), esta opção faz backup apenas de cópias ativas de todos os bancos de dados no DAG.

Cópias passivas não são feitas backup.



 a| 
Faça cópias de backup em servidores a serem selecionados no momento da criação do trabalho de backup
 a| 
Selecione esta opção para fazer backup de quaisquer cópias dos bancos de dados nos servidores selecionados, tanto ativos quanto passivos.

Para DAGs, esta opção faz backup de cópias ativas e passivas de todos os bancos de dados nos servidores selecionados.

|===
+

NOTE: Em configurações de cluster, os backups são retidos em cada nó do cluster de acordo com as configurações de retenção definidas na política.  Se o nó proprietário do cluster for alterado, os backups do nó proprietário anterior serão mantidos.  A retenção é aplicável somente no nível do nó.

.. Na seção Frequência da programação, selecione um ou mais tipos de frequência: *Sob demanda*, *Por hora*, *Diária*, *Semanal* e *Mensal*.
+

NOTE: Você pode especificar o agendamento (data de início, data de término) para operações de backup ao criar um grupo de recursos.  Isso permite que você crie grupos de recursos que compartilham a mesma política e frequência de backup, mas permite que você atribua agendamentos de backup diferentes a cada política.

+

NOTE: Se você agendou para 2h00, a programação não será acionada durante o horário de verão (DST).

.. Selecione o rótulo Política.
+

NOTE: Você pode atribuir rótulos SnapMirror a snapshots primários para replicação remota, permitindo que os snapshots primários descarreguem a operação de replicação de snapshots do SnapCenter para sistemas secundários ONTAP . Isso pode ser feito sem habilitar a opção SnapMirror ou SnapVault na página de política.

.. Na seção Selecionar opções de replicação secundária, selecione uma ou ambas as seguintes opções de replicação secundária:
+
|===
| Para este campo... | Faça isso... 


 a| 
Atualizar o SnapMirror após criar um Snapshot local
 a| 
Selecione esta opção para manter cópias espelhadas de conjuntos de backup em outro volume (SnapMirror).

Durante a replicação secundária, o tempo de expiração do SnapLock carrega o tempo de expiração do SnapLock primário.

Esta opção deve ser habilitada para sincronização ativa do SnapMirror .


IMPORTANT: A política somente primária não pode ser usada se a sincronização ativa do SnapMirror estiver configurada para volumes do Exchange ONTAP .  O SnapCenter não permite isso.  Você deve habilitar a opção "Espelho".

Clicar no botão *Atualizar* na página Topologia atualiza o tempo de expiração do SnapLock secundário e primário que são recuperados do ONTAP.

Ver link:../protect-sce/task_view_exchange_backups_in_the_topology_page.html["Exibir backups do Exchange na página Topologia"] .



 a| 
Atualizar o SnapVault após criar um Snapshot local
 a| 
Selecione esta opção para executar a replicação de backup de disco para disco.



 a| 
Contagem de novas tentativas de erro
 a| 
Insira o número de tentativas de replicação que devem ocorrer antes que o processo seja interrompido.

|===
+

NOTE: Você deve configurar a política de retenção do SnapMirror no ONTAP para o armazenamento secundário para evitar atingir o limite máximo de Snapshots no armazenamento secundário.



. Na página Retenção, configure as definições de retenção.
+
As opções exibidas dependem do tipo de backup e do tipo de frequência selecionados anteriormente.

+

NOTE: O valor máximo de retenção é 1018. Os backups falharão se a retenção for definida como um valor maior do que o suportado pela versão subjacente do ONTAP .

+

IMPORTANT: Você deve definir a contagem de retenção como 2 ou mais se planeja habilitar a replicação do SnapVault .  Se você definir a contagem de retenção como 1, a operação de retenção poderá falhar porque o primeiro Snapshot será o Snapshot de referência para o relacionamento SnapVault até que um Snapshot mais recente seja replicado para o destino.

+
.. Na seção Configurações de retenção de backups de log, selecione uma das seguintes opções:
+
|===
| Se você quiser... | Faça isso... 


 a| 
Manter apenas um número específico de backups de log
 a| 
Selecione *Número de backups completos para os quais os logs são retidos* e especifique o número de backups completos para os quais você deseja restauração atualizada.

A retenção atualizada (UTM) se aplica ao backup de log criado por meio de backup completo ou de log.  Por exemplo, se as configurações de retenção de UTM estiverem configuradas para reter backups de log dos últimos 5 backups completos, os backups de log dos últimos 5 backups completos serão retidos.

As pastas de log criadas como parte de backups completos e de log são excluídas automaticamente como parte do UTM.  Você não pode excluir as pastas de log manualmente.  Por exemplo, se a configuração de retenção de backup completo ou completo e de log for definida para 1 mês e a retenção UTM for definida para 10 dias, a pasta de log criada como parte desses backups será excluída conforme UTM.  Como resultado, apenas as pastas de log de 10 dias estarão lá e todos os outros backups serão marcados para restauração em um determinado momento.

Você pode definir o valor de retenção UTM como 0, se não quiser executar uma restauração atualizada.  Isso permitirá a operação de restauração em um determinado momento.

*Melhores práticas:* é melhor que a configuração seja igual à configuração de Total Snapshots (backups completos) na seção Configurações de retenção de backup completo.  Isso garante que os arquivos de log sejam mantidos para cada backup completo.



 a| 
Manter as cópias de segurança por um número específico de dias
 a| 
Selecione a opção *Manter backups de log para o último* e especifique o número de dias para manter as cópias de backup de log.

Os backups de log até o número de dias de backups completos são mantidos.



 a| 
Período de bloqueio de instantâneo
 a| 
Selecione *Período de bloqueio de cópia de instantâneo* e selecione dias, meses ou anos.

O período de retenção do SnapLock deve ser inferior a 100 anos.

|===
+
Se você selecionou *Backup de log* como o tipo de backup, os backups de log serão retidos como parte das configurações de retenção atualizadas para backups completos.

.. Na seção Configurações de retenção de backup completo, selecione uma das seguintes opções para backups sob demanda e, em seguida, selecione uma para backups completos:
+
|===
| Para este campo... | Faça isso... 


 a| 
Manter apenas um número específico de Snapshots
 a| 
Se você quiser especificar o número de backups completos a serem mantidos, selecione a opção *Total de cópias de instantâneos a serem mantidas* e especifique o número de instantâneos (backups completos) a serem mantidos.

Se o número de backups completos exceder o número especificado, os backups completos que excederem o número especificado serão excluídos, com as cópias mais antigas sendo excluídas primeiro.



 a| 
Manter backups completos por um número específico de dias
 a| 
Selecione a opção *Manter cópias de instantâneos por* e especifique o número de dias para manter os instantâneos (backups completos).



 a| 
Período de bloqueio do instantâneo primário
 a| 
Selecione *Período de bloqueio de cópia do instantâneo primário* e selecione dias, meses ou anos.

O período de retenção do SnapLock deve ser inferior a 100 anos.



 a| 
Período de bloqueio do instantâneo secundário
 a| 
Selecione *Período de bloqueio de cópia de instantâneo secundário* e selecione dias, meses ou anos.

|===
+
Se você tiver um banco de dados com apenas backups de log e nenhum backup completo em um host em uma configuração DAG, os backups de log serão mantidos das seguintes maneiras:

+
*** Por padrão, o SnapCenter encontra o backup completo mais antigo para esse banco de dados em todos os outros hosts no DAG e exclui todos os backups de log nesse host que foram feitos antes do backup completo.
*** Você pode substituir o comportamento de retenção padrão acima para um banco de dados em um host em um DAG com apenas backups de log adicionando a chave *MaxLogBackupOnlyCountWithoutFullBackup* no arquivo _C:\Program Files\ NetApp\ SnapCenter WebApp\web.config_.
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
No exemplo, o valor 10 significa que você mantém até 10 backups de log no host.





. Na página Script, insira o caminho e os argumentos do prescript ou postscript que devem ser executados antes ou depois da operação de backup, respectivamente.
+
** Os argumentos de backup prescritos incluem "`$Database`" e "`$ServerInstance`".
** Os argumentos de backup do Postscript incluem "`$Database`", "`$ServerInstance`", "`$BackupName`", "`$LogDirectory`" e "`$LogSnapshot`".
+
Você pode executar um script para atualizar traps SNMP, automatizar alertas, enviar logs e assim por diante.

+

NOTE: O caminho de prescrições ou pós-escritos não deve incluir unidades ou compartilhamentos.  O caminho deve ser relativo ao SCRIPTS_PATH.



. Revise o resumo e clique em *Concluir*.

