---
permalink: protect-scw/concept_snapcenter_plug_in_for_microsoft_windows_overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft Windows 
summary: O SnapCenter Plug-in para Microsoft Windows é um componente do lado do host do NetApp SnapCenter Software que permite o gerenciamento de proteção de dados com reconhecimento de aplicativo dos recursos do sistema de arquivos da Microsoft.  Além disso, ele fornece provisionamento de armazenamento, consistência de instantâneo e recuperação de espaço para sistemas de arquivos do Windows.  O plug-in para Windows automatiza as operações de backup, restauração e clonagem do sistema de arquivos no seu ambiente SnapCenter . 
---
= Visão geral do plug-in SnapCenter para Microsoft Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter Plug-in para Microsoft Windows é um componente do lado do host do NetApp SnapCenter Software que permite o gerenciamento de proteção de dados com reconhecimento de aplicativo dos recursos do sistema de arquivos da Microsoft.  Além disso, ele fornece provisionamento de armazenamento, consistência de instantâneo e recuperação de espaço para sistemas de arquivos do Windows.  O plug-in para Windows automatiza as operações de backup, restauração e clonagem do sistema de arquivos no seu ambiente SnapCenter .

Quando o plug-in para Windows estiver instalado, você poderá usar o SnapCenter com a tecnologia NetApp SnapMirror para criar cópias espelhadas de conjuntos de backup em outro volume e com a tecnologia NetApp SnapVault para executar a replicação de backup de disco para disco para arquivamento ou conformidade com padrões.

* Habilita a proteção de dados com reconhecimento de aplicativo para outros plug-ins que estão sendo executados em hosts Windows no seu ambiente SnapCenter
* Automatiza operações de backup, restauração e clonagem com reconhecimento de aplicativo para sistemas de arquivos Microsoft em seu ambiente SnapCenter
* Oferece suporte ao provisionamento de armazenamento, consistência de instantâneos e recuperação de espaço para hosts Windows



NOTE: O plug-in para Windows provisiona compartilhamentos SMB e sistemas de arquivos do Windows em LUNs físicos e RDM, mas não oferece suporte a operações de backup para sistemas de arquivos do Windows em compartilhamentos SMB.
