---
permalink: protect-scw/reference_installation_requirements_for_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: requirements 
summary: Você deve estar ciente de certos requisitos de instalação antes de instalar o Plug-in para Windows. 
---
= Requisitos de instalação do plug-in SnapCenter para Microsoft Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente de certos requisitos de instalação antes de instalar o Plug-in para Windows.

Antes de começar a usar o Plug-in para Windows, o administrador do SnapCenter deve instalar e configurar o SnapCenter Server e executar tarefas de pré-requisito.

* Você precisa ter privilégios de administrador do SnapCenter para instalar o Plug-in para Windows.
+
A função de administrador do SnapCenter deve ter privilégios de administrador.

* Você deve ter instalado e configurado o SnapCenter Server.
* Ao instalar um plug-in em um host Windows, se você especificar uma credencial que não esteja integrada ou se o usuário pertencer a um usuário de grupo de trabalho local, será necessário desabilitar o UAC no host.
* Você deve configurar o SnapMirror e o SnapVault se quiser replicação de backup.




== Requisitos de host para instalar o pacote de plug-ins SnapCenter para Windows

Antes de instalar o pacote de plug-ins do SnapCenter para Windows, você deve estar familiarizado com alguns requisitos básicos de espaço e dimensionamento do sistema host.

|===
| Item | Requisitos 


 a| 
Sistemas Operacionais
 a| 
Microsoft Windows

Para obter as informações mais recentes sobre as versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de Interoperabilidade da NetApp"^] .

Se você estiver em uma configuração de cluster do Windows, também deverá instalar e configurar o Gerenciamento Remoto do Windows (WinRM).



 a| 
RAM mínima para o plug-in SnapCenter no host
 a| 
1 GB



 a| 
Espaço mínimo de instalação e registro para o plug-in SnapCenter no host
 a| 
5 GB


NOTE: Você deve alocar espaço em disco suficiente e monitorar o consumo de armazenamento pela pasta de logs.  O espaço de log necessário varia dependendo do número de entidades a serem protegidas e da frequência das operações de proteção de dados.  Se não houver espaço em disco suficiente, os logs não serão criados para as operações executadas recentemente.



 a| 
Pacotes de software necessários
 a| 
* Pacote de hospedagem do ASP.NET Core Runtime 8.0.12 (e todos os patches 8.0.x subsequentes)
* PowerShell Core 7.4.2


Para obter as informações mais recentes sobre as versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de Interoperabilidade da NetApp"^] .

Para obter informações específicas sobre solução de problemas do .NET, consulte https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["A atualização ou instalação do SnapCenter falha em sistemas legados que não têm conectividade com a Internet."]

|===


== Configure suas credenciais para o Plug-in para Windows

O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter .  Você deve criar credenciais para instalar plug-ins do SnapCenter e credenciais adicionais para executar operações de proteção de dados em sistemas de arquivos do Windows.

*O que você vai precisar*

* Você deve configurar as credenciais do Windows antes de instalar plug-ins.
* Você deve configurar as credenciais com privilégios de administrador, incluindo direitos de administrador, no host remoto.
* Se você configurar credenciais para grupos de recursos individuais e o usuário não tiver privilégios de administrador completos, será necessário atribuir pelo menos os privilégios de grupo de recursos e backup ao usuário.


*Passos*

. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Credencial*.
. Clique em *Novo*.
. Na página Credencial, faça o seguinte:
+
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Digite um nome para as credenciais.



 a| 
Nome de usuário/Senha
 a| 
Digite o nome de usuário e a senha usados para autenticação.

** Administrador de domínio ou qualquer membro do grupo de administradores
+
Especifique o administrador do domínio ou qualquer membro do grupo de administradores no sistema em que você está instalando o plug-in SnapCenter . Os formatos válidos para o campo Nome de usuário são os seguintes:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`
*** `UserName@upn`


** Administrador local (somente para grupos de trabalho)
+
Para sistemas que pertencem a um grupo de trabalho, especifique o administrador local integrado no sistema em que você está instalando o plug-in SnapCenter . Você pode especificar uma conta de usuário local que pertença ao grupo de administradores locais se a conta de usuário tiver privilégios elevados ou se o recurso de Controle de Acesso do Usuário estiver desabilitado no sistema host.  O formato válido para o campo Nome de usuário é o seguinte: `UserName`

+
Não use aspas duplas (") ou acento grave (`) nas senhas.  Você não deve usar os símbolos de menor que (<) e exclamação (!) juntos em senhas.  Por exemplo, menor que <! 10, menor que 10 <!, acento grave `12.





 a| 
Senha
 a| 
Digite a senha usada para autenticação.

|===
. Clique em *OK*.
+
Depois de concluir a configuração das credenciais, talvez você queira atribuir a manutenção de credenciais a um usuário ou grupo de usuários na página Usuário e Acesso.





== Configurar o gMSA no Windows Server 2016 ou posterior

O Windows Server 2016 ou posterior permite que você crie uma Conta de Serviço Gerenciada de grupo (gMSA) que fornece gerenciamento automatizado de senhas de contas de serviço a partir de uma conta de domínio gerenciada.

.Antes de começar
* Você deve ter um controlador de domínio do Windows Server 2016 ou posterior.
* Você deve ter um host Windows Server 2016 ou posterior, que seja membro do domínio.


.Passos
. Crie uma chave raiz do KDS para gerar senhas exclusivas para cada objeto no seu gMSA.
. Para cada domínio, execute o seguinte comando no controlador de domínio do Windows: Add-KDSRootKey -EffectiveImmediately
. Crie e configure seu gMSA:
+
.. Crie uma conta de grupo de usuários no seguinte formato:
+
 domainName\accountName$
.. Adicione objetos de computador ao grupo.
.. Use o grupo de usuários que você acabou de criar para criar o gMSA.
+
Por exemplo,

+
 New-ADServiceAccount -name <ServiceAccountName> -DNSHostName <fqdn> -PrincipalsAllowedToRetrieveManagedPassword <group> -ServicePrincipalNames <SPN1,SPN2,…>
.. Correr `Get-ADServiceAccount` comando para verificar a conta de serviço.


. Configure o gMSA em seus hosts:
+
.. Habilite o módulo do Active Directory para Windows PowerShell no host onde você deseja usar a conta gMSA.
+
Para fazer isso, execute o seguinte comando no PowerShell:

+
[listing]
----
PS C:\> Get-WindowsFeature AD-Domain-Services

Display Name                           Name                Install State
------------                           ----                -------------
[ ] Active Directory Domain Services   AD-Domain-Services  Available


PS C:\> Install-WindowsFeature AD-DOMAIN-SERVICES

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Active Directory Domain Services, Active ...
WARNING: Windows automatic updating is not enabled. To ensure that your newly-installed role or feature is
automatically updated, turn on Windows Update.
----
.. Reinicie seu host.
.. Instale o gMSA no seu host executando o seguinte comando no prompt de comando do PowerShell: `Install-AdServiceAccount <gMSA>`
.. Verifique sua conta gMSA executando o seguinte comando: `Test-AdServiceAccount <gMSA>`


. Atribua privilégios administrativos ao gMSA configurado no host.
. Adicione o host do Windows especificando a conta gMSA configurada no SnapCenter Server.
+
O SnapCenter Server instalará os plug-ins selecionados no host e o gMSA especificado será usado como a conta de logon de serviço durante a instalação do plug-in.


