---
permalink: protect-scw/task_install_on_multiple_remote_hosts_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: Se você quiser instalar o SnapCenter Plug-in para Microsoft Windows em vários hosts ao mesmo tempo, poderá fazer isso usando o cmdlet Install-SmHostPackage do PowerShell. 
---
= Instalar o plug-in SnapCenter para Microsoft Windows em vários hosts remotos usando cmdlets do PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você deseja instalar o SnapCenter Plug-in para Microsoft Windows em vários hosts ao mesmo tempo, você pode fazer isso usando o `Install-SmHostPackage` Cmdlet do PowerShell.

Você deve ter efetuado login no SnapCenter como um usuário de domínio com direitos de administrador local em cada host no qual deseja instalar plug-ins.

.Passos
. Inicie o PowerShell.
. No host do SnapCenter Server, estabeleça uma sessão usando o `Open-SmConnection` cmdlet e insira suas credenciais.
. Adicione o host autônomo ou o cluster ao SnapCenter usando o `Add-SmHost` cmdlet e os parâmetros necessários.
+
As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _Get-Help command_name_. Alternativamente, você também pode consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência do cmdlet do software SnapCenter"^] .

. Instale o plug-in em vários hosts usando o `Install-SmHostPackage` cmdlet e os parâmetros necessários.
+
Você pode usar o `-skipprecheck` opção quando você instalou os plug-ins manualmente e não deseja validar se o host atende aos requisitos para instalar o plug-in.


