---
permalink: protect-scw/task_create_backup_policies_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup policy 
summary: Você pode criar uma nova política de backup para recursos antes de usar o SnapCenter para fazer backup de sistemas de arquivos do Windows ou pode criar uma nova política de backup no momento em que cria um grupo de recursos ou quando faz backup de um recurso. 
---
= Crie políticas de backup para sistemas de arquivos do Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar uma nova política de backup para recursos antes de usar o SnapCenter para fazer backup de sistemas de arquivos do Windows ou pode criar uma nova política de backup no momento em que cria um grupo de recursos ou quando faz backup de um recurso.

.Antes de começar
* Você deve ter definido sua estratégia de backup.link:task_define_a_backup_strategy_for_windows_file_systems.html["Saber mais"^]
* Você deve estar preparado para a proteção de dados.
+
Para se preparar para a proteção de dados, você deve concluir tarefas como instalar o SnapCenter, adicionar hosts, descobrir recursos e criar conexões de máquina virtual de armazenamento (SVM).

* Se você estiver replicando Snapshots para um espelho ou armazenamento secundário de cofre, o administrador do SnapCenter deverá ter atribuído as SVMs a você para os volumes de origem e destino.
* Se você quiser executar os scripts do PowerShell em prescripts e postscripts, defina o valor do parâmetro usePowershellProcessforScripts como true no arquivo web.config.
+
O valor padrão é falso

* Revise os pré-requisitos e limitações específicos da sincronização ativa do SnapMirror . Para obter informações, consulte https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Limites de objetos para sincronização ativa do SnapMirror"] .


.Sobre esta tarefa
* O SCRIPTS_PATH é definido usando a chave PredefinedWindowsScriptsDirectory localizada no arquivo SMCoreServiceHost.exe.Config do host do plug-in.
+
Se necessário, você pode alterar esse caminho e reiniciar o serviço SMcore.  É recomendável que você use o caminho padrão por segurança.

+
O valor da chave pode ser exibido no swagger por meio da API: API /4.7/configsettings

+
Você pode usar a API GET para exibir o valor da chave.  A API SET não é suportada.

* SnapLock
+
** Se a opção 'Manter as cópias de backup por um número específico de dias' for selecionada, o período de retenção do SnapLock deverá ser menor ou igual aos dias de retenção mencionados.
** Especificar um período de bloqueio de Snapshot impede a exclusão dos Snapshots até que o período de retenção expire. Isso pode levar à retenção de um número maior de Snapshots do que a contagem especificada na política.
** Para o ONTAP 9.12.1 e versões anteriores, os clones criados a partir dos SnapLock Vault Snapshots como parte da restauração herdarão o tempo de expiração do SnapLock Vault. O administrador de armazenamento deve limpar manualmente os clones após o tempo de expiração do SnapLock .




.Passos
. No painel de navegação esquerdo, selecione *Configurações*.
. Na página Configurações, selecione *Políticas*.
. Selecione *Novo*.
. Na página Nome, insira o nome e os detalhes da política.
. Na página Backup e Replicação, execute as seguintes tarefas:
+
.. Selecione uma configuração de backup.
+
|===
| Opção | Descrição 


 a| 
Backup consistente do sistema de arquivos
 a| 
Escolha esta opção se desejar que o SnapCenter desative a unidade de disco na qual o sistema de arquivos reside antes do início da operação de backup e, em seguida, retome a unidade de disco após o término da operação de backup.



 a| 
Backup consistente com falhas do sistema de arquivos
 a| 
Escolha esta opção se não quiser que o SnapCenter desative a unidade de disco na qual o sistema de arquivos reside.

|===
.. Selecione uma frequência de programação (também chamada de tipo de política).
+
A política especifica apenas a frequência de backup.  O cronograma de proteção específico para backup é definido no grupo de recursos.  Portanto, dois ou mais grupos de recursos podem compartilhar a mesma política e frequência de backup, mas ter agendamentos de backup diferentes.

+

NOTE: Se você agendou para 2h00, a programação não será acionada durante o horário de verão (DST).

.. Selecione um rótulo de política.
+
Dependendo do rótulo do Snapshot selecionado, o ONTAP aplica a política de retenção do Snapshot secundário que corresponde ao rótulo.

+

NOTE: Se você selecionou *Atualizar SnapMirror após criar uma cópia local do Snapshot*, você pode opcionalmente especificar o rótulo da política secundária.  No entanto, se você tiver selecionado *Atualizar SnapVault após criar uma cópia local do Snapshot*, deverá especificar o rótulo da política secundária.



. Na seção Selecionar opções de replicação secundária, selecione uma ou ambas as seguintes opções de replicação secundária:
+
|===
| Para este campo... | Faça isso... 


 a| 
Atualizar o SnapMirror após criar uma cópia local do Snapshot
 a| 
Selecione esta opção para criar cópias espelhadas de conjuntos de backup em outro volume (SnapMirror).

Esta opção deve ser habilitada para sincronização ativa do SnapSnapMirror.

Durante a replicação secundária, o tempo de expiração do SnapLock carrega o tempo de expiração do SnapLock primário.  Clicar no botão *Atualizar* na página Topologia atualiza o tempo de expiração do SnapLock secundário e primário que são recuperados do ONTAP.

Ver link:../protect-scw/task_view_related_backups_and_clones_in_the_topology_page.html["Veja backups e clones relacionados na página Topologia"] .



 a| 
Atualizar o SnapVault após criar uma cópia do Snapshot
 a| 
Selecione esta opção para executar a replicação de backup de disco para disco.

Durante a replicação secundária, o tempo de expiração do SnapLock carrega o tempo de expiração do SnapLock primário.  Clicar no botão Atualizar na página Topologia atualiza o tempo de expiração do SnapLock secundário e primário que são recuperados do ONTAP.

Quando o SnapLock é configurado somente no secundário do ONTAP conhecido como SnapLock Vault, clicar no botão Atualizar na página Topologia atualiza o período de bloqueio no secundário recuperado do ONTAP.

Para mais informações sobre o SnapLock Vault, consulte https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["Enviar cópias do Snapshot para o WORM em um destino de cofre"]



 a| 
Contagem de novas tentativas de erro
 a| 
Insira o número de tentativas de replicação que devem ocorrer antes que o processo seja interrompido.

|===
+

NOTE: Você deve configurar a política de retenção do SnapMirror no ONTAP para o armazenamento secundário para evitar atingir o limite máximo de Snapshots no armazenamento secundário.

. Na página Configurações de retenção, especifique as configurações de retenção para backups sob demanda e para cada frequência de agendamento selecionada.
+
|===
| Opção | Descrição 


 a| 
Total de cópias do Snapshot a serem mantidas
 a| 
Escolha esta opção se quiser especificar o número de Snapshots que o SnapCenter armazena antes de excluí-los automaticamente.



 a| 
Mantenha cópias do Snapshot para
 a| 
Escolha esta opção se quiser especificar o número de dias que o SnapCenter retém uma cópia de backup antes de excluí-la.



 a| 
Período de bloqueio de cópia de instantâneo
 a| 
Selecione Período de bloqueio do instantâneo e especifique a duração em dias, meses ou anos.

O período de retenção do SnapLock deve ser inferior a 100 anos.

|===
+

IMPORTANT: Você deve definir a contagem de retenção como 2 ou mais.  O valor mínimo para a contagem de retenção é 2.

+

NOTE: O valor máximo de retenção é 1018. Os backups falharão se a retenção for definida como um valor maior do que o suportado pela versão do ONTAP .

. Na página Script, insira o caminho do prescript ou postscript que você deseja que o SnapCenter Server execute antes ou depois da operação de backup, respectivamente, e um limite de tempo que o SnapCenter aguarda a execução do script antes de atingir o tempo limite.
+
Por exemplo, você pode executar um script para atualizar traps SNMP, automatizar alertas e enviar logs.

+

NOTE: O caminho de prescrições ou pós-escritos não deve incluir unidades ou compartilhamentos.  O caminho deve ser relativo ao SCRIPTS_PATH.

. Revise o resumo e clique em *Concluir*.

