---
permalink: protect-scw/task_define_a_backup_strategy_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup strategy 
summary: 'Definir uma estratégia de backup antes de criar seus backups fornece os backups necessários para restaurar ou clonar seus sistemas de arquivos com sucesso.  Seu contrato de nível de serviço (SLA), objetivo de tempo de recuperação (RTO) e objetivo de ponto de recuperação (RPO) determinam em grande parte sua estratégia de backup.' 
---
= Definir uma estratégia de backup para sistemas de arquivos do Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Definir uma estratégia de backup antes de criar seus backups fornece os backups necessários para restaurar ou clonar seus sistemas de arquivos com sucesso.  Seu contrato de nível de serviço (SLA), objetivo de tempo de recuperação (RTO) e objetivo de ponto de recuperação (RPO) determinam em grande parte sua estratégia de backup.

Um SLA define o nível de serviço esperado e aborda muitas questões relacionadas ao serviço, incluindo a disponibilidade e o desempenho do serviço.  RTO é o tempo em que um processo de negócios deve ser restaurado após uma interrupção no serviço.  O RPO define a estratégia para a idade dos arquivos que devem ser recuperados do armazenamento de backup para que as operações regulares sejam retomadas após uma falha.  SLA, RTO e RPO contribuem para a estratégia de proteção de dados.



== Agendamentos de backup para sistemas de arquivos do Windows

A frequência de backup é especificada nas políticas; um agendamento de backup é especificado na configuração do grupo de recursos.  O fator mais crítico na determinação da frequência ou programação de backup é a taxa de alteração do recurso e a importância dos dados.  Você pode fazer backup de um recurso muito utilizado a cada hora, enquanto pode fazer backup de um recurso raramente utilizado uma vez por dia.  Outros fatores incluem a importância do recurso para sua organização, seu Acordo de Nível de Serviço (SLA) e seu Objetivo de Ponto de Recuperação (RPO).

Um SLA define o nível de serviço esperado e aborda muitas questões relacionadas ao serviço, incluindo a disponibilidade e o desempenho do serviço.  Um RPO define a estratégia para a idade dos arquivos que devem ser recuperados do armazenamento de backup para que as operações regulares sejam retomadas após uma falha.  O SLA e o RPO contribuem para a estratégia de proteção de dados.

Mesmo para um recurso muito utilizado, não há necessidade de executar um backup completo mais de uma ou duas vezes por dia.

Os agendamentos de backup têm duas partes, conforme a seguir:

* Frequência de backup
+
A frequência de backup (com que frequência os backups devem ser realizados), chamada de _tipo de agendamento_ para alguns plug-ins, faz parte de uma configuração de política.  Por exemplo, você pode configurar a frequência de backup como horária, diária, semanal ou mensal, ou pode especificar *Nenhum*, o que torna a política somente sob demanda.  Você pode acessar as políticas clicando em *Configurações* > *Políticas*.

* Agendamentos de backup
+
Os agendamentos de backup (exatamente quando os backups devem ser executados) fazem parte de uma configuração de grupo de recursos.  Por exemplo, se você tiver um grupo de recursos com uma política configurada para backups semanais, poderá configurar o agendamento para fazer backup toda quinta-feira às 22h.  Você pode acessar as programações dos grupos de recursos clicando em *Recursos* > *Grupos de Recursos*.





== Número de backups necessários para sistemas de arquivos do Windows

Os fatores que determinam o número de backups necessários incluem o tamanho do sistema de arquivos do Windows, o número de volumes usados, a taxa de alteração do sistema de arquivos e seu Contrato de Nível de Serviço (SLA).



== Convenção de nomenclatura de backup para sistemas de arquivos do Windows

Os backups do sistema de arquivos do Windows usam a convenção de nomenclatura Snapshot padrão.  A convenção de nomenclatura de backup padrão adiciona um registro de data e hora aos nomes de instantâneos que ajuda a identificar quando as cópias foram criadas.

O Snapshot usa a seguinte convenção de nomenclatura padrão: resourcegroupname_hostname_timestamp

Você deve nomear seus grupos de recursos de backup logicamente, como no exemplo a seguir:

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
Neste exemplo, os elementos de sintaxe têm os seguintes significados:

* `dts1`é o nome do grupo de recursos.
* `mach1x88`é o nome do host.
* `03-12-2016_23.17.26`é a data e o carimbo de data/hora.


Ao criar um backup, você também pode adicionar uma tag descritiva para ajudar a identificar o backup.  Por outro lado, se você quiser usar uma convenção de nomenclatura de backup personalizada, precisará renomear o backup após a conclusão da operação de backup.



== Opções de retenção de backup

Você pode escolher o número de dias pelos quais deseja manter cópias de backup ou especificar o número de cópias de backup que deseja manter, até um máximo ONTAP de 255 cópias.  Por exemplo, sua organização pode exigir que você mantenha 10 dias de cópias de backup ou 130 cópias de backup.

Ao criar uma política, você pode especificar as opções de retenção para o tipo de backup e o tipo de agendamento.

Se você configurar a replicação do SnapMirror , a política de retenção será espelhada no volume de destino.

O SnapCenter exclui os backups retidos que têm rótulos de retenção que correspondem ao tipo de agendamento.  Se o tipo de agendamento foi alterado para o recurso ou grupo de recursos, os backups com o rótulo de tipo de agendamento antigo ainda poderão permanecer no sistema.


NOTE: Para retenção de cópias de backup a longo prazo, você deve usar o backup SnapVault .
