---
permalink: upgrade/task_configure_snapcenter_to_check_for_available_updates.html 
sidebar: sidebar 
keywords: configure, snapcenter server, updates, software updates 
summary: O SnapCenter se comunica periodicamente com o site de suporte da NetApp para notificá-lo sobre atualizações de software disponíveis.  Você também pode criar uma programação para especificar o intervalo em que deseja receber informações sobre atualizações disponíveis. 
---
= Configure o SnapCenter para verificar se há atualizações disponíveis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter se comunica periodicamente com o site de suporte da NetApp para notificá-lo sobre atualizações de software disponíveis.  Você também pode criar uma programação para especificar o intervalo em que deseja receber informações sobre atualizações disponíveis.

.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página *Configurações*, clique em *Software*.
+
A página Software disponível exibe os pacotes de plug-ins disponíveis, as versões disponíveis e seu status de instalação.

. Clique em *Verificar atualizações* para ver se há versões mais recentes de pacotes de plug-ins disponíveis.
. Clique em *Agendar atualizações* para criar uma programação para especificar o intervalo em que você deseja receber informações sobre atualizações disponíveis:
+
.. Selecione o intervalo em *Verificar atualizações*.
.. Selecione a credencial do SnapCenter Server Admin Windows e clique em *OK*.



