---
permalink: protect-hana/reference_prerequisites_for_using_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: Credentials,SnapCenter Plug-in for SAP HANA Database 
summary: Antes de usar o SnapCenter Plug-in para o banco de dados SAP HANA, o administrador do SnapCenter deve instalar e configurar o SnapCenter Server e executar as tarefas de pré-requisito. 
---
= Pré-requisitos para usar o plug-in SnapCenter para banco de dados SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar o SnapCenter Plug-in para o banco de dados SAP HANA, o administrador do SnapCenter deve instalar e configurar o SnapCenter Server e executar as tarefas de pré-requisito.

* Instalar e configurar o SnapCenter Server.
* Efetue login no SnapCenter Server.
* Configure o ambiente SnapCenter adicionando conexões do sistema de armazenamento e criando credenciais, se aplicável.
* Instale o Java 11 no seu host Linux ou Windows.
+
Você deve definir o caminho Java na variável de caminho ambiental da máquina host.

* Configure o SnapMirror e o SnapVault se desejar replicação de backup.
* Instale o cliente HDBSQL no host onde você instalará o plug-in para o banco de dados SAP HANA.
+
Configure as chaves de armazenamento do usuário para os nós do SAP HANA que você gerenciará por meio deste host.

* Para o banco de dados SAP HANA 2.0SPS05, se você estiver usando uma conta de usuário do banco de dados SAP HANA, certifique-se de ter as seguintes permissões para executar operações de backup, restauração e clonagem no SnapCenter Server:
+
** Administrador de backup
** Leitura do catálogo
** Administrador de backup de banco de dados
** Operador de recuperação de banco de dados



