---
permalink: protect-hana/task_add_hosts_and_install_plug_in_packages_on_remote_hosts_sap_hana.html 
sidebar: sidebar 
keywords: credentials 
summary: Você deve usar a página Adicionar Host do SnapCenter para adicionar hosts e, em seguida, instalar os pacotes de plug-ins.  Os plug-ins são instalados automaticamente nos hosts remotos.  Você pode adicionar um host e instalar pacotes de plug-in para um host individual ou para um cluster. 
---
= Adicionar hosts e instalar pacotes de plug-ins em hosts remotos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve usar a página Adicionar Host do SnapCenter para adicionar hosts e, em seguida, instalar os pacotes de plug-ins.  Os plug-ins são instalados automaticamente nos hosts remotos.  Você pode adicionar um host e instalar pacotes de plug-in para um host individual ou para um cluster.

.Antes de começar
* Se o sistema operacional do host do SnapCenter Server for o Windows 2019 e o sistema operacional do host do plug-in for o Windows 2022, você deverá executar o seguinte:
+
** Atualize para o Windows Server 2019 (versão do sistema operacional 17763.5936) ou posterior
** Atualize para o Windows Server 2022 (versão do sistema operacional 20348.2402) ou posterior


* Você deve ser um usuário atribuído a uma função que tenha permissões de instalação e desinstalação de plug-ins, como a função de administrador do SnapCenter .
* Ao instalar um plug-in em um host Windows, se você especificar uma credencial que não esteja integrada ou se o usuário pertencer a um usuário de grupo de trabalho local, será necessário desabilitar o UAC no host.
* Você deve garantir que o serviço de enfileiramento de mensagens esteja em execução.
* A documentação de administração contém informações sobre o gerenciamento de hosts.
* Se estiver usando uma conta de serviço gerenciada em grupo (gMSA), você deverá configurar a gMSA com privilégios administrativos.
+
link:../protect-hana/task_configure_gMSA_on_windows_server_2012_or_later.html["Configurar conta de serviço gerenciada de grupo no Windows Server 2016 ou posterior para SAP HANA"^]



.Sobre esta tarefa
* Não é possível adicionar um SnapCenter Server como um host de plug-in a outro SnapCenter Server.
* Para que a replicação do sistema SAP HANA descubra recursos nos sistemas primário e secundário, é recomendável adicionar os sistemas primário e secundário usando o usuário root ou sudo.


.Passos
. No painel de navegação esquerdo, clique em *Hosts*.
. Verifique se a aba *Hosts Gerenciados* está selecionada na parte superior.
. Clique em *Adicionar*.
. Na página Hosts, execute as seguintes ações:
+
|===
| Para este campo... | Faça isso... 


 a| 
Tipo de host
 a| 
Selecione o tipo de host:

** Windows
** Linux
+

NOTE: O plug-in para SAP HANA é instalado no host do cliente HDBSQL, e esse host pode estar em um sistema Windows ou Linux.





 a| 
Nome do host
 a| 
Digite o nome do host de comunicação.  Digite o nome de domínio totalmente qualificado (FQDN) ou o endereço IP do host.  O SnapCenter depende da configuração correta do DNS.  Portanto, a melhor prática é inserir o FQDN.

Você deve configurar o cliente HDBSQL e o HDBUserStore neste host.



 a| 
Credenciais
 a| 
Selecione o nome da credencial que você criou ou crie novas credenciais.  A credencial deve ter direitos administrativos no host remoto.  Para obter detalhes, consulte as informações sobre como criar credenciais.

Você pode visualizar detalhes sobre as credenciais posicionando o cursor sobre o nome da credencial fornecida.


NOTE: O modo de autenticação de credenciais é determinado pelo tipo de host especificado no assistente Adicionar Host.

|===
. Na seção Selecionar plug-ins para instalar, selecione os plug-ins a serem instalados.
. (Opcional) Clique em *Mais opções*.
+
|===
| Para este campo... | Faça isso... 


 a| 
Porta
 a| 
Mantenha o número da porta padrão ou especifique o número da porta.  O número da porta padrão é 8145.  Se o SnapCenter Server foi instalado em uma porta personalizada, esse número de porta será exibido como a porta padrão.


NOTE: Se você instalou manualmente os plug-ins e especificou uma porta personalizada, deverá especificar a mesma porta.  Caso contrário, a operação falhará.



 a| 
Caminho de instalação
 a| 
O plug-in para SAP HANA é instalado no host do cliente HDBSQL, e esse host pode estar em um sistema Windows ou Linux.

** Para o pacote de plug-ins SnapCenter para Windows, o caminho padrão é C:\Arquivos de Programas\ NetApp\ SnapCenter.  Opcionalmente, você pode personalizar o caminho.
** Para o pacote de plug-ins SnapCenter para Linux, o caminho padrão é /opt/ NetApp/snapcenter.  Opcionalmente, você pode personalizar o caminho.




 a| 
Ignorar verificações de pré-instalação
 a| 
Marque esta caixa de seleção se você já instalou os plug-ins manualmente e não deseja validar se o host atende aos requisitos para instalar o plug-in.



 a| 
Use a conta de serviço gerenciada em grupo (gMSA) para executar os serviços do plug-in
 a| 
Para o host Windows, marque esta caixa de seleção se desejar usar a Conta de Serviço Gerenciada em Grupo (gMSA) para executar os serviços do plug-in.


NOTE: Forneça o nome do gMSA no seguinte formato: domainName\accountName$.


NOTE: O gMSA será usado como uma conta de serviço de logon somente para o serviço SnapCenter Plug-in para Windows.

|===
. Clique em *Enviar*.
+
Se você não tiver marcado a caixa de seleção Ignorar pré-verificações, o host será validado para verificar se ele atende aos requisitos para a instalação do plug-in. O espaço em disco, a RAM, a versão do PowerShell, a versão do .NET, a localização (para plug-ins do Windows) e a versão do Java (para plug-ins do Linux) são validados em relação aos requisitos mínimos.  Se os requisitos mínimos não forem atendidos, mensagens de erro ou aviso apropriadas serão exibidas.

+
Se o erro estiver relacionado ao espaço em disco ou à RAM, você pode atualizar o arquivo web.config localizado em C:\Arquivos de Programas\ NetApp\ SnapCenter WebApp para modificar os valores padrão.  Se o erro estiver relacionado a outros parâmetros, você deverá corrigir o problema.

+

NOTE: Em uma configuração de HA, se você estiver atualizando o arquivo web.config, deverá atualizar o arquivo em ambos os nós.

. Se o tipo de host for Linux, verifique a impressão digital e clique em *Confirmar e Enviar*.
+
Em uma configuração de cluster, você deve verificar a impressão digital de cada um dos nós do cluster.

+

NOTE: A verificação de impressão digital é obrigatória mesmo que o mesmo host tenha sido adicionado anteriormente ao SnapCenter e a impressão digital tenha sido confirmada.

. Monitore o progresso da instalação.
+
Os arquivos de log específicos da instalação estão localizados em /custom_location/snapcenter/logs.


