---
permalink: protect-hana/task_prepare_multitenant_database_containers_for_data_protection.html 
sidebar: sidebar 
keywords: multitenant database containers 
summary: 'Para hosts SAP HANA registrados diretamente no SnapCenter, a instalação ou atualização do SnapCenter Plug-in para banco de dados SAP HANA acionará uma descoberta automática de recursos no host.  Após instalar ou atualizar o plug-in, para cada recurso de contêiner de banco de dados multilocatário \(MDC\) localizado no host do plug-in, outro recurso MDC será descoberto automaticamente com um formato GUID diferente e registrado no SnapCenter.  O novo recurso estará no estado “bloqueado”.' 
---
= Preparar contêineres de banco de dados multilocatário para proteção de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para hosts SAP HANA registrados diretamente no SnapCenter, a instalação ou atualização do SnapCenter Plug-in para banco de dados SAP HANA acionará uma descoberta automática de recursos no host.  Após instalar ou atualizar o plug-in, para cada recurso de contêiner de banco de dados multilocatário (MDC) localizado no host do plug-in, outro recurso MDC será descoberto automaticamente com um formato GUID diferente e registrado no SnapCenter.  O novo recurso estará no estado "`bloqueado`".

.Sobre esta tarefa
Por exemplo, no SnapCenter 4.2, se o recurso E90 MDC estava localizado no host do plug-in e registrado manualmente, após a atualização para o SnapCenter 4.3, outro recurso E90 MDC com um GUID diferente será descoberto e registrado no SnapCenter.


NOTE: Os backups associados ao recurso do SnapCenter 4.2 e versões anteriores devem ser mantidos até o término do período de retenção.  Após o término do período de retenção, você pode excluir o antigo recurso MDC e continuar a gerenciar o novo recurso MDC descoberto automaticamente.

`Old MDC resource`é o recurso MDC para um host de plug-in que foi adicionado manualmente no SnapCenter 4.2 ou versões anteriores.

Execute as seguintes etapas para começar a usar o novo recurso descoberto no SnapCenter 4.3 para operações de proteção de dados:

.Passos
. Na página Recursos, selecione o antigo recurso MDC com backups adicionados à versão anterior do SnapCenter e coloque-o no "`modo de manutenção`" na página Topologia.
+
Se o recurso fizer parte de um grupo de recursos, coloque o grupo de recursos no "`modo de manutenção`".

. Configure o novo recurso MDC descoberto após a atualização para o SnapCenter 4.3 selecionando o novo recurso na página Recursos.
+
"`Novo recurso MDC`" é o recurso MDC recém-descoberto que foi descoberto quando o SnapCenter Server e o host do plug-in foram atualizados para 4.3.  O novo recurso MDC pode ser identificado como um recurso com o mesmo SID que o antigo recurso MDC, para um determinado host, e com um ícone de cadeado vermelho ao lado dele na página Recursos.

. Proteja o novo recurso MDC descoberto após a atualização para o SnapCenter 4.3 selecionando políticas de proteção, agendamentos e configurações de notificação.
. Exclua os backups feitos no SnapCenter 4.2 ou versões anteriores com base nas configurações de retenção.
. Exclua o grupo de recursos da página Topologia.
. Exclua o antigo recurso MDC da página Recursos.
+
Por exemplo, se o período de retenção de Snapshots primários for de 7 dias e o período de retenção de Snapshots secundários for de 45 dias, após a conclusão dos 45 dias e após a exclusão de todos os backups, você deverá excluir o grupo de recursos e o antigo recurso MDC.



.Informações relacionadas
link:task_configure_hdb_user_store_key_and_hdbsql_os_user_for_the_sap_hana_database.html["Configurar a chave de armazenamento do usuário HDB e o usuário do sistema operacional HDBSQL para o banco de dados SAP HANA"]

link:task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Visualize backups e clones do banco de dados SAP HANA na página Topologia"]
