---
sidebar: sidebar 
permalink: sc-automation/task_get_started_with_the_rest_api.html 
keywords: REST API 
summary: Acessar a API fornece alguma perspectiva antes de você começar a usá-la com processos de fluxo de trabalho mais complexos em uma configuração ativa. 
---
= Comece a usar a API REST
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode começar rapidamente usando a API REST do SnapCenter .  Acessar a API fornece alguma perspectiva antes de você começar a usá-la com processos de fluxo de trabalho mais complexos em uma configuração ativa.



== Olá Mundo

Você pode executar um comando simples no seu sistema para começar a usar a API REST do SnapCenter e confirmar sua disponibilidade.

.Antes de começar
* Certifique-se de que o utilitário Curl esteja disponível no seu sistema.
* Endereço IP ou nome do host do SnapCenter Server
* Nome de usuário e senha para uma conta com autoridade para acessar a API REST do SnapCenter .



NOTE: Se suas credenciais incluírem caracteres especiais, você precisará formatá-las de uma forma que seja aceitável para o Curl com base no shell que você está usando.  Por exemplo, você pode inserir uma barra invertida antes de cada caractere especial ou quebrar todo o caractere `username:password` string entre aspas simples.

.Etapa
Na interface de linha de comando, execute o seguinte para recuperar as informações do plug-in:

`curl -X GET -u username:password -k "https://<ip_address>/api/hosts?fields=IncludePluginInfo"`

Exemplo:

`curl -X GET -u admin:password -k "'https://10.225.87.97/api/hosts?fields=IncludePluginInfo"`
