---
permalink: sc-automation/task_how to_access_rest_apis_using_the_swagger_api_web_page.html 
sidebar: sidebar 
keywords: REST API, Swagger 
summary: As APIs REST são expostas por meio da página da web do Swagger.  Você pode acessar a página da web do Swagger para exibir as APIs REST do SnapCenter Server, bem como emitir manualmente uma chamada de API.  Você pode usar APIs REST para ajudar a gerenciar seu SnapCenter Server ou para executar operações de proteção de dados. 
---
= Como acessar APIs REST usando a página da web da API do Swagger
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As APIs REST são expostas por meio da página da web do Swagger.  Você pode acessar a página da web do Swagger para exibir as APIs REST do SnapCenter Server, bem como emitir manualmente uma chamada de API.  Você pode usar APIs REST para ajudar a gerenciar seu SnapCenter Server ou para executar operações de proteção de dados.

Você deve saber o endereço IP de gerenciamento ou o nome de domínio do SnapCenter Server no qual deseja executar as APIs REST.

Você não precisa de permissões especiais para executar o cliente da API REST.  Qualquer usuário pode acessar a página web do Swagger.  As respectivas permissões nos objetos acessados via API REST são baseadas no usuário que gera o token para efetuar login na API REST.

.Passos
. Em um navegador, insira o URL para acessar a página da web do Swagger no formato _\https://<endereço_IP_ou_nome_do_SnapCenter>:<porta_do_SnapCenter>/swagger/_.
+

NOTE: Certifique-se de que a URL da API REST não tenha os seguintes caracteres: +, ., % e &.

. No campo *Swagger Explore*, se a documentação da API do Swagger não for exibida automaticamente, digite: _\https://<SnapCenter_IP_address_or_name>:<SnapCenter_port>/Content/swagger/ SnapCenter.yaml_
. Clique em *Explorar*.
+
Uma lista de tipos ou categorias de recursos de API é exibida.

. Clique em um tipo de recurso de API para exibir as APIs nesse tipo de recurso.


Se você encontrar um comportamento inesperado ao executar as APIs REST do SnapCenter , poderá usar os arquivos de log para identificar a causa e resolver o problema.  Você pode baixar os arquivos de log da interface do usuário do SnapCenter clicando em *Monitor* > *Logs* > *Download*.
