---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: Crie a credencial do Azure no SnapCenter para acessar a conta do Azure NetApp . 
---
= Crie a credencial do Azure no SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve criar a credencial do Azure no SnapCenter para acessar a conta do Azure NetApp .

.Antes de começar
* Certifique-se de ter criado a entidade de serviço no Azure.
* Certifique-se de ter o ID do locatário, o ID do cliente e a chave secreta associados à entidade de serviço disponíveis.
+
** O ID do locatário pode ser encontrado no Portal do Azure, na página Visão geral do ID de entrada.
** O ID do cliente também é conhecido como ID do aplicativo para o aplicativo/serviço principal corporativo.  Isso pode ser encontrado no Portal do Azure, na página Visão geral do aplicativo empresarial que você criou para atuar como a entidade de serviço do SnapCenter.
** A Chave Secreta do Cliente também é conhecida como Valor Secreto.  Você pode criar esse segredo do cliente no Portal do Azure navegando até *Registros de aplicativo* em ID de entrada.  Depois de selecionar o aplicativo corporativo que você criou, navegue até *Certificados e segredos* e depois *Novo segredo do cliente*.
+

NOTE: O valor secreto só pode ser acessado quando criado.  Você não poderá acessá-lo mais tarde.

** O Principal de Serviço precisa receber permissões.  A função de Colaborador permitirá que a entidade de serviço execute as ações necessárias no Azure.  Isso pode ser concedido na página Controle de Acesso (IAM) na página Assinatura.




.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Credencial*.
. Clique em *Novo*.
. Na página Credencial, especifique as seguintes informações necessárias para criar a credencial.
+
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Digite um nome para a credencial.



 a| 
Modo de autenticação
 a| 
Selecione *Credencial do Azure* na lista suspensa.



 a| 
ID do inquilino
 a| 
Digite o ID do inquilino.



 a| 
ID do cliente
 a| 
Digite o ID do cliente.



 a| 
Chave secreta do cliente
 a| 
Digite a chave secreta do cliente.

|===
. Clique em *OK*.

