---
permalink: protect-azure/create-backup-policies-oracle.html 
sidebar: sidebar 
keywords: create policies, Oracle, backup policies 
summary: Crie uma política de backup para o recurso ou grupo de recursos do qual você deseja fazer backup. 
---
= Crie políticas de backup para bancos de dados Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar o SnapCenter para fazer backup de recursos do banco de dados Oracle, você deve criar uma política de backup para o recurso ou grupo de recursos do qual deseja fazer backup.

.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Políticas*.
. Selecione Oracle Database na lista suspensa.
. Clique em *Novo*.
. Na página Nome, insira o nome e a descrição da política.
. Na página Tipo de política, execute as seguintes etapas:
+
.. Selecione * Azure NetApp Files* como o tipo de armazenamento.
.. Selecione o tipo de backup como backup online ou offline.
.. Se você quiser catalogar o backup usando o Oracle Recovery Manager (RMAN), selecione *Catalogar backup com o Oracle Recovery Manager (RMAN)*.
.. Se você quiser remover logs de arquivo após o backup, selecione *Remover logs de arquivo após o backup*.
.. Especifique as configurações de log de arquivo de exclusão.


. Na página Snapshot e backup, execute as seguintes etapas:
+
.. Selecione a frequência do backup agendado.
.. Especifique as configurações de retenção.
.. Se você quiser habilitar o backup do Azure NetApp Files , selecione *Habilitar backup* e especifique as configurações de retenção.


. Na página Script, insira o caminho e os argumentos do prescript ou postscript que você deseja executar antes ou depois da operação de backup, respectivamente.
. Na página Verificação, selecione o agendamento de backup para o qual você deseja executar a operação de verificação e insira o caminho e os argumentos do prescript ou postscript que você deseja executar antes ou depois da operação de verificação, respectivamente.
. Revise o resumo e clique em *Concluir*.

