---
permalink: protect-azure/create-credential-add-plugin-host.html 
sidebar: sidebar 
keywords: snapcenter, azure, credential, plug-in host 
summary: Crie a credencial para adicionar o host do plug-in. 
---
= Crie a credencial para adicionar o host do plug-in
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter .

Você deve criar credenciais para instalar plug-ins do SnapCenter e credenciais adicionais para executar operações de proteção de dados.

.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Credencial*.
. Clique em *Novo*.
. Na página Credencial, especifique as seguintes informações necessárias para criar a credencial.
+
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Digite um nome para a credencial.



 a| 
Modo de autenticação
 a| 
Selecione o modo de autenticação na lista suspensa.



 a| 
Tipo de autenticação
 a| 
Selecione *Baseado em senha* ou *Baseado em chave SSH* (somente para host Linux).



 a| 
Nome de usuário
 a| 
Especifique o nome de usuário.



 a| 
Senha
 a| 
Se você selecionou Autenticação baseada em senha, especifique a senha.



 a| 
Chave privada SSH
 a| 
Se você selecionou a autenticação baseada em chave SSH, especifique a chave privada.



 a| 
Use privilégios sudo
 a| 
Marque a caixa de seleção Usar privilégios sudo se estiver criando credenciais para um usuário não root.


NOTE: Isso é aplicável somente para usuários do Linux.

|===
. Clique em *OK*.

