---
permalink: admin/task_manage_resource_groups.html 
sidebar: sidebar 
keywords: Manage resource groups 
summary: Você pode executar várias operações em grupos de recursos. 
---
= Gerenciar grupos de recursos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar várias operações em grupos de recursos.

Você pode executar as seguintes tarefas relacionadas a grupos de recursos:

* Modifique um grupo de recursos selecionando-o e clicando em *Modificar grupo de recursos* para editar as informações fornecidas ao criar o grupo de recursos.
+

NOTE: Você pode alterar o cronograma enquanto modifica o grupo de recursos.  Entretanto, para alterar o tipo de programação, você deve modificar a política.

+

NOTE: Se você remover recursos de um grupo de recursos, as configurações de retenção de backup definidas nas políticas atualmente anexadas ao grupo de recursos continuarão a ser aplicadas aos recursos removidos.

* Crie um backup de um grupo de recursos.
* Crie um clone de um backup.
+
Você pode clonar backups existentes de SQL, Oracle, sistemas de arquivos Windows, aplicativos personalizados e recursos ou grupos de recursos de banco de dados SAP HANA.

* Crie um clone de um grupo de recursos.
+
Esta operação é suportada somente para grupos de recursos SQL (que contêm somente bancos de dados).  Você pode configurar um cronograma para clonar um grupo de recursos (ciclo de vida do clone).

* Impedir que operações agendadas em grupos de recursos sejam iniciadas.
* Excluir um grupo de recursos.




== Parar e retomar operações em grupos de recursos

Você pode desabilitar temporariamente o início de operações agendadas em um grupo de recursos.  Mais tarde, quando quiser, você pode habilitar essas operações.

*Passos*

. No painel de navegação esquerdo, clique em *Recursos* e selecione o plug-in apropriado na lista.
. Na página Recursos, selecione *Grupo de recursos* na lista *Exibir*.
. Selecione o grupo de recursos e clique em *Manutenção*.
. Clique em *OK*.


Se você quiser retomar as operações no grupo de recursos que colocou no modo de manutenção, selecione o grupo de recursos e clique em *Produção*.



== Excluir grupos de recursos

Você pode excluir um grupo de recursos se não precisar mais proteger os recursos nele contidos.  Você deve garantir que os grupos de recursos sejam excluídos antes de remover plug-ins do SnapCenter.

*Sobre esta tarefa*

Você deve excluir manualmente todos os clones criados para qualquer um dos recursos no grupo de recursos.  Opcionalmente, você pode forçar a exclusão de todos os backups, metadados, políticas e instantâneos associados ao grupo de recursos.

*Passos*

. No painel de navegação esquerdo, clique em *Recursos* e selecione o plug-in apropriado na lista.
. Na página Recursos, selecione *Grupo de recursos* na lista *Exibir*.
. Selecione o grupo de recursos e clique em *Excluir*.
. Opcional: marque a caixa de seleção *Excluir backups e desanexar políticas associadas a este grupo de recursos* para remover todos os backups, metadados, políticas e instantâneos associados ao grupo de recursos.
. Clique em *OK*.

