---
permalink: admin/task_request_status_reports_of_the_jobs_from_the_dashboard.html 
sidebar: sidebar 
keywords: dashboard, snapcenter 
summary: Você pode solicitar relatórios sobre tarefas de backup, restauração e clonagem na página Painel.  Isso é útil se você quiser identificar o número total de trabalhos bem-sucedidos ou com falha no seu ambiente SnapCenter . 
---
= Solicitar relatórios de status dos trabalhos no painel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode solicitar relatórios sobre tarefas de backup, restauração e clonagem na página Painel.  Isso é útil se você quiser identificar o número total de trabalhos bem-sucedidos ou com falha no seu ambiente SnapCenter .

*Passos*

. No painel de navegação esquerdo, clique em *Painel*
. Localize o bloco Tarefas no Painel e selecione *Backup*, *Restaurar* ou *Clonar*.
. Usando o menu suspenso, selecione o período para o qual deseja informações sobre os trabalhos: 24 horas, 7 dias ou 30 dias.
+
Os sistemas exibem um gráfico de rosca cobrindo os dados.

. Clique na fatia de rosca que representa as informações do trabalho para o qual você deseja um relatório.
+
Ao clicar no gráfico de rosca, você será redirecionado da página Painel para a página Monitor.  A página Monitor exibe os trabalhos com o status selecionado no gráfico de rosca.

. Na lista da página Monitor, clique em um trabalho específico para selecioná-lo.
. Na parte superior da página Monitor, clique em *Relatórios*.


*Resultado*

O relatório exibe informações somente para o trabalho selecionado.  Você pode revisar o relatório ou baixá-lo para seu sistema local.
