---
permalink: protect-postgresql/set-up-credentials-for-snapcenter-plug-in-for-postgresql.html 
sidebar: sidebar 
keywords: credentials, SnapCenter Plug-in for postgresql 
summary: O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter .  Você deve criar credenciais para instalar plug-ins do SnapCenter e credenciais adicionais para executar operações de proteção de dados em clusters ou sistemas de arquivos do Windows. 
---
= Configurar credenciais para o plug-in SnapCenter para PostgreSQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter usa credenciais para autenticar usuários para operações do SnapCenter .  Você deve criar credenciais para instalar plug-ins do SnapCenter e credenciais adicionais para executar operações de proteção de dados em clusters ou sistemas de arquivos do Windows.

.Sobre esta tarefa
* Hosts Linux
+
Você deve configurar credenciais para instalar plug-ins em hosts Linux.

+
Você deve configurar as credenciais para o usuário root ou para um usuário não root que tenha privilégios sudo para instalar e iniciar o processo do plug-in.

+
|===


| *Melhores práticas:* embora você tenha permissão para criar credenciais para o Linux após implantar hosts e instalar plug-ins, a melhor prática é criar credenciais depois de adicionar SVMs, antes de implantar hosts e instalar plug-ins. 
|===
* Hosts do Windows
+
Você deve configurar as credenciais do Windows antes de instalar plug-ins.

+
Você deve configurar as credenciais com privilégios de administrador, incluindo direitos de administrador no host remoto.



Se você configurar credenciais para grupos de recursos individuais e o nome de usuário não tiver privilégios de administrador completos, será necessário atribuir pelo menos os privilégios de grupo de recursos e backup ao nome de usuário.

.Passos
. No painel de navegação esquerdo, clique em *Configurações*.
. Na página Configurações, clique em *Credencial*.
. Clique em *Novo*.
. Na página Credencial, especifique as informações necessárias para configurar as credenciais:
+
|===
| Para este campo... | Faça isso... 


 a| 
Nome da credencial
 a| 
Digite um nome para as credenciais.



 a| 
Nome de usuário
 a| 
Digite o nome de usuário e a senha que serão usados para autenticação.

** Administrador de domínio ou qualquer membro do grupo de administradores
+
Especifique o administrador do domínio ou qualquer membro do grupo de administradores no sistema em que você está instalando o plug-in SnapCenter . Os formatos válidos para o campo Nome de usuário são:

+
*** _NetBIOS\Nome do Usuário_
*** _FQDN do domínio\Nome do usuário_


** Administrador local (somente para grupos de trabalho)
+
Para sistemas que pertencem a um grupo de trabalho, especifique o administrador local integrado no sistema em que você está instalando o plug-in SnapCenter . Você pode especificar uma conta de usuário local que pertença ao grupo de administradores locais se a conta de usuário tiver privilégios elevados ou se o recurso de Controle de Acesso do Usuário estiver desabilitado no sistema host.  O formato válido para o campo Nome de usuário é: _UserName_

+
Não use aspas duplas (") ou acento grave (`) nas senhas.  Você não deve usar os símbolos de menor que (<) e exclamação (!) juntos em senhas.  Por exemplo, menor que <! 10, menor que 10 <!, acento grave `12.





 a| 
Senha
 a| 
Digite a senha usada para autenticação.



 a| 
Modo de autenticação
 a| 
Selecione o modo de autenticação que você deseja usar.



 a| 
Use privilégios sudo
 a| 
Marque a caixa de seleção *Usar privilégios sudo* se estiver criando credenciais para um usuário não root.


NOTE: Aplicável somente a usuários do Linux.

|===
. Clique em *OK*.


Depois de concluir a configuração das credenciais, talvez você queira atribuir a manutenção de credenciais a um usuário ou grupo de usuários na página Usuário e Acesso.
