---
permalink: protect-postgresql/snapcenter-plug-in-for-postgresql-overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for PostgreSQL 
summary: O SnapCenter Plug-in para PostgreSQL é um componente do lado do host do SnapCenter software NetApp SnapCenter que permite o gerenciamento de proteção de dados com reconhecimento de aplicativo de clusters PostgreSQL.  O plug-in para cluster PostgreSQL automatiza o backup, a restauração e a clonagem de clusters PostgreSQL no seu ambiente SnapCenter . 
---
= Visão geral do plug-in SnapCenter para PostgreSQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O plug-in SnapCenter para cluster PostgreSQL é um componente do lado do host do software NetApp SnapCenter software que permite o gerenciamento de proteção de dados com reconhecimento de aplicativo de clusters PostgreSQL.  O plug-in para cluster PostgreSQL automatiza o backup, a restauração e a clonagem de clusters PostgreSQL no seu ambiente SnapCenter .

O SnapCenter oferece suporte a configurações de cluster único e multicluster do PostgreSQL.  Você pode usar o Plug-in para Clusters PostgreSQL em ambientes Linux e Windows.  Em ambientes Windows, o PostgreSQL será suportado como recurso manual.

Quando o cluster Plug-in para PostgreSQL estiver instalado, você poderá usar o SnapCenter com a tecnologia NetApp SnapMirror para criar cópias espelhadas de conjuntos de backup em outro volume.  Você também pode usar o plug-in com a tecnologia NetApp SnapVault para executar a replicação de backup de disco para disco para conformidade com os padrões.

O plug-in SnapCenter para PostgreSQL oferece suporte a NFS e SAN em layouts de armazenamento de arquivos ONTAP e Azure NetApp .

O layout de armazenamento virtual VMDK, vVol e RDM é suportado.
