---
permalink: install/concept_svm_connections_and_credentials.html 
sidebar: sidebar 
keywords: storage, connection, credentials 
summary: Antes de executar operações de proteção de dados, você deve configurar as conexões de armazenamento e adicionar as credenciais que o SnapCenter Server e os plug-ins do SnapCenter usarão. 
---
= Conexões e credenciais de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de executar operações de proteção de dados, você deve configurar as conexões de armazenamento e adicionar as credenciais que o SnapCenter Server e os plug-ins do SnapCenter usarão.



== Conexões de armazenamento

As conexões de armazenamento dão ao SnapCenter Server e aos plug-ins do SnapCenter acesso ao armazenamento ONTAP .  A configuração dessas conexões também envolve a configuração dos recursos do AutoSupport e do Sistema de Gerenciamento de Eventos (EMS).



== Credenciais

* Administrador de domínio ou qualquer membro do grupo de administradores
+
Especifique o administrador do domínio ou qualquer membro do grupo de administradores no sistema em que você está instalando o plug-in SnapCenter . Os formatos válidos para o campo Nome de usuário são:

+
** _NetBIOS\Nome do Usuário_
** _FQDN do domínio\Nome do usuário_
** _Nome de usuário@upn_


* Administrador local (somente para grupos de trabalho)
+
Para sistemas que pertencem a um grupo de trabalho, especifique o administrador local integrado no sistema em que você está instalando o plug-in SnapCenter . Você pode especificar uma conta de usuário local que pertença ao grupo de administradores locais se a conta de usuário tiver privilégios elevados ou se o recurso de Controle de Acesso do Usuário estiver desabilitado no sistema host.

+
O formato válido para o campo Nome de usuário é: _UserName_

* Credenciais para grupos de recursos individuais
+
Se você configurar credenciais para grupos de recursos individuais e o nome de usuário não tiver privilégios de administrador completos, será necessário atribuir pelo menos os privilégios de grupo de recursos e backup ao nome de usuário.


