---
permalink: install/configure_mfa_using_powershell_sccli_restapi.html 
sidebar: sidebar 
keywords: mfa, authentication, multifactor authentication 
summary: Você pode usar as interfaces Rest API, PowerShell e SCCLI para configurar o MFA. 
---
= Configurar MFA no SnapCenter Server usando PowerShell, SCCLI e REST API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar o MFA no SnapCenter Server usando PowerShell, SCCLI e REST API.



== Autenticação SnapCenter MFA CLI

No PowerShell e no SCCLI, o cmdlet existente (Open-SmConnection) é estendido com mais um campo chamado "AccessToken" para usar o token do portador para autenticar o usuário.

`Open-SmConnection -Credential <PSCredential> [-SMSbaseUrl <String>] [-Port <String>] [-RoleName <String>] [ -AccessToken <string>]`

Após a execução do cmdlet acima, uma sessão é criada para o respectivo usuário executar outros cmdlets do SnapCenter .



== Autenticação SnapCenter MFA Rest API

Use o token portador no formato _Authorization=Bearer <access token>_ no cliente REST API (como Postman ou swagger) e mencione o RoleName do usuário no cabeçalho para obter uma resposta bem-sucedida do SnapCenter.



== Fluxo de trabalho da API REST do MFA

Quando o MFA é configurado com o AD FS, você deve autenticar usando um token de acesso (portador) para acessar o aplicativo SnapCenter por qualquer API Rest.

*Sobre esta tarefa*

* Você pode usar qualquer cliente REST, como Postman, Swagger UI ou FireCamp.
* Obtenha um token de acesso e use-o para autenticar solicitações subsequentes (SnapCenter Rest API) para executar qualquer operação.


*Passos*

*Para autenticar através do AD FS MFA*

. Configure o cliente REST para chamar o ponto de extremidade do AD FS para obter o token de acesso.
+
Ao clicar no botão para obter um token de acesso para um aplicativo, você será redirecionado para a página SSO do AD FS, onde deverá fornecer suas credenciais do AD e autenticar com o MFA. 1.  Na página SSO do AD FS, digite seu nome de usuário ou e-mail na caixa de texto Nome de usuário.

+
+ Os nomes de usuário devem ser formatados como usuário@domínio ou domínio\usuário.

. Na caixa de texto Senha, digite sua senha.
. Clique em *Entrar*.
. Na seção *Opções de login*, selecione uma opção de autenticação e autentique (dependendo da sua configuração).
+
** Push: aprove a notificação push que é enviada para seu telefone.
** Código QR: Use o aplicativo móvel AUTH Point para escanear o código QR e digite o código de verificação mostrado no aplicativo
** Senha de uso único: digite a senha de uso único para seu token.


. Após a autenticação bem-sucedida, um pop-up será aberto contendo o acesso, o ID e o token de atualização.
+
Copie o token de acesso e use-o na API Rest do SnapCenter para executar a operação.

. Na API Rest, você deve passar o token de acesso e o nome da função na seção de cabeçalho.
. O SnapCenter valida esse token de acesso do AD FS.
+
Se for um token válido, o SnapCenter o decodifica e obtém o nome de usuário.

. Usando o nome de usuário e o nome da função, o SnapCenter autentica o usuário para uma execução de API.
+
Se a autenticação for bem-sucedida, o SnapCenter retornará o resultado, caso contrário, uma mensagem de erro será exibida.





== Habilitar ou desabilitar a funcionalidade SnapCenter MFA para REST API, CLI e GUI

*GUI*

*Passos*

. Efetue login no SnapCenter Server como Administrador do SnapCenter .
. Clique em *Configurações* > *Configurações globais* > *Configurações de autenticação multifator (MFA)*
. Selecione a interface (GUI/RST API/CLI) para habilitar ou desabilitar o login MFA.


*Interface do PowerShell*

*Passos*

. Execute os comandos do PowerShell ou da CLI para habilitar o MFA para GUI, REST API, PowerShell e SCCLI.
+
`Set-SmMultiFactorAuthentication -IsGuiMFAEnabled -IsRestApiMFAEnabled`
`-IsCliMFAEnabled -Path`

+
O parâmetro path especifica o local do arquivo XML de metadados do AD FS MFA.

+
Habilita o MFA para SnapCenter GUI, Rest API, PowerShell e SCCLI configurados com o caminho de arquivo de metadados do AD FS especificado.

. Verifique o status e as configurações da configuração do MFA usando o `Get-SmMultiFactorAuthentication` cmdlet.


*Interface SCCLI*

*Passos*

. `# sccli Set-SmMultiFactorAuthentication -IsGuiMFAEnabled true -IsRESTAPIMFAEnabled true -IsCliMFAEnabled true  -Path "C:\ADFS_metadata\abc.xml"`
. `# sccli Get-SmMultiFactorAuthentication`


*APIs REST*

. Execute a seguinte API de postagem para habilitar MFA para GUI, REST API, PowerShell e SCCLI.
+
|===


| Parâmetro | Valor 


 a| 
URL solicitada
 a| 
/api/4.9/settings/autenticação multifator



 a| 
Método HTTP
 a| 
Publicar



 a| 
Corpo da solicitação
 a| 
{ "IsGuiMFAEnabled": falso, "IsRestApiMFAEnabled": verdadeiro, "IsCliMFAEnabled": falso, "ADFSConfigFilePath": "C:\\ADFS_metadata\\abc.xml" }



 a| 
Corpo de Resposta
 a| 
{ "MFAConfiguration": { "IsGuiMFAEnabled": falso, "ADFSConfigFilePath": "C:\\ADFS_metadata\\abc.xml", "SCConfigFilePath": nulo, "IsRestApiMFAEnabled": verdadeiro, "IsCliMFAEnabled": falso, "ADFSHostName": "win-adfs-sc49.winscedom2.com" } }

|===
. Verifique o status e as configurações da configuração do MFA usando a seguinte API.
+
|===


| Parâmetro | Valor 


 a| 
URL solicitada
 a| 
/api/4.9/settings/autenticação multifator



 a| 
Método HTTP
 a| 
Pegar



 a| 
Corpo de Resposta
 a| 
{ "MFAConfiguration": { "IsGuiMFAEnabled": falso, "ADFSConfigFilePath": "C:\\ADFS_metadata\\abc.xml", "SCConfigFilePath": nulo, "IsRestApiMFAEnabled": verdadeiro, "IsCliMFAEnabled": falso, "ADFSHostName": "win-adfs-sc49.winscedom2.com" } }

|===

