---
permalink: install/task_configure_CA_client_certificate_for_LDAPS.html 
sidebar: sidebar 
keywords: CA client certificate, LDAPS 
summary: Você deve configurar o certificado do cliente CA para LDAPS no SnapCenter Server quando o Windows Active Directory LDAPS estiver configurado com os certificados CA. 
---
= Configurar certificado de cliente CA para LDAPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar o certificado do cliente CA para LDAPS no SnapCenter Server quando o Windows Active Directory LDAPS estiver configurado com os certificados CA.

*Passos*

. Acesse o console de gerenciamento da Microsoft (MMC) e clique em *Arquivo* > *Adicionar/Remover Snapin*.
. Na janela Adicionar ou remover snap-ins, selecione *Certificados* e clique em *Adicionar*.
. Na janela do snap-in Certificados, selecione a opção *Conta de computador* e clique em *Concluir*.
. Clique em *Console Root* > *Certificados – Computador local* > *Autoridades de certificação raiz confiáveis* > *Certificados*.
. Clique com o botão direito do mouse na pasta “Autoridades de Certificação Raiz Confiáveis” e selecione *Todas as Tarefas* > *Importar* para iniciar o assistente de importação.
. Conclua o assistente da seguinte forma:
+
|===
| Nesta janela do assistente... | Faça o seguinte... 


 a| 
Na segunda página do assistente
 a| 
Clique em *Procurar*, selecione o _Certificado Raiz_ e clique em *Avançar*.



 a| 
Concluindo o Assistente de Importação de Certificados
 a| 
Revise o resumo e clique em *Concluir* para iniciar a importação.

|===
. Repita as etapas 5 e 6 para os certificados intermediários.

