---
permalink: install/task_reclaim_space_on_the_storage_system.html 
sidebar: sidebar 
keywords: space, storage system, reclaim 
summary: Embora o NTFS rastreie o espaço disponível em um LUN quando os arquivos são excluídos ou modificados, ele não relata as novas informações ao sistema de armazenamento.  Você pode executar o cmdlet de recuperação de espaço do PowerShell no host do Plug-in para Windows para garantir que os blocos recém-liberados sejam marcados como disponíveis no armazenamento. 
---
= Recupere espaço no sistema de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Embora o NTFS rastreie o espaço disponível em um LUN quando os arquivos são excluídos ou modificados, ele não relata as novas informações ao sistema de armazenamento.  Você pode executar o cmdlet de recuperação de espaço do PowerShell no host do Plug-in para Windows para garantir que os blocos recém-liberados sejam marcados como disponíveis no armazenamento.

Se estiver executando o cmdlet em um host de plug-in remoto, você deverá executar o cmdlet SnapCenterOpen-SMConnection para abrir uma conexão com o SnapCenter Server.

.Antes de começar
* Você deve garantir que o processo de recuperação de espaço tenha sido concluído antes de executar uma operação de restauração.
* Se o LUN for compartilhado por hosts em um cluster de failover do Windows Server, você deverá executar a recuperação de espaço no host que possui o grupo de clusters.
* Para um desempenho ideal de armazenamento, você deve executar a recuperação de espaço com a maior frequência possível.
+
Você deve garantir que todo o sistema de arquivos NTFS tenha sido verificado.



*Sobre esta tarefa*

* A recuperação de espaço consome muito tempo e exige muita CPU, por isso, geralmente, é melhor executar a operação quando o uso do sistema de armazenamento e do host Windows estiver baixo.
* A recuperação de espaço recupera quase todo o espaço disponível, mas não 100%.
* Você não deve executar a desfragmentação do disco ao mesmo tempo em que estiver recuperando espaço.
+
Fazer isso pode atrasar o processo de recuperação.



*Etapa*

No prompt de comando do PowerShell do servidor de aplicativos, digite o seguinte comando:

`Invoke-SdHostVolumeSpaceReclaim -Path drive_path`

drive_path é o caminho da unidade mapeado para o LUN.
