---
permalink: install/task_configure_audit_log_settings.html 
sidebar: sidebar 
keywords: audit, log, configure 
summary: Você pode configurar o registro de eventos de segurança de plataformas de software e de todos os softwares em execução nessas plataformas. 
---
= Configurar definições de log de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os logs de auditoria são gerados para cada atividade do SnapCenter Server.  Por padrão, os logs de auditoria são protegidos no local de instalação padrão _C:\Arquivos de Programas\ NetApp\ SnapCenter WebApp\audit\_.

Os logs de auditoria são protegidos por meio da geração de um resumo assinado digitalmente para cada evento de auditoria para protegê-lo de modificações não autorizadas.  Os resumos gerados são mantidos no arquivo de soma de verificação de auditoria separado e passam por verificações periódicas de integridade para garantir a integridade do conteúdo.

Você deve ter efetuado login com a função "SnapCenterAdmin".

.Sobre esta tarefa
* Os alertas são enviados nos seguintes cenários:
+
** A verificação da integridade do log de auditoria ou o servidor Syslog está habilitado ou desabilitado
** Verificação de integridade do log de auditoria, log de auditoria ou falha do log do servidor Syslog
** Pouco espaço em disco


* O e-mail é enviado somente quando a verificação de integridade falha.
* Você deve modificar os caminhos do diretório do log de auditoria e do diretório do log de soma de verificação de auditoria juntos.  Você não pode modificar apenas um deles.
* Quando os caminhos do diretório do log de auditoria e do diretório do log de soma de verificação de auditoria são modificados, a verificação de integridade não pode ser executada nos logs de auditoria presentes no local anterior.
* Os caminhos do diretório do log de auditoria e do diretório do log de soma de verificação de auditoria devem estar na unidade local do SnapCenter Server.
+
Unidades compartilhadas ou montadas em rede não são suportadas.

* Se o protocolo UDP for usado nas configurações do servidor Syslog, erros devido a porta inativa ou indisponível não poderão ser capturados como um erro ou um alerta no SnapCenter.
* Você pode usar os comandos Set-SmAuditSettings e Get-SmAuditSettings para configurar os logs de auditoria.
+
As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando Get-Help command_name.  Alternativamente, você também pode consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência do cmdlet do software SnapCenter"^] .



.Passos
. Na página *Configurações*, navegue até *Configurações* > *Configurações globais* > *Configurações do log de auditoria*.
. Na seção Log de auditoria, insira os detalhes.
. Entre no *diretório de log de auditoria* e no *diretório de log de soma de verificação de auditoria*
+
.. Digite o tamanho máximo do arquivo
.. Insira o máximo de arquivos de log
.. Insira a porcentagem de uso do espaço em disco para enviar um alerta


. (Opcional) Habilite *Registrar hora UTC*.
. (Opcional) Habilite *Agendamento de verificação de integridade do log de auditoria* e clique em *Iniciar verificação de integridade* para verificação de integridade sob demanda.
+
Você também pode executar o comando *Start-SmAuditIntegrityCheck* para iniciar a verificação de integridade sob demanda.

. (Opcional) Habilite Logs de auditoria encaminhados para o servidor syslog remoto e insira os detalhes do servidor syslog.
+
Você deve importar o certificado do servidor Syslog para a 'Raiz Confiável' para o protocolo TLS 1.2.

+
.. Digite o host do servidor Syslog
.. Digite a porta do servidor Syslog
.. Digite o protocolo do servidor Syslog
.. Insira o formato RFC


. Clique em *Salvar*.
. Você pode ver as verificações de integridade de auditoria e as verificações de espaço em disco clicando em *Monitor* > *Tarefas*.

