---
permalink: install/task_configure_CA_certificate_with_snapcenter_site.html 
sidebar: sidebar 
keywords: SnapCenter, configure, CA certificate 
summary: Você deve configurar o certificado CA com o site SnapCenter no host Windows. 
---
= Configurar certificado CA com o site SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar o certificado CA com o site SnapCenter no host Windows.

*Passos*

. Abra o Gerenciador do IIS no Windows Server onde o SnapCenter está instalado.
. No painel de navegação esquerdo, clique em *Conexões*.
. Expanda o nome do servidor e *Sites*.
. Selecione o site do SnapCenter no qual você deseja instalar o Certificado SSL.
. Navegue até *Ações* > *Editar site* e clique em *Vinculações*.
. Na página Ligações, selecione *ligação para https*.
. Clique em *Editar*.
. Na lista suspensa do certificado SSL, selecione o certificado SSL importado recentemente.
. Clique em *OK*.
+

NOTE: O site do SnapCenter Scheduler (porta padrão: 8154, HTTPS) é configurado com certificado autoassinado.  Esta porta está se comunicando dentro do host do SnapCenter Server e não é obrigatório configurá-la com um certificado CA.  No entanto, se o seu ambiente exigir que você use um Certificado CA, repita as etapas 5 a 9 usando o site SnapCenter Scheduler.




NOTE: Se o certificado CA implantado recentemente não estiver listado no menu suspenso, verifique se o certificado CA está associado à chave privada.


IMPORTANT: Certifique-se de que o certificado seja adicionado usando o seguinte caminho: *Raiz do console > Certificados – Computador local > Autoridades de certificação raiz confiáveis > Certificados*.
