---
permalink: protect-scu/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux.html 
sidebar: sidebar 
keywords: prerequisites, iSCSI, host requirement for Linux, sudo privileges, non-root user, credentials, authenticate, domain administrator, local administrator, workgroup, sudo, root user 
summary: Antes de adicionar um host e instalar os pacotes de plug-ins, você deve atender a todos os requisitos. 
---
= Pré-requisitos para adicionar hosts e instalar o pacote de plug-ins para Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de adicionar um host e instalar o pacote de plug-ins para Linux, você deve atender a todos os requisitos.

* Se você estiver usando iSCSI, o serviço iSCSI deverá estar em execução.
* Você pode usar a autenticação baseada em senha para o usuário root ou não root ou a autenticação baseada em chave SSH.
+
O plug-in SnapCenter para sistemas de arquivos Unix pode ser instalado por um usuário não root.  No entanto, você deve configurar os privilégios sudo para que o usuário não root instale e inicie o processo do plug-in.  Após instalar o plug-in, os processos serão executados como um usuário não root.

* Crie credenciais com modo de autenticação como Linux para o usuário de instalação.
* Você deve ter instalado o Java 11 no seu host Linux.
+

NOTE: Certifique-se de ter instalado apenas a edição certificada do JAVA 11 no host Linux.

+
Para obter informações sobre como baixar o JAVA, consulte: http://www.java.com/en/download/manual.jsp["Downloads Java para todos os sistemas operacionais"^]

* Você deve ter *bash* como o shell padrão para instalação de plug-ins.




== Requisitos do host Linux

Você deve garantir que o host atenda aos requisitos antes de instalar o Pacote de plug-ins do SnapCenter para Linux.

|===
| Item | Requisitos 


 a| 
Sistemas operacionais
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* Servidor SUSE Linux Enterprise (SLES)




 a| 
RAM mínima para o plug-in SnapCenter no host
 a| 
2 GB



 a| 
Espaço mínimo de instalação e registro para o plug-in SnapCenter no host
 a| 
2 GB


NOTE: Você deve alocar espaço em disco suficiente e monitorar o consumo de armazenamento pela pasta de logs.  O espaço de log necessário varia dependendo do número de entidades a serem protegidas e da frequência das operações de proteção de dados.  Se não houver espaço em disco suficiente, os logs não serão criados para as operações executadas recentemente.



 a| 
Pacotes de software necessários
 a| 
Java 11 Oracle Java e OpenJDK


NOTE: Certifique-se de ter instalado apenas a edição certificada do JAVA 11 no host Linux.

Se você atualizou o JAVA para a versão mais recente, certifique-se de que a opção JAVA_HOME localizada em /var/opt/snapcenter/spl/etc/spl.properties esteja definida para a versão correta do JAVA e o caminho correto.

|===
Para obter as informações mais recentes sobre as versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["Ferramenta de Matriz de Interoperabilidade da NetApp"^] .
