---
permalink: protect-scu/task_configure_CA_certificate_with_SPL_on_Linux_host.html 
sidebar: sidebar 
keywords: SnapCenter, SPL, Plug-in loader service, CA certificate, certificate 
summary: Configurar certificado CA com o serviço SnapCenter Plug-in Loader no host Linux 
---
= Configurar certificado CA com o serviço SnapCenter Plug-in Loader (SPL) no host Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve gerenciar a senha do keystore SPL e seu certificado, configurar o certificado CA, configurar certificados raiz ou intermediários para o trust-store SPL e configurar o par de chaves assinadas pela CA para o trust-store SPL com o serviço SnapCenter Plug-in Loader para ativar o certificado digital instalado.


IMPORTANT: O SPL usa o arquivo 'keystore.jks', que está localizado em '/var/opt/snapcenter/spl/etc' como seu armazenamento confiável e armazenamento de chaves.



== Gerenciar senha para keystore SPL e alias do par de chaves assinadas pela CA em uso

*Passos*

. Você pode recuperar a senha padrão do keystore SPL a partir do arquivo de propriedades SPL.
+
É o valor correspondente à chave 'SPL_KEYSTORE_PASS'.

. Alterar a senha do keystore:
+
 keytool -storepasswd -keystore keystore.jks
. Altere a senha de todos os aliases de entradas de chave privada no keystore para a mesma senha usada para o keystore:
+
 keytool -keypasswd -alias "<alias_name>" -keystore keystore.jks
+
Atualize o mesmo para a chave SPL_KEYSTORE_PASS no arquivo spl.properties.

. Reinicie o serviço após alterar a senha.



NOTE: A senha para o keystore SPL e para todas as senhas de alias associadas da chave privada deve ser a mesma.



== Configurar certificados raiz ou intermediários para armazenamento confiável SPL

Você deve configurar os certificados raiz ou intermediários sem a chave privada para o armazenamento confiável SPL.

*Passos*

. Navegue até a pasta que contém o keystore SPL: _/var/opt/snapcenter/spl/etc_.
. Localize o arquivo 'keystore.jks'.
. Listar os certificados adicionados no keystore:
+
 keytool -list -v -keystore keystore.jks
. Adicione um certificado raiz ou intermediário:
+
 keytool -import -trustcacerts -alias <AliasNameForCerticateToBeImported> -file /<CertificatePath> -keystore keystore.jks
. Reinicie o serviço após configurar os certificados raiz ou intermediários para o armazenamento confiável SPL.



NOTE: Você deve adicionar o certificado da CA raiz e depois os certificados da CA intermediária.



== Configurar o par de chaves assinadas pela CA para o armazenamento confiável SPL

Você deve configurar o par de chaves assinadas pela CA para o armazenamento confiável SPL.

*Passos*

. Navegue até a pasta que contém o keystore do SPL /var/opt/snapcenter/spl/etc.
. Localize o arquivo 'keystore.jks'.
. Listar os certificados adicionados no keystore:
+
 keytool -list -v -keystore keystore.jks
. Adicione o certificado da CA com chave privada e pública.
+
 keytool -importkeystore -srckeystore <CertificatePathToImport> -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS
. Listar os certificados adicionados no keystore.
+
 keytool -list -v -keystore keystore.jks
. Verifique se o keystore contém o alias correspondente ao novo certificado CA, que foi adicionado ao keystore.
. Altere a senha da chave privada adicionada para o certificado CA para a senha do keystore.
+
A senha padrão do keystore SPL é o valor da chave SPL_KEYSTORE_PASS no arquivo spl.properties.

+
 keytool -keypasswd -alias "<aliasNameOfAddedCertInKeystore>" -keystore keystore.jks
. Se o nome do alias no certificado da CA for longo e contiver espaços ou caracteres especiais ("*",","), altere o nome do alias para um nome simples:
+
 keytool -changealias -alias "<OrignalAliasName>" -destalias "<NewAliasName>" -keystore keystore.jks
. Configure o nome do alias do keystore localizado no arquivo spl.properties.
+
Atualize este valor em relação à chave SPL_CERTIFICATE_ALIAS.

. Reinicie o serviço após configurar o par de chaves assinadas pela CA para o armazenamento confiável SPL.




== Configurar lista de revogação de certificados (CRL) para SPL

Você deve configurar o CRL para SPL

*Sobre esta tarefa*

* O SPL procurará os arquivos CRL em um diretório pré-configurado.
* O diretório padrão para os arquivos CRL do SPL é _/var/opt/snapcenter/spl/etc/crl_.


*Passos*

. Você pode modificar e atualizar o diretório padrão no arquivo spl.properties com a chave SPL_CRL_PATH.
. Você pode colocar mais de um arquivo CRL neste diretório.
+
Os certificados recebidos serão verificados em relação a cada CRL.


