---
permalink: protect-db2/considerations-for-determining-backup-schedules-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: 'O fator mais crítico na determinação de um cronograma de backup é a taxa de alteração do recurso.  Você pode fazer backup de um recurso muito utilizado a cada hora, enquanto pode fazer backup de um recurso raramente utilizado uma vez por dia.  Outros fatores incluem a importância do recurso para sua organização, seu acordo de nível de serviço (SLA) e seu objetivo de ponto de recuperação (RPO).' 
---
= Considerações para determinar agendamentos de backup para IBM Db2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O fator mais crítico na determinação de um cronograma de backup é a taxa de alteração do recurso.  Você pode fazer backup de um recurso muito utilizado a cada hora, enquanto pode fazer backup de um recurso raramente utilizado uma vez por dia.  Outros fatores incluem a importância do recurso para sua organização, seu acordo de nível de serviço (SLA) e seu objetivo de ponto de recuperação (RPO).

Os agendamentos de backup têm duas partes, conforme a seguir:

* Frequência de backup (com que frequência os backups devem ser realizados)
+
A frequência de backup, também chamada de tipo de agendamento para alguns plug-ins, faz parte de uma configuração de política.  Por exemplo, você pode configurar a frequência de backup como horária, diária, semanal ou mensal.

* Agendamentos de backup (exatamente quando os backups devem ser executados)
+
Os agendamentos de backup fazem parte de uma configuração de recurso ou grupo de recursos.  Por exemplo, se você tiver um grupo de recursos com uma política configurada para backups semanais, poderá configurar o agendamento para fazer backup todas as quintas-feiras às 22h.


