---
permalink: protect-db2/create-a-storage-system-connection-and-a-run-as-account-using-powershell-cmdlets-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: 'Você deve criar uma conexão de máquina virtual de armazenamento (SVM) e uma credencial antes de usar cmdlets do PowerShell para fazer backup, restaurar ou clonar bancos de dados IBM Db2.' 
---
= Crie uma conexão de sistema de armazenamento e uma credencial usando cmdlets do PowerShell para IBM Db2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve criar uma conexão de máquina virtual de armazenamento (SVM) e uma credencial antes de usar cmdlets do PowerShell para fazer backup, restaurar ou clonar bancos de dados IBM Db2.

.Antes de começar
* Você deve ter preparado o ambiente do PowerShell para executar os cmdlets do PowerShell.
* Você deve ter as permissões necessárias na função de administrador de infraestrutura para criar conexões de armazenamento.
* Você deve garantir que as instalações do plug-in não estejam em andamento.
+
As instalações do plug-in do host não devem estar em andamento ao adicionar uma conexão de sistema de armazenamento porque o cache do host pode não ser atualizado e o status dos bancos de dados pode ser exibido na GUI do SnapCenter como "`Não disponível para backup`" ou "`Não no armazenamento NetApp ".

* Os nomes dos sistemas de armazenamento devem ser exclusivos.
+
O SnapCenter não oferece suporte a vários sistemas de armazenamento com o mesmo nome em clusters diferentes.  Cada sistema de armazenamento suportado pelo SnapCenter deve ter um nome exclusivo e um endereço IP LIF de dados exclusivo.



.Passos
. Clique em *SnapCenterPS* para iniciar o PowerShell Core.
. Crie uma nova conexão com o sistema de armazenamento usando o cmdlet Add-SmStorageConnection.
+
[listing]
----
PS C:\> Add-SmStorageConnection -StorageType DataOntap -Type DataOntap -OntapStorage ‘scsnfssvm’ -Protocol Https -Timeout 60
----
. Crie uma nova credencial usando o cmdlet Add-SmCredential.
+
Este exemplo mostra como criar uma nova credencial chamada FinanceAdmin com credenciais do Windows:

+
[listing]
----
PS C:\> Add-SmCredential -Name 'FinanceAdmin' -Type Linux -AuthenticationType PasswordBased -Credential db2hostuser -EnableSudoPrevileges:$true
----
. Adicione o host de comunicação IBM Db2 ao SnapCenter Server.
+
Para Linux:

+
[listing]
----
PS C:\> Add-SmHost -HostType Linux -HostName '10.232.204.61' -CredentialName 'defaultcreds'
----
+
Para Windows:

+
[listing]
----
PS C:\> Add-SmHost -HostType Windows -HostName '10.232.204.61' -CredentialName 'defaultcreds'
----
. Instale o pacote e o plug-in SnapCenter para IBM Db2 no host.
+
Para Linux:

+
[listing]
----
PS C:\> Install-SmHostPackage -HostNames '10.232.204.61' -PluginCodes DB2
----
+
Para Windows:

+
[listing]
----
PS C:\> Install-SmHostPackage -HostNames '10.232.204.61' -PluginCodes DB2,SCW
----
. Defina o caminho para o SQLLIB.
+
Para Windows, o plug-in Db2 usará o caminho padrão para a pasta SQLLIB: “C:\Arquivos de Programas\IBM\SQLLIB\BIN”

+
Se você quiser substituir o caminho padrão, use o seguinte comando.

+
[listing]
----
PS C:\> Set-SmConfigSettings -Plugin -HostName '10.232.204.61' -PluginCode DB2 -configSettings @{"DB2_SQLLIB_CMD"="<custom_path>\IBM\SQLLIB\BIN"}

----


As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _Get-Help command_name_. Alternativamente, você também pode consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência do cmdlet do software SnapCenter"^] .
