---
permalink: protect-db2/generate-CA-certificate-CSR-file.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: 'Você pode gerar uma Solicitação de Assinatura de Certificado (CSR) e importar o certificado.' 
---
= Gerar arquivo CSR de certificado CA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerar uma Solicitação de Assinatura de Certificado (CSR) e importar o certificado que pode ser obtido de uma Autoridade de Certificação (CA) usando o CSR gerado.  O certificado terá uma chave privada associada a ele.

CSR é um bloco de texto codificado que é fornecido a um fornecedor de certificado autorizado para obter o certificado de CA assinado.


NOTE: O comprimento mínimo da chave RSA do certificado CA deve ser de 3072 bits.

Para obter informações sobre como gerar um CSR, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_generate_CA_Certificate_CSR_file["Como gerar um arquivo CSR de certificado CA"^] .


NOTE: Se você possui o certificado CA para seu domínio (*.domain.company.com) ou seu sistema (machine1.domain.company.com), você pode pular a geração do arquivo CSR do certificado CA.  Você pode implantar o certificado CA existente com o SnapCenter.

Para configurações de cluster, o nome do cluster (FQDN do cluster virtual) e os respectivos nomes de host devem ser mencionados no certificado da CA.  O certificado pode ser atualizado preenchendo o campo Nome Alternativo do Assunto (SAN) antes de adquirir o certificado.  Para um certificado curinga (*.domain.company.com), o certificado conterá todos os nomes de host do domínio implicitamente.
