---
permalink: protect-db2/prepare-storage-systems-for-snapmirror-and-snapvault-replication-for-plugin-for-db2.html 
sidebar: sidebar 
keywords: snapmirror, snapvault, storage system, replication 
summary: Você pode usar um plug-in SnapCenter com as tecnologias ONTAP SnapMirror e SnapVault 
---
= Preparar sistemas de armazenamento para replicação SnapMirror e SnapVault para IBM Db2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar um plug-in SnapCenter com a tecnologia ONTAP SnapMirror para criar cópias espelhadas de conjuntos de backup em outro volume e com a tecnologia ONTAP SnapVault para executar replicação de backup de disco para disco para conformidade com padrões e outros propósitos relacionados à governança.  Antes de executar essas tarefas, você deve configurar um relacionamento de proteção de dados entre os volumes de origem e destino e inicializar o relacionamento.

O SnapCenter executa as atualizações no SnapMirror e no SnapVault após concluir a operação Snapshot. As atualizações do SnapMirror e do SnapVault são executadas como parte do trabalho do SnapCenter ; não crie uma programação ONTAP separada.


NOTE: Se você estiver acessando o SnapCenter a partir de um produto NetApp SnapManager e estiver satisfeito com os relacionamentos de proteção de dados configurados, pode pular esta seção.

Um relacionamento de proteção de dados replica dados do armazenamento primário (o volume de origem) para o armazenamento secundário (o volume de destino).  Quando você inicializa o relacionamento, o ONTAP transfere os blocos de dados referenciados no volume de origem para o volume de destino.


NOTE: O SnapCenter não oferece suporte a relacionamentos em cascata entre volumes SnapMirror e SnapVault (*Primário* > *Espelho* > *Cofre*).  Você deve usar relacionamentos fanout.

O SnapCenter oferece suporte ao gerenciamento de relacionamentos SnapMirror flexíveis em termos de versão.  Para obter detalhes sobre relacionamentos SnapMirror flexíveis em termos de versão e como configurá-los, consulte http://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.ic-base%2Fresources%2Fhome.html["Documentação do ONTAP"^] .
