---
permalink: protect-nsp/add_hosts_and_install_plug_in_packages_on_remote_hosts.html 
sidebar: sidebar 
keywords: add hostsNetApp supported plug-ins, MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB, Storage plug-in 
summary: Você deve usar a página SnapCenterAdd Host para adicionar hosts e, em seguida, instalar os pacotes de plug-in.  Os plug-ins são instalados automaticamente nos hosts remotos.  Você pode adicionar um host e instalar os pacotes de plug-in para um host individual ou para um cluster. 
---
= Adicionar hosts e instalar pacotes de plug-ins em hosts remotos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve usar a página Adicionar Host do SnapCenter para adicionar hosts e, em seguida, instalar os pacotes de plug-in.  Os plug-ins são instalados automaticamente nos hosts remotos.  Você pode adicionar um host e instalar os pacotes de plug-in para um host individual ou para um cluster.

.Antes de começar
* Você deve ser um usuário atribuído a uma função que tenha permissões de instalação e desinstalação de plug-ins, como a função de administrador do SnapCenter .
* Você deve garantir que o serviço de enfileiramento de mensagens esteja em execução.
* Se estiver usando uma conta de serviço gerenciada em grupo (gMSA), você deverá configurar a gMSA com privilégios administrativos.
+
link:configure_gMSA_on_windows_server_2012_or_later.html["Configurar conta de serviço gerenciada de grupo no Windows Server 2016 ou posterior para aplicativos personalizados"]

* Para o host Windows, você deve garantir que selecionou o SnapCenter Plug-in para Windows.


.Sobre esta tarefa
* Não é possível adicionar um SnapCenter Server como um host de plug-in a outro SnapCenter Server.
* Se você instalar plug-ins em um cluster (WSFC), os plug-ins serão instalados em todos os nós do cluster.


.Passos
. No painel de navegação esquerdo, selecione *Hosts*.
. Verifique se a aba *Hosts Gerenciados* está selecionada na parte superior.
. Selecione *Adicionar*.
. Na página Hosts, execute as seguintes ações:
+
|===
| Para este campo... | Faça isso... 


 a| 
Tipo de host
 a| 
Selecione o tipo de host:

** Windows
** Linux
** AIX



NOTE: Os plug-ins suportados pela NetApp podem ser usados ​​em ambientes Windows, Linux e AIX.


NOTE: Aplicativos de armazenamento e Oracle são suportados no AIX.



 a| 
Nome do host
 a| 
Digite o nome de domínio totalmente qualificado (FQDN) ou o endereço IP do host.

O SnapCenter depende da configuração correta do DNS.  Portanto, a melhor prática é inserir o FQDN.

Para ambientes Windows, o endereço IP é suportado para hosts de domínio não confiáveis somente se for resolvido para o FQDN.

Você pode inserir os endereços IP ou FQDN de um host autônomo.

Se você estiver adicionando um host usando o SnapCenter e o host fizer parte de um subdomínio, você deverá fornecer o FQDN.



 a| 
Credenciais
 a| 
Selecione o nome da credencial que você criou ou crie novas credenciais.

As credenciais devem ter direitos administrativos no host remoto.  Para obter detalhes, consulte as informações sobre como criar credenciais.

Você pode visualizar detalhes sobre as credenciais posicionando o cursor sobre o nome da credencial que você especificou.


NOTE: O modo de autenticação de credenciais é determinado pelo tipo de host especificado no assistente Adicionar Host.

|===
. Na seção *Selecionar plug-ins para instalar*, selecione os plug-ins a serem instalados.
+
Você pode instalar os seguintes plug-ins da lista:

+
** MongoDB
** ORASCPM (exibido como Aplicativos Oracle)
** SAP ASE
** SAP MaxDB
** Armazenar


. (Opcional) Selecione *Mais opções* para instalar os outros plug-ins.
+
|===
| Para este campo... | Faça isso... 


 a| 
Porta
 a| 
Mantenha o número da porta padrão ou especifique o número da porta.

O número da porta padrão é 8145.  Se o SnapCenter Server foi instalado em uma porta personalizada, esse número de porta será exibido como a porta padrão.


NOTE: Se você instalou manualmente os plug-ins e especificou uma porta personalizada, deverá especificar a mesma porta.  Caso contrário, a operação falhará.



 a| 
Caminho de instalação
 a| 
Os plug-ins suportados pela NetApp podem ser instalados em um sistema Windows ou Linux.

** Para o pacote de plug-ins SnapCenter para Windows, o caminho padrão é C:\Arquivos de Programas\ NetApp\ SnapCenter.
+
Opcionalmente, você pode personalizar o caminho.

** Para o pacote de plug-ins SnapCenter para Linux e o pacote de plug-ins SnapCenter para AIX, o caminho padrão é `/opt/NetApp/snapcenter` .
+
Opcionalmente, você pode personalizar o caminho.





 a| 
Ignorar verificações de pré-instalação
 a| 
Marque esta caixa de seleção se você já instalou os plug-ins manualmente e não deseja validar se o host atende aos requisitos para instalar o plug-in.



 a| 
Use a conta de serviço gerenciada em grupo (gMSA) para executar os serviços do plug-in
 a| 
Para o host Windows, marque esta caixa de seleção se desejar usar a Conta de Serviço Gerenciada em Grupo (gMSA) para executar os serviços do plug-in.


IMPORTANT: Forneça o nome do gMSA no seguinte formato: domainName\accountName$.


NOTE: O gMSA será usado como uma conta de serviço de logon somente para o serviço SnapCenter Plug-in para Windows.

|===
. Selecione *Enviar*.
+
Se você não tiver marcado a caixa de seleção *Ignorar pré-verificações*, o host será validado para verificar se atende aos requisitos para a instalação do plug-in. O espaço em disco, a RAM, a versão do PowerShell, a versão do .NET, a localização (para plug-ins do Windows) e a versão do Java (para plug-ins do Linux) são validados em relação aos requisitos mínimos.  Se os requisitos mínimos não forem atendidos, mensagens de erro ou aviso apropriadas serão exibidas.

+
Se o erro estiver relacionado ao espaço em disco ou à RAM, você pode atualizar o arquivo web.config localizado em `C:\Program Files\NetApp\SnapCenter WebApp` para modificar os valores padrão.  Se o erro estiver relacionado a outros parâmetros, você deverá corrigir o problema.

+

NOTE: Em uma configuração de HA, se você estiver atualizando o SnapManager.Web.UI.dll.config, deverá atualizar o arquivo em ambos os nós e reiniciar o SnapCenter App Pool.

+
O caminho padrão do Windows é `C:\Program Files\NetApp\SnapCenter WebApp\SnapManager.Web.UI.dll.config`

+
O caminho padrão do Linux é `/opt/NetApp/snapcenter/SnapManagerWeb/SnapManager.Web.UI.dll.config`

. Se o tipo de host for Linux, verifique a impressão digital e selecione *Confirmar e Enviar*.
+

NOTE: A verificação de impressão digital é obrigatória mesmo que o mesmo host tenha sido adicionado anteriormente ao SnapCenter e a impressão digital tenha sido confirmada.

. Monitore o progresso da instalação.
+
Os arquivos de log específicos da instalação estão localizados em `/custom_location/snapcenter/` registros.


