---
permalink: protect-nsp/configure_CA_certificate_on_windows_host.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Configurar o certificado CA para o serviço de plug-ins suportados pela NetApp no ​​host Windows 
---
= Configurar o certificado CA para o serviço de plug-ins suportados pela NetApp no ​​host Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve gerenciar a senha do keystore do plug-in e seu certificado, configurar o certificado da CA, configurar certificados raiz ou intermediários para o trust-store do plug-in e configurar o par de chaves assinadas pela CA para o trust-store do plug-in com o serviço de plug-ins do SnapCenter para ativar o certificado digital instalado.

Os plug-ins usam o arquivo _keystore.jks_, que está localizado em _C:\Program Files\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\etc_ como seu armazenamento confiável e armazenamento de chaves.



== Gerenciar senha para keystore de plug-in e alias do par de chaves assinadas pela CA em uso

.Passos
. Você pode recuperar a senha padrão do keystore do plug-in a partir do arquivo de propriedades do agente do plug-in.
+
É o valor correspondente à chave _KEYSTORE_PASS_.

. Alterar a senha do keystore:
+
_keytool -storepasswd -keystore keystore.jks_

+

NOTE: Se o comando "keytool" não for reconhecido no prompt de comando do Windows, substitua o comando keytool pelo seu caminho completo.

+
_C:\Arquivos de Programas\Java\<versão_jdk>\bin\keytool.exe" -storepasswd -keystore keystore.jks_

. Altere a senha de todos os aliases de entradas de chave privada no keystore para a mesma senha usada para o keystore:
+
_keytool -keypasswd -alias "nome_do_alias_no_certificado" -keystore keystore.jks_

+
Atualize o mesmo para a chave KEYSTORE_PASS no arquivo _agent.properties_.

. Reinicie o serviço após alterar a senha.
+

NOTE: A senha para o keystore do plug-in e para todas as senhas de alias associadas da chave privada deve ser a mesma.





== Configurar certificados raiz ou intermediários para plug-in trust-store

Você deve configurar os certificados raiz ou intermediários sem a chave privada para conectar o trust-store.

.Passos
. Navegue até a pasta que contém o keystore do plug-in _C:\Program Files\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\etc_
. Localize o arquivo 'keystore.jks'.
. Listar os certificados adicionados no keystore:
+
_keytool -list -v -keystore keystore.jks_

. Adicione um certificado raiz ou intermediário:
+
_keytool -import -trustcacerts -alias myRootCA -file /root/USERTrustRSA_Root.cer -keystore keystore.jks_

. Reinicie o serviço após configurar os certificados raiz ou intermediários para conectar o trust-store.



NOTE: Você deve adicionar o certificado da CA raiz e depois os certificados da CA intermediária.



== Configurar o par de chaves assinadas pela CA para plug-in trust-store

Você deve configurar o par de chaves assinadas pela CA para o trust-store do plug-in.

.Passos
. Navegue até a pasta que contém o keystore do plug-in _C:\Program Files\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\etc_
. Localize o arquivo _keystore.jks_.
. Listar os certificados adicionados no keystore:
+
_keytool -list -v -keystore keystore.jks_

. Adicione o certificado da CA com chave privada e pública.
+
_keytool -importkeystore -srckeystore /root/snapcenter.ssl.test.netapp.com.pfx -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS_

. Listar os certificados adicionados no keystore.
+
_keytool -list -v -keystore keystore.jks_

. Verifique se o keystore contém o alias correspondente ao novo certificado CA, que foi adicionado ao keystore.
. Altere a senha da chave privada adicionada para o certificado CA para a senha do keystore.
+
A senha padrão do keystore do plug-in é o valor da chave KEYSTORE_PASS no arquivo agent.properties.

+
_keytool -keypasswd -alias "nome_do_alias_no_certificado_da_CA" -keystore keystore.jks_

. Configure o nome do alias do certificado CA no arquivo _agent.properties_.
+
Atualize este valor em relação à chave SCC_CERTIFICATE_ALIAS.

. Reinicie o serviço após configurar o par de chaves assinadas pela CA para plug-in trust-store.




== Configurar lista de revogação de certificados (CRL) para plug-ins SnapCenter

.Sobre esta tarefa
* Para baixar o arquivo CRL mais recente para o certificado CA relacionado, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_update_certificate_revocation_list_file_in_SnapCenter_CA_Certificate["Como atualizar o arquivo de lista de revogação de certificados no SnapCenter CA Certificate"] .
* Os plug-ins do SnapCenter procurarão os arquivos CRL em um diretório pré-configurado.
* O diretório padrão para os arquivos CRL dos plug-ins do SnapCenter é _'C:\Arquivos de Programas\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\ etc\crl'_.


.Passos
. Você pode modificar e atualizar o diretório padrão no arquivo _agent.properties_ em relação à chave CRL_PATH.
. Você pode colocar mais de um arquivo CRL neste diretório.
+
Os certificados recebidos serão verificados em relação a cada CRL.


