---
permalink: protect-nsp/define_a_backup_strategy.html 
sidebar: sidebar 
keywords: backup strategy 
summary: 'Definir uma estratégia de backup antes de criar suas tarefas de backup garante que você tenha os backups necessários para restaurar ou clonar seus recursos com sucesso.  Seu contrato de nível de serviço (SLA), objetivo de tempo de recuperação (RTO) e objetivo de ponto de recuperação (RPO) determinam em grande parte sua estratégia de backup.' 
---
= Definir uma estratégia de backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Definir uma estratégia de backup antes de criar suas tarefas de backup garante que você tenha os backups necessários para restaurar ou clonar seus recursos com sucesso.  Seu contrato de nível de serviço (SLA), objetivo de tempo de recuperação (RTO) e objetivo de ponto de recuperação (RPO) determinam em grande parte sua estratégia de backup.

.Sobre esta tarefa
Um SLA define o nível de serviço esperado e aborda muitas questões relacionadas ao serviço, incluindo a disponibilidade e o desempenho do serviço.  RTO é o tempo em que um processo de negócios deve ser restaurado após uma interrupção no serviço.  O RPO define a estratégia para a idade dos arquivos que devem ser recuperados do armazenamento de backup para que as operações regulares sejam retomadas após uma falha.  SLA, RTO e RPO contribuem para a estratégia de proteção de dados.

.Passos
. Determine quando você deve fazer backup dos seus recursos.
. Decida quantos trabalhos de backup você precisa.
. Decida como nomear seus backups.
. Decida se você deseja Snapshots do Grupo de Consistência e decida sobre as opções apropriadas para excluir Snapshots do Grupo de Consistência.
. Decida se você deseja usar a tecnologia NetApp SnapMirror para replicação ou a tecnologia NetApp SnapVault para retenção de longo prazo.
. Determine o período de retenção dos Snapshots no sistema de armazenamento de origem e no destino do SnapMirror .
. Determine se você deseja executar algum comando antes ou depois da operação de backup e forneça uma prescrição ou pós-escrito.

