---
permalink: protect-nsp/how_resources_resource_groups_policies_used_for_protecting_netapp_supported_plugins_resources.html 
sidebar: sidebar 
keywords: NetApp supported plug-in 
summary: Antes de usar o SnapCenter, é útil entender os conceitos básicos relacionados às operações de backup, clonagem e restauração que você deseja executar.  Você interage com recursos, grupos de recursos e políticas para diferentes operações. 
---
= Como recursos, grupos de recursos e políticas são usados ​​para proteger recursos de plug-in com suporte da NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar o SnapCenter, é útil entender os conceitos básicos relacionados às operações de backup, clonagem e restauração que você deseja executar.  Você interage com recursos, grupos de recursos e políticas para diferentes operações.

* Os recursos geralmente são bancos de dados, sistemas de arquivos do Windows ou VMs que você faz backup ou clona com o SnapCenter.
* Um grupo de recursos do SnapCenter é uma coleção de recursos em um host ou cluster.
+
Ao executar uma operação em um grupo de recursos, você executa essa operação nos recursos definidos no grupo de recursos de acordo com o cronograma especificado para o grupo de recursos.

+
Você pode fazer backup sob demanda de um único recurso ou de um grupo de recursos.  Você também pode executar backups agendados para recursos individuais e grupos de recursos.

* As políticas especificam a frequência de backup, retenção de cópias, replicação, scripts e outras características das operações de proteção de dados.
+
Ao criar um grupo de recursos, você seleciona uma ou mais políticas para esse grupo.  Você também pode selecionar uma política ao executar um backup sob demanda para um único recurso.



Pense em um grupo de recursos como definidor de _o que_ você quer proteger e quando quer proteger em termos de dia e hora.  Pense em uma política como a definição de _como_ você quer protegê-la.  Se você estiver fazendo backup de todos os bancos de dados ou de todos os sistemas de arquivos de um host, por exemplo, poderá criar um grupo de recursos que inclua todos os bancos de dados ou todos os sistemas de arquivos no host.  Você pode então anexar duas políticas ao grupo de recursos: uma política diária e uma política horária.  Ao criar o grupo de recursos e anexar as políticas, você pode configurar o grupo de recursos para executar um backup baseado em arquivo diariamente e outra programação que executa um backup baseado em instantâneo a cada hora.
