---
permalink: protect-nsp/install_snapcenter_plug_in_packages_for_linux_or_windows_on_multiple_remote_hosts_using_cmdlets.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: Você pode instalar os pacotes de plug-in do SnapCenter para Linux ou Windows em vários hosts simultaneamente usando o cmdlet Install-SmHostPackage do PowerShell. 
---
= Instalar pacotes de plug-in SnapCenter para Linux, Windows ou AIX em vários hosts remotos usando cmdlets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode instalar os pacotes de plug-in do SnapCenter para Linux, Windows ou AIX em vários hosts simultaneamente usando o cmdlet Install-SmHostPackage do PowerShell.

.Antes de começar
O usuário que adiciona um host deve ter direitos administrativos no host.


NOTE: Aplicativos de armazenamento e Oracle são suportados no AIX.

.Passos
. Inicie o PowerShell.
. No host do SnapCenter Server, estabeleça uma sessão usando o cmdlet Open-SmConnection e insira suas credenciais.
. Instale o plug-in em vários hosts usando o cmdlet Install-SmHostPackage e os parâmetros necessários.
+
As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _Get-Help command_name_. Alternativamente, você também pode consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência do cmdlet do software SnapCenter"^] .

+
Você pode usar a opção -skipprecheck quando tiver instalado os plug-ins manualmente e não quiser validar se o host atende aos requisitos para instalar o plug-in.

. Insira suas credenciais para instalação remota.

