---
permalink: protect-nsp/prerequisites_for_using_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: Credentials 
summary: Antes de usar os plug-ins suportados SnapCenter NetApp , o administrador do SnapCenter deve instalar e configurar o SnapCenter Server e executar as tarefas de pré-requisito. 
---
= Pré-requisitos para usar os plug-ins suportados pela NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar os plug-ins suportados SnapCenter NetApp , o administrador do SnapCenter deve instalar e configurar o SnapCenter Server e executar as tarefas de pré-requisito.

* Instalar e configurar o SnapCenter Server.
* Efetue login no SnapCenter Server.
* Configure o ambiente SnapCenter adicionando conexões do sistema de armazenamento e criando credenciais, se aplicável.
* Adicione hosts, instale e carregue os plug-ins.
* Se aplicável, instale o Java 11 no host do plug-in.
* Se você tiver vários caminhos de dados (LIFs) ou uma configuração dNFS, poderá executar o seguinte usando a CLI do SnapCenter no host do banco de dados:
+
** Por padrão, todos os endereços IP do host do banco de dados são adicionados à política de exportação de armazenamento NFS na máquina virtual de armazenamento (SVM) para os volumes clonados.  Se você quiser ter um endereço IP específico ou restringir a um subconjunto de endereços IP, execute a CLI Set-PreferredHostIPsInStorageExportPolicy.
** Se você tiver vários caminhos de dados (LIFs) em SVMs, o SnapCenter escolherá o caminho de dados (LIF) apropriado para montar o volume clonado NFS. No entanto, se você quiser especificar um caminho de dados específico (LIF), deverá executar a CLI Set-SvmPreferredDataPath. As informações sobre os parâmetros que podem ser usados ​​com o comando e suas descrições podem ser obtidas executando _Get-Help command_name_. Alternativamente, você também pode consultar o https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["Guia de referência de comandos do software SnapCenter"^] .


* Configure o SnapMirror e o SnapVault se desejar replicação de backup.
* Certifique-se de que a porta 9090 não esteja sendo usada por nenhum outro aplicativo no host.
+
A porta 9090 deve ser reservada para uso por plug-ins suportados NetApp , além das outras portas exigidas pelo SnapCenter.


