---
permalink: get-started/concept_resources_resource_groups_and_policies.html 
sidebar: sidebar 
keywords: resource, resource group, policy 
summary: Antes de usar o SnapCenter, é útil entender os conceitos básicos relacionados às operações de backup, clonagem e restauração que você deseja executar. 
---
= Conceitos-chave de proteção de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar o SnapCenter, entenda os principais conceitos de backup, clonagem e restauração.



== Recursos

Os recursos incluem bancos de dados, sistemas de arquivos do Windows ou compartilhamentos de arquivos copiados ou clonados com o SnapCenter.  Dependendo do seu ambiente, os recursos também podem ser instâncias de banco de dados, grupos de disponibilidade do SQL Server, bancos de dados Oracle, bancos de dados RAC ou grupos de aplicativos personalizados.



== Grupo de recursos

Um grupo de recursos é uma coleção de recursos em um host ou cluster, potencialmente de vários hosts e clusters.  As operações executadas em um grupo de recursos se aplicam a todos os seus recursos com base no cronograma especificado.  Você pode executar backups sob demanda ou agendados para recursos individuais ou grupos.


NOTE: Se um host em um grupo de recursos compartilhados entrar no modo de manutenção, todas as operações agendadas para esse grupo serão suspensas em todos os hosts.

Use plug-ins relevantes para fazer backup de recursos específicos: plug-ins de banco de dados para bancos de dados, plug-ins de sistema de arquivos para sistemas de arquivos e SnapCenter Plug-in for VMware vSphere para VMs e datastores.



== Políticas

As políticas especificam a frequência de backup, retenção de cópias, replicação, scripts e outras características das operações de proteção de dados.

Uma ou mais políticas podem ser selecionadas ao criar um grupo de recursos ou ao executar um backup sob demanda.

Um grupo de recursos define o que precisa ser protegido e quando deve ser protegido em termos de dia e hora.  Uma política descreve como a proteção será realizada.  Por exemplo, se for necessário fazer backup de todos os bancos de dados ou sistemas de arquivos de um host, um grupo de recursos incluindo todos os bancos de dados ou sistemas de arquivos no host poderá ser criado.  Duas políticas podem então ser anexadas ao grupo de recursos: uma política diária e uma política horária.

Ao criar o grupo de recursos e anexar as políticas, é possível configurá-lo para executar um backup completo diariamente e outro agendamento para backups de log a cada hora.

Prescrições e pós-escritos personalizados podem ser usados em operações de proteção de dados.  Esses scripts permitem a automação antes ou depois do trabalho de proteção de dados.  Por exemplo, um script pode notificar automaticamente sobre falhas ou avisos de tarefas de proteção de dados.  Entender os requisitos para criar esses scripts é crucial antes de configurar prescrições e pós-escritos.



== Uso de prescrições e posfácios

Prescrições e pós-escritos personalizados podem automatizar suas tarefas de proteção de dados antes ou depois do trabalho.  Por exemplo, você pode adicionar um script para notificá-lo sobre falhas de trabalho ou avisos.  Antes de configurá-los, certifique-se de entender os requisitos desses scripts.



=== Tipos de script suportados

Os seguintes tipos de scripts são suportados pelo Windows:

* Arquivos em lote
* Scripts do PowerShell
* Scripts Perl


Os seguintes tipos de scripts são suportados pelo UNIX:

* Scripts Perl
* Scripts Python
* Scripts de shell
+

NOTE: Junto com o shell bash padrão, outros shells como sh-shell, k-shell e c-shell também são suportados.





=== Caminho do script

Todos os prescrições e pós-escritos executados como parte das operações do SnapCenter em sistemas de armazenamento virtualizados e não virtualizados são executados no host do plug-in.

* Os scripts do Windows devem estar localizados no host do plug-in.



NOTE: O caminho de prescrições ou pós-escritos não deve incluir unidades ou compartilhamentos.  O caminho deve ser relativo ao SCRIPTS_PATH.

* Os scripts UNIX devem estar localizados no host do plug-in.



NOTE: O caminho do script é validado no momento da execução.



=== Onde especificar scripts

Os scripts são especificados em políticas de backup.  Quando uma tarefa de backup é iniciada, a política associa automaticamente o script aos recursos que estão sendo copiados.  Ao criar uma política de backup, você pode especificar os argumentos prescript e postscript.


NOTE: Você não pode especificar vários scripts.



=== Tempo limite de script

O tempo limite é definido como 60 segundos, por padrão.  Você pode modificar o valor do tempo limite.



=== Saída do script

O diretório padrão para os arquivos de saída de prescrições e postscripts do Windows é Windows\System32.

Não há um local padrão para os prescrições e pós-escritos do UNIX.  Você pode redirecionar o arquivo de saída para qualquer local preferido.
