---
permalink: get-started/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication, untrusted domain, local workgroup, windows authentication, SQL Server authentication, Linux authentication, AIX authentication, Oracle database authentication, Oracle ASM authentication, RMAN catalog authentication 
summary: As credenciais usam métodos de autenticação diferentes dependendo do aplicativo ou ambiente.  As credenciais autenticam os usuários para que eles possam executar operações do SnapCenter .  Você deve criar um conjunto de credenciais para instalar plug-ins e outro conjunto para operações de proteção de dados. 
---
= Métodos de autenticação para credenciais do SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As credenciais usam métodos de autenticação diferentes dependendo do aplicativo ou ambiente.  As credenciais autenticam os usuários para que eles possam executar operações do SnapCenter .  Você deve criar um conjunto de credenciais para instalar plug-ins e outro para operações de proteção de dados.



== Autenticação do Windows

O método de autenticação do Windows autentica no Active Directory.  Para autenticação do Windows, o Active Directory é configurado fora do SnapCenter.  O SnapCenter autentica sem nenhuma configuração adicional.  Você precisa de uma credencial do Windows para adicionar hosts, instalar pacotes de plug-ins e agendar tarefas.



== Autenticação de domínio não confiável

O SnapCenter permite que usuários e grupos pertencentes a domínios não confiáveis ​​criem credenciais do Windows.  Para que a autenticação seja bem-sucedida, você deve registrar os domínios não confiáveis ​​no SnapCenter.



== Autenticação de grupo de trabalho local

O SnapCenter permite a criação de credenciais do Windows com usuários e grupos de grupos de trabalho locais.  A autenticação do Windows para usuários e grupos de grupos de trabalho locais não ocorre durante a criação de credenciais do Windows, mas é adiada até que o registro do host e outras operações do host sejam executadas.



== Autenticação do SQL Server

O método de autenticação SQL autentica em uma instância do SQL Server.  Isso significa que uma instância do SQL Server deve ser descoberta no SnapCenter.  Portanto, antes de adicionar uma credencial SQL, você deve adicionar um host, instalar pacotes de plug-in e atualizar os recursos.  Você precisa da autenticação do SQL Server para executar operações como agendamento no SQL Server ou descobrir recursos.



== Autenticação Linux

O método de autenticação do Linux autentica em um host Linux.  Você precisa de autenticação do Linux durante a etapa inicial de adição do host Linux e instalação remota do Pacote de plug-ins do SnapCenter para Linux a partir da GUI do SnapCenter .



== Autenticação AIX

O método de autenticação AIX autentica em um host AIX.  Você precisa da autenticação do AIX durante a etapa inicial de adição do host do AIX e instalação remota do Pacote de plug-ins do SnapCenter para AIX a partir da GUI do SnapCenter .



== Autenticação de banco de dados Oracle

O método de autenticação do banco de dados Oracle autentica em um banco de dados Oracle.  Você precisa de uma autenticação de banco de dados Oracle para executar operações no banco de dados Oracle se a autenticação do sistema operacional (SO) estiver desabilitada no host do banco de dados.  Portanto, antes de adicionar uma credencial de banco de dados Oracle, você deve criar um usuário Oracle no banco de dados Oracle com privilégios sysdba.



== Autenticação Oracle ASM

O método de autenticação Oracle ASM autentica em uma instância do Oracle Automatic Storage Management (ASM).  A autenticação do Oracle ASM será necessária se você precisar acessar uma instância do Oracle ASM e a autenticação do sistema operacional estiver desabilitada no host do banco de dados.  Antes de adicionar uma credencial do Oracle ASM, crie um usuário Oracle com privilégios de sistema na instância do ASM.



== Autenticação de catálogo RMAN

O método de autenticação do catálogo RMAN autentica no banco de dados do catálogo Oracle Recovery Manager (RMAN).  Se você configurou um mecanismo de catálogo externo e registrou seu banco de dados no banco de dados de catálogo, será necessário adicionar a autenticação de catálogo do RMAN.
