---
permalink: get-started/reference_data_security.html 
sidebar: sidebar 
keywords: security, authentication, CA certificates, FIPS, SSL, AES, TLS, RBAC, MFA, multi-factor authentication 
summary: O SnapCenter emprega recursos rigorosos de segurança e autenticação para permitir que você mantenha seus dados seguros. 
---
= Recursos de segurança no SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapCenter emprega recursos rigorosos de segurança e autenticação para permitir que você mantenha seus dados seguros.

O SnapCenter inclui os seguintes recursos de segurança:

* Toda a comunicação com o SnapCenter usa HTTP sobre SSL (HTTPS).
* Todas as credenciais no SnapCenter são protegidas usando criptografia Advanced Encryption Standard (AES).
* Suporta algoritmos de segurança compatíveis com o Padrão Federal de Processamento de Informações (FIPS).
* Suporta o uso de certificados de CA autorizados fornecidos pelo cliente.
* Suporta Transport Layer Security (TLS) 1.3 para comunicação com ONTAP.  Você também pode usar o TLS 1.2 para comunicação entre clientes e servidores.
* Oferece suporte a um determinado conjunto de conjuntos de cifras SSL para fornecer segurança na comunicação de rede. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_the_supported_SSL_Cipher_Suite["Saber mais"] .
* O SnapCenter é instalado dentro do firewall da sua empresa para permitir o acesso ao SnapCenter Server e permitir a comunicação entre o SnapCenter Server e os plug-ins.
* O acesso à API e à operação do SnapCenter usa tokens criptografados com criptografia AES, que expiram após 24 horas.
* O SnapCenter integra-se ao Windows Active Directory para login e controle de acesso baseado em função (RBAC) que controlam as permissões de acesso.
* O IPsec é compatível com o SnapCenter no ONTAP para máquinas host Windows e Linux. https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html#use-ipsec-identities["Saber mais"] .
* Os cmdlets do SnapCenter PowerShell são protegidos por sessão.
* Após um período padrão de 15 minutos de inatividade, o SnapCenter avisa que você será desconectado em 5 minutos.
+
Após 20 minutos de inatividade, o SnapCenter desconecta você e você deve efetuar login novamente.  Você pode modificar o período de logout.

* O login é temporariamente desativado após 5 tentativas incorretas de login.
* Suporta autenticação de certificado CA entre SnapCenter Server e ONTAP. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_securely_connect_SnapCenter_with_ONTAP_using_CA_certificate["Saber mais"] .
* O Integrity Verifier é adicionado ao SnapCenter Server e aos plug-ins e valida todos os binários enviados durante novas operações de instalação e atualização.




== Visão geral do certificado CA

O instalador do SnapCenter Server habilita o suporte ao certificado SSL centralizado durante a instalação.  Para melhorar a comunicação segura entre o servidor e o plug-in, o SnapCenter oferece suporte ao uso de certificados de CA autorizados fornecidos pelo cliente.

Você deve implantar certificados de CA após instalar o SnapCenter Server e os respectivos plug-ins. Para obter mais informações, consulte link:../install/reference_generate_CA_certificate_CSR_file.html["Gerar arquivo CSR de certificado CA"] .

Você também pode implantar o certificado CA para o plug-in SnapCenter para VMware vSphere. Para obter mais informações, consulte  https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_and_import_certificates.html["Criar e importar certificados"^] .



== Comunicação SSL bidirecional

A comunicação SSL bidirecional protege a comunicação mútua entre o SnapCenter Server e os plug-ins.



== Visão geral da autenticação baseada em certificado

A autenticação baseada em certificado verifica a autenticidade dos respectivos usuários que tentam acessar o host do plug-in SnapCenter .  O usuário deve exportar o certificado do SnapCenter Server sem a chave privada e importá-lo no armazenamento confiável do host do plug-in.  A autenticação baseada em certificado funciona somente se o recurso SSL bidirecional estiver habilitado.



== Autenticação multifator (MFA)

O MFA usa um Provedor de Identidade (IdP) de terceiros por meio da Linguagem de Marcação de Asserção de Segurança (SAML) para gerenciar sessões de usuários.  Essa funcionalidade aumenta a segurança da autenticação ao oferecer a opção de usar vários fatores, como TOTP, biometria, notificações push etc., juntamente com o nome de usuário e a senha existentes.  Além disso, ele permite que o cliente use seus próprios provedores de identidade de usuário para obter login de usuário unificado (SSO) em todo o seu portfólio.

O MFA é aplicável somente ao login da interface de usuário do SnapCenter Server.  Os logins são autenticados por meio do IdP Active Directory Federation Services (AD FS).  Você pode configurar vários fatores de autenticação no AD FS.  O SnapCenter é o provedor de serviços e você deve configurar o SnapCenter como uma parte confiável no AD FS.  Para habilitar o MFA no SnapCenter, você precisará dos metadados do AD FS.

Para obter informações sobre como habilitar o MFA, consultelink:../install/enable_multifactor_authentication.html["Habilitar autenticação multifator"] .
