---
permalink: uninstall/task_uninstall_plug_ins_from_a_host_using_the_snapcenter_gui.html 
sidebar: sidebar 
keywords: uninstall, gui 
summary: Quando você decidir que não precisa mais de um plug-in individual ou de um pacote de plug-ins, poderá desinstalá-lo usando a interface do SnapCenter . 
---
= Desinstalar plug-ins usando a interface gráfica do usuário do SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você decidir que não precisa mais de um plug-in individual ou de um pacote de plug-ins, poderá desinstalá-lo usando a interface do SnapCenter .

.Antes de começar
* Você deve ter removido os grupos de recursos do pacote de plug-in que está desinstalando.
* Você deve ter desanexado as políticas associadas aos grupos de recursos do pacote de plug-in que está desinstalando.


.Sobre esta tarefa
Você pode desinstalar um plug-in individual. Por exemplo, talvez seja necessário desinstalar o plug-in SnapCenter para Microsoft SQL Server porque um host está ficando sem recursos e você deseja mover esse plug-in para um host mais potente.  Você também pode desinstalar um pacote de plug-in inteiro.  Por exemplo, talvez seja necessário desinstalar o pacote de plug-ins do SnapCenter para Linux, que inclui o plug-in do SnapCenter para Oracle Database e o plug-in do SnapCenter para UNIX.

* Remover um host inclui desinstalar todos os plug-ins.
+
Quando você remove um host do SnapCenter, o SnapCenter desinstala todos os pacotes de plug-in no host antes de removê-lo.

* A interface gráfica do usuário do SnapCenter remove plug-ins de um host por vez.
+
Ao usar a interface gráfica do usuário do SnapCenter , você pode desinstalar plug-ins em apenas um host por vez.  No entanto, você pode ter várias operações de desinstalação em execução ao mesmo tempo.

+
Você também pode desinstalar um plug-in de vários hosts usando o cmdlet _Uninstall-SmHostPackage_ e os parâmetros necessários.  As informações sobre os parâmetros que podem ser usados com o cmdlet e suas descrições podem ser obtidas executando _Get-Help command_name_. Alternativamente, você também pode consultar o https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guia de referência do cmdlet do software SnapCenter"^] .




IMPORTANT: Desinstalar o pacote de plug-ins do SnapCenter para Windows de um host no qual o SnapCenter Server está instalado danificará a instalação do SnapCenter Server.  Não desinstale o pacote de plug-ins do SnapCenter para Windows, a menos que tenha certeza de que não precisa mais do SnapCenter Server.

.Passos
. No painel de navegação esquerdo, clique em *Hosts*.
. Na página Hosts, clique em *Hosts gerenciados*.
. Na página Hosts gerenciados, selecione o host do qual você deseja desinstalar o plug-in ou pacote de plug-ins.
. Ao lado do plug-in que você deseja remover, clique em *Remover* > *Enviar*.


.Depois que você terminar
Você deve esperar 5 minutos antes de reinstalar o plug-in naquele host.  Este período de tempo é suficiente para a GUI do SnapCenter atualizar o status do host gerenciado.  A instalação falhará se você reinstalar o plug-in imediatamente.

Se você estiver desinstalando o pacote de plug-ins do SnapCenter para Linux, os arquivos de log específicos da desinstalação estarão disponíveis em: _/custom_location/snapcenter/log_.
