---
permalink: uninstall/task_uninstall_plug_ins_locally_on_a_host.html 
sidebar: sidebar 
keywords: uninstall, uninstall plug-in locally, uninstall plug-in from a host 
summary: Você pode desinstalar os plug-ins do SnapCenter localmente em um host se não conseguir acessar o host a partir do SnapCenter Server. 
---
= Desinstalar plug-ins localmente em um host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desinstalar os plug-ins do SnapCenter localmente em um host se não conseguir acessar o host a partir do SnapCenter Server.

.Sobre esta tarefa
A prática recomendada para desinstalar plug-ins individuais ou pacotes de plug-ins é usar a GUI do SnapCenter ou usar o cmdlet Uninstall-SmHostPackage na interface de linha de comando do host do SnapCenter Server.  Esses procedimentos ajudam o SnapCenter Server a se manter atualizado com quaisquer alterações.

No entanto, você pode ter uma rara necessidade de desinstalar plug-ins localmente.  Por exemplo, você pode ter executado uma tarefa de desinstalação do SnapCenter Server, mas a tarefa falhou, ou você desinstalou o SnapCenter Server e plug-ins órfãos permanecem em um host.


IMPORTANT: Desinstalar um pacote de plug-in localmente em um host não exclui dados associados ao host; por exemplo, trabalhos agendados e metadados de backup.


IMPORTANT: Não tente desinstalar o pacote de plug-ins do SnapCenter para Windows localmente pelo Painel de Controle.  Você deve usar a interface gráfica do usuário do SnapCenter para garantir que o SnapCenter Plug-in para Microsoft Windows seja desinstalado corretamente.

.Passos
. No sistema host, navegue até o Painel de Controle e clique em *Desinstalar um programa*.
. Na lista de programas, selecione o plug-in ou pacote de plug-ins do SnapCenter que você deseja desinstalar e clique em *Desinstalar*.
+
O Windows desinstala todos os plug-ins no pacote selecionado.


