---
permalink: uninstall/uninstall_snapcenter_server_linux.html 
sidebar: sidebar 
keywords: uninstall, snapcenter server, linux 
summary: Se não desejar mais usar o SnapCenter Server para gerenciar tarefas de proteção de dados, você pode desinstalar o SnapCenter Server. 
---
= Desinstalar o SnapCenter Server no host Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se não desejar mais usar o SnapCenter Server para gerenciar tarefas de proteção de dados, você pode desinstalar o SnapCenter Server.  Desinstalar o SnapCenter Server remove todos os seus componentes.

.Passos
. Execute uma das ações para desinstalar o SnapCenter Server.
+
|===
| Se você quiser executar... | Faça isso... 


 a| 
Desinstalação não interativa
 a| 
`$ sudo /opt/NetApp/snapcenter/SnapManagerWeb/installation/uninstall -i silent -DCONFIRM=1`

Exemplo: sudo /opt/ NetApp/snapcenter/SnapManagerWeb/installation/uninstall



 a| 
Desinstalação interativa
 a| 
`$ sudo <USER_INSTALL_DIR>/NetApp/snapcenter/SnapManagerWeb/installation/uninstall`

Digite qualquer valor diferente de 0 na entrada de confirmação para confirmar a desinstalação.

|===

