---
permalink: protect-mysql/types-of-restore-strategies-supported-for-manually-added-mysql.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Você deve definir uma estratégia antes de poder executar com sucesso operações de restauração usando o SnapCenter.  Existem dois tipos de estratégias de restauração para recursos MySQL adicionados manualmente.  Não é possível recuperar recursos MySQL adicionados manualmente. 
---
= Tipos de estratégias de restauração suportadas para recursos MySQL adicionados manualmente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve definir uma estratégia antes de poder executar com sucesso operações de restauração usando o SnapCenter.  Existem dois tipos de estratégias de restauração para recursos MySQL adicionados manualmente.


NOTE: Não é possível recuperar recursos MySQL adicionados manualmente.



== Restauração completa de recursos

* Restaura todos os volumes, qtrees e LUNs de um recurso



NOTE: Se o recurso contiver volumes ou qtrees, os instantâneos tirados após o instantâneo selecionado para restauração nesses volumes ou qtrees serão excluídos e não poderão ser recuperados.  Além disso, se qualquer outro recurso estiver hospedado nos mesmos volumes ou qtrees, esse recurso também será excluído.
